import { randomBytes } from "node:crypto";
import { writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { execSync } from "node:child_process";

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, "..");
const envPath = resolve(projectRoot, ".env.local");

if (existsSync(envPath)) {
  console.log(".env.local already exists, skipping generation.");
  process.exit(0);
}

function generateSecret(bytes = 32) {
  return randomBytes(bytes).toString("base64");
}

function generateVapidKeys() {
  try {
    const result = execSync("npx web-push generate-vapid-keys", {
      encoding: "utf-8",
      stdio: "pipe",
    });
    const publicKey = result.match(/Public Key:\s*(\S+)/)?.[1] ?? "";
    const privateKey = result.match(/Private Key:\s*(\S+)/)?.[1] ?? "";
    return { publicKey, privateKey };
  } catch {
    console.warn(
      "Could not generate VAPID keys (web-push not installed?). Using placeholders.",
    );
    return { publicKey: "", privateKey: "" };
  }
}

const authSecret = generateSecret(32);
const { publicKey: vapidPublic, privateKey: vapidPrivate } =
  generateVapidKeys();

const template = `# ============================================
# SQL Trainer — Environment Variables
# Generated by scripts/generate-env.mjs
# ============================================

# Server
PORT=3000
NEXTAUTH_URL=http://localhost:3000

# Authentication (NextAuth.js v5)
AUTH_SECRET=${authSecret}

# Database
DATABASE_PATH=./data/users.db

# Email (SMTP)
SMTP_HOST=smtp.example.com
SMTP_PORT=587
SMTP_SECURE=false
SMTP_USER=your-smtp-user
SMTP_PASS=your-smtp-password
SMTP_FROM=SQL Trainer <noreply@example.com>

# Push Notifications (VAPID)
VAPID_PUBLIC_KEY=${vapidPublic || "your-vapid-public-key"}
VAPID_PRIVATE_KEY=${vapidPrivate || "your-vapid-private-key"}
VAPID_SUBJECT=mailto:your-email@example.com
`;

writeFileSync(envPath, template, "utf-8");
console.log("Generated .env.local with random AUTH_SECRET.");
if (vapidPublic) {
  console.log("VAPID keys generated for push notifications.");
}
