/**
 * Advanced Task Definitions
 * Auto-generated from training-tasks.ts
 */

import type { TrainingTask } from './types';
import { ANALYTICS_SCHEMA, CLICKHOUSE_EVENTS_SCHEMA, EMPLOYEES_SCHEMA, EMPTY_ORDERS_SCHEMA, INDEX_DEMO_SCHEMA, SHOP_SCHEMA } from './schemas';

export const ADVANCED_TASKS: TrainingTask[] = [

  // ==================== ADVANCED TASKS ====================
  {
    id: 'advanced-1',
    title: 'Оконные функции — ROW_NUMBER',
    description: 'Нумерация строк с помощью ROW_NUMBER',
    difficulty: 'advanced',
    dbType: 'sqlite',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Присвойте каждому сотруднику ранг по зарплате внутри своего отдела (1 — самая высокая зарплата). Выведите: department_id, first_name, last_name, salary, rank.',
    hint: 'Оконные функции вычисляют значение для каждой строки, не "схлопывая" группы как GROUP BY. PARTITION BY делит строки на группы (как GROUP BY), ORDER BY внутри окна определяет порядок. ROW_NUMBER() присваивает уникальный номер 1, 2, 3... каждой строке внутри партиции.',
    sampleSolution: 'SELECT department_id, first_name, last_name, salary, ROW_NUMBER() OVER (PARTITION BY department_id ORDER BY salary DESC) as rank FROM employees WHERE department_id IS NOT NULL ORDER BY department_id, rank;',
    verificationQuery: 'SELECT COUNT(*) as count FROM employees WHERE department_id IS NOT NULL;',
  },

  {
    id: 'advanced-2',
    title: 'Оконные функции — RANK и DENSE_RANK',
    description: 'Ранжирование с пропусками и без',
    difficulty: 'advanced',
    dbType: 'sqlite',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Выведите отделы, общее количество часов работы по отделу и долю каждого проекта в общих часах отдела. Используйте SUM() с оконной функцией.',
    hint: 'SUM(hours_worked) OVER (PARTITION BY department_id) даст сумму по отделу.',
    sampleSolution: 'SELECT p.name as project_name, d.name as department_name, a.hours_worked, SUM(a.hours_worked) OVER (PARTITION BY p.department_id) as dept_total_hours, ROUND(CAST(a.hours_worked AS REAL) / SUM(a.hours_worked) OVER (PARTITION BY p.department_id) * 100, 1) as percentage FROM assignments a JOIN projects p ON a.project_id = p.id JOIN departments d ON p.department_id = d.id ORDER BY d.name, a.hours_worked DESC;',
    verificationQuery: 'SELECT COUNT(DISTINCT p.department_id) as count FROM assignments a JOIN projects p ON a.project_id = p.id;',
  },

  {
    id: 'advanced-3',
    title: 'CTE (WITH clause)',
    description: 'Общие табличные выражения',
    difficulty: 'advanced',
    dbType: 'sqlite',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Используя CTE, найдите отделы, где суммарный бюджет отдела больше суммарной зарплаты всех его сотрудников.',
    hint: 'CTE (WITH) — это именованный подзапрос, который делает сложные запросы читаемее. В отличие от подзапроса в FROM, CTE можно использовать несколько раз в запросе и он лучше читается. Сначала определите в CTE сумму зарплат по отделам, затем сравните с бюджетом.',
    sampleSolution: 'WITH dept_salaries AS (SELECT department_id, SUM(salary) as total_salary FROM employees WHERE department_id IS NOT NULL GROUP BY department_id) SELECT d.name, d.budget, ds.total_salary, d.budget - ds.total_salary as surplus FROM departments d JOIN dept_salaries ds ON d.id = ds.department_id WHERE d.budget > ds.total_salary;',
    verificationQuery: 'SELECT COUNT(*) as count FROM (SELECT d.id FROM departments d JOIN (SELECT department_id, SUM(salary) as total_salary FROM employees WHERE department_id IS NOT NULL GROUP BY department_id) ds ON d.id = ds.department_id WHERE d.budget > ds.total_salary);',
  },

  {
    id: 'advanced-4',
    title: 'Рекурсивный CTE',
    description: 'Рекурсивные запросы для иерархических данных',
    difficulty: 'advanced',
    dbType: 'sqlite',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Создайте рекурсивный CTE, который генерирует таблицу чисел от 1 до 10, и для каждого числа выведите его квадрат и куб.',
    hint: 'Базовый случай: SELECT 1 as n. Рекурсия: SELECT n+1 FROM cte WHERE n < 10.',
    sampleSolution: 'WITH RECURSIVE numbers AS (SELECT 1 as n UNION ALL SELECT n + 1 FROM numbers WHERE n < 10) SELECT n, n * n as square, n * n * n as cube FROM numbers;',
    verificationQuery: 'SELECT 10 as expected_count;',
  },

  {
    id: 'advanced-5',
    title: 'Самосоединение (Self Join)',
    description: 'Соединение таблицы с самой собой',
    difficulty: 'advanced',
    dbType: 'sqlite',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Найдите все пары сотрудников из одного отдела, у которых разница в зарплате более 5000. Выведите имена обоих сотрудников и разницу в зарплате.',
    hint: 'Соедините employees с самой же таблицей по department_id, но с разными алиасами. Исключите совпадения и дубликаты.',
    sampleSolution: 'SELECT e1.first_name as emp1_name, e1.last_name as emp1_last, e2.first_name as emp2_name, e2.last_name as emp2_last, ABS(e1.salary - e2.salary) as salary_diff FROM employees e1 JOIN employees e2 ON e1.department_id = e2.department_id AND e1.id < e2.id WHERE ABS(e1.salary - e2.salary) > 5000 ORDER BY salary_diff DESC;',
    verificationQuery: 'SELECT COUNT(*) as count FROM employees e1 JOIN employees e2 ON e1.department_id = e2.department_id AND e1.id < e2.id WHERE ABS(e1.salary - e2.salary) > 5000;',
  },

  {
    id: 'advanced-6',
    title: 'Сложный запрос с подзапросами',
    description: 'Комбинация подзапросов и JOIN',
    difficulty: 'advanced',
    dbType: 'sqlite',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Найдите сотрудников, которые работают над завершёнными проектами и при этом трудились больше 150 часов. Выведите имя сотрудника, название проекта, роль и часы.',
    hint: 'Подзапрос для завершённых проектов, затем JOIN с assignments и employees.',
    sampleSolution: "SELECT e.first_name, e.last_name, p.name as project_name, a.role, a.hours_worked FROM employees e JOIN assignments a ON e.id = a.employee_id JOIN projects p ON a.project_id = p.id WHERE p.status = 'completed' AND a.hours_worked > 150 ORDER BY a.hours_worked DESC;",
    verificationQuery: "SELECT COUNT(*) as count FROM employees e JOIN assignments a ON e.id = a.employee_id JOIN projects p ON a.project_id = p.id WHERE p.status = 'completed' AND a.hours_worked > 150;",
  },

  {
    id: 'advanced-7',
    title: 'Несколько CTE и аналитика',
    description: 'Многоуровневые CTE с оконными функциями',
    difficulty: 'advanced',
    dbType: 'sqlite',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Для каждого отдела выведите: название, кол-во сотрудников, среднюю зарплату, сотрудника с максимальной зарплатой и общее количество часов по проектам отдела.',
    hint: 'Используйте несколько CTE: один для статистики по сотрудникам, другой для часов по проектам.',
    sampleSolution: 'WITH emp_stats AS (SELECT department_id, COUNT(*) as emp_count, AVG(salary) as avg_salary, MAX(salary) as max_salary FROM employees WHERE department_id IS NOT NULL GROUP BY department_id), top_earners AS (SELECT e.department_id, e.first_name, e.last_name, e.salary, ROW_NUMBER() OVER (PARTITION BY e.department_id ORDER BY e.salary DESC) as rn FROM employees e WHERE e.department_id IS NOT NULL), project_hours AS (SELECT p.department_id, SUM(a.hours_worked) as total_hours FROM projects p JOIN assignments a ON p.id = a.project_id GROUP BY p.department_id) SELECT d.name as department, es.emp_count, ROUND(es.avg_salary) as avg_salary, te.first_name || \' \' || te.last_name as top_earner, te.salary as top_salary, COALESCE(ph.total_hours, 0) as total_project_hours FROM departments d LEFT JOIN emp_stats es ON d.id = es.department_id LEFT JOIN top_earners te ON d.id = te.department_id AND te.rn = 1 LEFT JOIN project_hours ph ON d.id = ph.department_id ORDER BY es.emp_count DESC;',
    verificationQuery: 'SELECT COUNT(*) as count FROM departments;',
  },

  {
    id: 'advanced-8',
    title: 'HAVING vs WHERE и NULL обработка',
    description: 'Фильтрация NULL значений и сложная агрегация',
    difficulty: 'advanced',
    dbType: 'sqlite',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Найдите проекты, в которых участвуют сотрудники из 3 и более разных отделов. Выведите название проекта и количество уникальных отделов.',
    hint: 'JOIN projects → assignments → employees, GROUP BY project, HAVING COUNT(DISTINCT department_id) >= 3.',
    sampleSolution: 'SELECT p.name as project_name, COUNT(DISTINCT e.department_id) as dept_count FROM projects p JOIN assignments a ON p.id = a.project_id JOIN employees e ON a.employee_id = e.id GROUP BY p.id, p.name HAVING COUNT(DISTINCT e.department_id) >= 3;',
    verificationQuery: 'SELECT 0 as expected_count;',
  },


  // ==================== NEW TOPIC TASKS ====================
  {
    id: 'advanced-9',
    title: 'Представления (VIEW)',
    description: 'Создание и использование VIEW',
    difficulty: 'advanced',
    dbType: 'sqlite',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Создайте представление active_employees, которое показывает только активных сотрудников (is_active = 1). Затем выберите все данные из этого представления.',
    hint: 'CREATE VIEW name AS SELECT ... FROM ... WHERE is_active = 1, затем SELECT * FROM name.',
    sampleSolution: 'CREATE VIEW active_employees AS SELECT * FROM employees WHERE is_active = 1; SELECT * FROM active_employees;',
    verificationQuery: 'SELECT COUNT(*) as count FROM employees WHERE is_active = 1;',
  },

  {
    id: 'advanced-10',
    title: 'Индексы (INDEX)',
    description: 'Создание и использование индексов',
    difficulty: 'advanced',
    dbType: 'sqlite',
    schema: INDEX_DEMO_SCHEMA,
    taskText: 'Создайте индекс idx_books_author на таблице books по столбцу author. Затем создайте составной индекс idx_books_genre_year по genre и published_year. Выведите все индексы для таблицы books.',
    hint: 'CREATE INDEX idx_name ON table(column). Для просмотра: SELECT * FROM sqlite_master WHERE type="index" AND tbl_name="books".',
    sampleSolution: "CREATE INDEX idx_books_author ON books(author); CREATE INDEX idx_books_genre_year ON books(genre, published_year); SELECT name FROM sqlite_master WHERE type='index' AND tbl_name='books';",
    verificationQuery: "SELECT COUNT(*) as count FROM sqlite_master WHERE type='index' AND tbl_name='books';",
  },

  {
    id: 'advanced-11',
    title: 'Коррелированный подзапрос с EXISTS',
    description: 'Подзапрос, зависящий от внешнего запроса',
    difficulty: 'advanced',
    dbType: 'sqlite',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Найдите отделы, в которых есть сотрудники с зарплатой больше 140000. Выведите название отдела. Используйте EXISTS.',
    hint: 'EXISTS (SELECT 1 FROM employees WHERE department_id = departments.id AND salary > 140000).',
    sampleSolution: "SELECT d.name FROM departments d WHERE EXISTS (SELECT 1 FROM employees e WHERE e.department_id = d.id AND e.salary > 140000);",
    verificationQuery: "SELECT COUNT(*) as count FROM departments d WHERE EXISTS (SELECT 1 FROM employees e WHERE e.department_id = d.id AND e.salary > 140000);",
  },


  // ==================== SUBQUERIES IN SELECT/FROM ====================
  {
    id: 'advanced-12',
    title: 'Скалярный подзапрос в SELECT',
    description: 'Подзапрос, возвращающий одно значение в SELECT',
    difficulty: 'advanced',
    dbType: 'sqlite',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Для каждого сотрудника выведите first_name, salary и разницу между его зарплатой и максимальной зарплатой в компании.',
    hint: 'Подзапрос (SELECT MAX(salary) FROM employees) в SELECT вернет максимальную зарплату для каждой строки.',
    sampleSolution: 'SELECT first_name, salary, (SELECT MAX(salary) FROM employees) - salary as diff_from_max FROM employees ORDER BY diff_from_max;',
    verificationQuery: 'SELECT COUNT(*) as count FROM employees;',
  },

  {
    id: 'advanced-13',
    title: 'Табличный подзапрос в FROM',
    description: 'Использование подзапроса как таблицы',
    difficulty: 'advanced',
    dbType: 'sqlite',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Найдите сотрудников, чья зарплата выше средней по их отделу. Используйте подзапрос в FROM для расчета средних зарплат по отделам.',
    hint: 'Создайте подзапрос с AVG(salary) GROUP BY department_id в FROM, затем JOIN с employees.',
    sampleSolution: 'SELECT e.first_name, e.last_name, e.salary, e.department_id, dept_avg.avg_salary FROM employees e JOIN (SELECT department_id, AVG(salary) as avg_salary FROM employees WHERE department_id IS NOT NULL GROUP BY department_id) dept_avg ON e.department_id = dept_avg.department_id WHERE e.salary > dept_avg.avg_salary ORDER BY e.department_id, e.salary DESC;',
    verificationQuery: 'SELECT COUNT(*) as count FROM employees e JOIN (SELECT department_id, AVG(salary) as avg_salary FROM employees WHERE department_id IS NOT NULL GROUP BY department_id) dept_avg ON e.department_id = dept_avg.department_id WHERE e.salary > dept_avg.avg_salary;',
  },

  {
    id: 'advanced-14',
    title: 'Подзапрос в WHERE с IN',
    description: 'Фильтрация по списку значений из подзапроса',
    difficulty: 'advanced',
    dbType: 'sqlite',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Найдите сотрудников, которые работают над проектами со статусом "active". Используйте IN с подзапросом.',
    hint: 'Подзапрос SELECT employee_id FROM assignments JOIN projects WHERE status = "active".',
    sampleSolution: "SELECT first_name, last_name FROM employees WHERE id IN (SELECT a.employee_id FROM assignments a JOIN projects p ON a.project_id = p.id WHERE p.status = 'active');",
    verificationQuery: "SELECT COUNT(*) as count FROM employees WHERE id IN (SELECT a.employee_id FROM assignments a JOIN projects p ON a.project_id = p.id WHERE p.status = 'active');",
  },


  // ==================== WINDOW FUNCTIONS LAG/LEAD ====================
  {
    id: 'advanced-15',
    title: 'LAG — доступ к предыдущей строке',
    description: 'Получение значения из предыдущей строки',
    difficulty: 'advanced',
    dbType: 'sqlite',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Для каждого сотрудника выведите first_name, salary и зарплату предыдущего сотрудника (при сортировке по salary).',
    hint: 'LAG(salary) OVER (ORDER BY salary) вернет зарплату предыдущей строки.',
    sampleSolution: 'SELECT first_name, salary, LAG(salary) OVER (ORDER BY salary) as prev_salary FROM employees WHERE department_id IS NOT NULL ORDER BY salary;',
    verificationQuery: 'SELECT COUNT(*) as count FROM employees WHERE department_id IS NOT NULL;',
  },

  {
    id: 'advanced-16',
    title: 'LEAD — доступ к следующей строке',
    description: 'Получение значения из следующей строки',
    difficulty: 'advanced',
    dbType: 'sqlite',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Для каждого сотрудника выведите first_name, salary и разницу с зарплатой следующего сотрудника (при сортировке по salary).',
    hint: 'LEAD(salary) OVER (ORDER BY salary) - salary даст разницу.',
    sampleSolution: 'SELECT first_name, salary, LEAD(salary) OVER (ORDER BY salary) - salary as diff_to_next FROM employees WHERE department_id IS NOT NULL ORDER BY salary;',
    verificationQuery: 'SELECT COUNT(*) as count FROM employees WHERE department_id IS NOT NULL;',
  },

  {
    id: 'advanced-17',
    title: 'FIRST_VALUE и LAST_VALUE',
    description: 'Первое и последнее значение в окне',
    difficulty: 'advanced',
    dbType: 'sqlite',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Для каждого отдела выведите сотрудника, его зарплату, минимальную и максимальную зарплату в этом отделе.',
    hint: 'FIRST_VALUE(salary) OVER (PARTITION BY department_id ORDER BY salary) и LAST_VALUE с ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING.',
    sampleSolution: 'SELECT first_name, department_id, salary, FIRST_VALUE(salary) OVER (PARTITION BY department_id ORDER BY salary) as min_dept_salary, LAST_VALUE(salary) OVER (PARTITION BY department_id ORDER BY salary ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) as max_dept_salary FROM employees WHERE department_id IS NOT NULL ORDER BY department_id, salary;',
    verificationQuery: 'SELECT COUNT(*) as count FROM employees WHERE department_id IS NOT NULL;',
  },


  // ==================== TRIGGERS ====================
  {
    id: 'advanced-18',
    title: 'Триггер AFTER INSERT',
    description: 'Автоматическое действие после вставки',
    difficulty: 'advanced',
    dbType: 'sqlite',
    schema: EMPTY_ORDERS_SCHEMA,
    taskText: 'Создайте триггер, который автоматически уменьшает stock продукта при создании заказа. Затем создайте заказ и проверьте, что stock обновился.',
    hint: 'CREATE TRIGGER after_order_insert AFTER INSERT ON orders BEGIN UPDATE products SET stock = stock - NEW.quantity WHERE id = NEW.product_id; END;',
    sampleSolution: "CREATE TRIGGER after_order_insert AFTER INSERT ON orders BEGIN UPDATE products SET stock = stock - NEW.quantity WHERE id = NEW.product_id; END; INSERT INTO orders (product_id, quantity, order_date, customer_name) VALUES (1, 2, '2024-03-01', 'Сидоров'); SELECT stock FROM products WHERE id = 1;",
    verificationQuery: 'SELECT stock FROM products WHERE id = 1;',
  },

  {
    id: 'advanced-19',
    title: 'Триггер BEFORE UPDATE',
    description: 'Проверка данных перед обновлением',
    difficulty: 'advanced',
    dbType: 'sqlite',
    schema: EMPTY_ORDERS_SCHEMA,
    taskText: 'Создайте триггер, который предотвращает отрицательный stock. Попробуйте установить stock=-5 для продукта id=1 и посмотрите результат.',
    hint: 'CREATE TRIGGER before_product_update BEFORE UPDATE ON products WHEN NEW.stock < 0 BEGIN SELECT RAISE(ABORT, "Stock не может быть отрицательным"); END;',
    sampleSolution: 'CREATE TRIGGER before_product_update BEFORE UPDATE ON products WHEN NEW.stock < 0 BEGIN SELECT RAISE(ABORT, "Stock не может быть отрицательным"); END; UPDATE products SET stock = -5 WHERE id = 1;',
    verificationQuery: 'SELECT stock FROM products WHERE id = 1;',
  },


  // ==================== FULL-TEXT SEARCH ====================
  {
    id: 'advanced-20',
    title: 'FTS5 — полнотекстовый поиск',
    description: 'Создание FTS5 таблицы и поиск по тексту',
    difficulty: 'advanced',
    dbType: 'sqlite',
    schema: '',
    taskText: 'Создайте FTS5 таблицу articles с колонками title и content. Добавьте 3 статьи. Найдите статьи, содержащие слово "база".',
    hint: 'CREATE VIRTUAL TABLE articles USING fts5(title, content). Поиск: SELECT * FROM articles WHERE articles MATCH "база".',
    sampleSolution: "CREATE VIRTUAL TABLE articles USING fts5(title, content); INSERT INTO articles VALUES ('SQL основы', 'База данных — это система для хранения данных'); INSERT INTO articles VALUES ('NoSQL подходы', 'Документо-ориентированные базы данных'); INSERT INTO articles VALUES ('Программирование', 'Python для веб-разработки'); SELECT title FROM articles WHERE articles MATCH 'база';",
    verificationQuery: "SELECT COUNT(*) as count FROM articles WHERE articles MATCH 'база';",
  },

  {
    id: 'advanced-21',
    title: 'FTS5 — расширенный поиск',
    description: 'Поиск с префиксами и логическими операторами',
    difficulty: 'advanced',
    dbType: 'sqlite',
    schema: '',
    taskText: 'Используя FTS5 таблицу articles из предыдущего задания, найдите статьи, содержащие "данные" И "хран". Используйте префиксный поиск.',
    hint: 'MATCH "данные AND хран*" для поиска с префиксом.',
    sampleSolution: "SELECT title FROM articles WHERE articles MATCH 'данные AND хран*';",
    verificationQuery: "SELECT COUNT(*) as count FROM articles WHERE articles MATCH 'данные AND хран*';",
  },


  // ==================== JSON FUNCTIONS ====================
  {
    id: 'advanced-22',
    title: 'JSON — извлечение данных',
    description: 'json_extract для получения значений из JSON',
    difficulty: 'advanced',
    dbType: 'sqlite',
    schema: '',
    taskText: 'Создайте таблицу users с колонком data типа TEXT (JSON). Добавьте пользователей с полями name, age, city. Извлеките имя и город каждого пользователя.',
    hint: 'json_extract(data, "$.name") или data->"$.name" для извлечения.',
    sampleSolution: "CREATE TABLE users (id INTEGER PRIMARY KEY, data TEXT); INSERT INTO users (data) VALUES ('{\"name\": \"Алексей\", \"age\": 30, \"city\": \"Москва\"}'); INSERT INTO users (data) VALUES ('{\"name\": \"Мария\", \"age\": 25, \"city\": \"Санкт-Петербург\"}'); SELECT json_extract(data, '$.name') as name, json_extract(data, '$.city') as city FROM users;",
    verificationQuery: 'SELECT COUNT(*) as count FROM users;',
  },

  {
    id: 'advanced-23',
    title: 'JSON — фильтрация и агрегация',
    description: 'Фильтрация по JSON полям и создание JSON',
    difficulty: 'advanced',
    dbType: 'sqlite',
    schema: '',
    taskText: 'Используя таблицу users, найдите пользователей старше 25 лет. Создайте JSON объект с их именем и городом.',
    hint: 'json_extract(data, "$.age") > 25 для фильтрации. json_object("name", ..., "city", ...) для создания JSON.',
    sampleSolution: "SELECT json_object('name', json_extract(data, '$.name'), 'city', json_extract(data, '$.city')) as user_info FROM users WHERE json_extract(data, '$.age') > 25;",
    verificationQuery: "SELECT COUNT(*) as count FROM users WHERE json_extract(data, '$.age') > 25;",
  },

  {
    id: 'advanced-24',
    title: 'JSON — массивы',
    description: 'Работа с JSON массивами',
    difficulty: 'advanced',
    dbType: 'sqlite',
    schema: '',
    taskText: 'Создайте таблицу orders с JSON массивом items. Найдите заказы, содержащие товар "Ноутбук". Используйте json_each.',
    hint: 'json_each(items) возвращает таблицу элементов. EXISTS или JOIN с json_each.',
    sampleSolution: "CREATE TABLE orders (id INTEGER PRIMARY KEY, items TEXT); INSERT INTO orders (items) VALUES ('[\"Ноутбук\", \"Мышь\"]'); INSERT INTO orders (items) VALUES ('[\"Клавиатура\", \"Монитор\"]'); INSERT INTO orders (items) VALUES ('[\"Ноутбук\", \"Наушники\"]'); SELECT o.id FROM orders o, json_each(o.items) WHERE json_each.value = 'Ноутбук';",
    verificationQuery: "SELECT COUNT(*) as count FROM orders o, json_each(o.items) WHERE json_each.value = 'Ноутбук';",
  },


  // ==================== STORED PROCEDURES (SQLite doesn't support them, so we use a simulation) ====================
  {
    id: 'advanced-25',
    title: 'Имитация хранимых процедур',
    description: 'Использование CTE и сложных запросов вместо процедур',
    difficulty: 'advanced',
    dbType: 'sqlite',
    schema: EMPTY_ORDERS_SCHEMA,
    taskText: 'Создайте "процедуру" через CTE: для заданного product_id=1 проверьте stock, если > 0 создайте заказ и уменьшите stock. Используйте последовательность запросов.',
    hint: 'Несколько запросов: SELECT stock, INSERT INTO orders, UPDATE products. Проверьте stock > 0.',
    sampleSolution: "SELECT stock FROM products WHERE id = 1; INSERT INTO orders (product_id, quantity, order_date, customer_name) SELECT 1, 1, '2024-04-01', 'Козлов' FROM products WHERE id = 1 AND stock > 0; UPDATE products SET stock = stock - 1 WHERE id = 1 AND stock > 0; SELECT * FROM orders;",
    verificationQuery: 'SELECT COUNT(*) as count FROM orders WHERE customer_name = "Козлов";',
  },


  // ==================== SHOP TASKS ====================
  {
    id: 'pg-28',
    title: 'PostgreSQL: оператор @> (containment)',
    description: 'Проверка вхождения элементов в массив',
    difficulty: 'advanced',
    dbType: 'postgresql',
    category: 'shop',
    schema: SHOP_SCHEMA,
    taskText: 'Найдите товары, в описании которых есть слово «смартфон». Используйте string_to_array(description, \' \') для разбивки описания на массив слов и оператор @> для проверки вхождения. Выведите name и description.',
    hint: 'string_to_array(text, delimiter) разбивает строку на массив. Оператор @> проверяет, содержит ли левый массив все элементы правого массива.',
    sampleSolution: "SELECT name, description FROM products WHERE string_to_array(description, ' ') @> ARRAY['смартфон'];",
    verificationQuery: "SELECT COUNT(*) as count FROM products WHERE description LIKE '%смартфон%';",
  },

  {
    id: 'pg-32',
    title: 'PostgreSQL: коррелированный подзапрос',
    description: 'Подзапрос, зависящий от строки внешнего запроса',
    difficulty: 'advanced',
    dbType: 'postgresql',
    category: 'shop',
    schema: SHOP_SCHEMA,
    taskText: 'Найдите товары, цена которых выше средней цены в своей категории. Используйте коррелированный подзапрос: WHERE price > (SELECT AVG(price) FROM products WHERE category_id = p.category_id). Выведите name, price и category. Отсортируйте по category и price DESC.',
    hint: 'Коррелированный подзапрос выполняется заново для каждой строки внешнего запроса, подставляя p.category_id текущей строки.',
    sampleSolution: "SELECT p.name, p.price, c.name AS category FROM products p JOIN categories c ON p.category_id = c.id WHERE p.price > (SELECT AVG(p2.price) FROM products p2 WHERE p2.category_id = p.category_id) ORDER BY c.name, p.price DESC;",
    verificationQuery: "SELECT COUNT(*) as count FROM products p WHERE p.price > (SELECT AVG(p2.price) FROM products p2 WHERE p2.category_id = p.category_id);",
  },

  {
    id: 'pg-8',
    title: 'PostgreSQL: DISTINCT ON',
    description: 'Выбор первой строки для каждой группы',
    difficulty: 'advanced',
    dbType: 'postgresql',
    category: 'shop',
    schema: SHOP_SCHEMA,
    taskText: 'Для каждого клиента (customers) найдите самый дорогой заказ. Используйте DISTINCT ON (customer_id). Выведите customer_id, order_id, total_amount. Отсортируйте по customer_id.',
    hint: 'DISTINCT ON (customer_id) выбирает первую строку для каждого уникального customer_id при заданной сортировке.',
    sampleSolution: 'SELECT DISTINCT ON (customer_id) customer_id, id AS order_id, total_amount FROM orders ORDER BY customer_id, total_amount DESC;',
    verificationQuery: 'SELECT customer_id, id AS order_id, total_amount FROM orders o1 WHERE total_amount = (SELECT MAX(total_amount) FROM orders WHERE customer_id = o1.customer_id) ORDER BY customer_id;',
  },

  {
    id: 'pg-adv-3',
    title: 'PostgreSQL: FILTER в агрегации',
    description: 'Условная агрегация с помощью FILTER (WHERE)',
    difficulty: 'advanced',
    dbType: 'postgresql',
    category: 'shop',
    schema: SHOP_SCHEMA,
    taskText: 'Для каждого города доставки (shipping_city) из orders выведите: общее количество заказов, количество доставленных заказов и среднюю сумму только доставленных заказов. Используйте FILTER (WHERE ...).',
    hint: 'COUNT(*) FILTER (WHERE condition) считает строки только удовлетворяющие условию. AVG(col) FILTER (WHERE cond) считает среднее по условию.',
    sampleSolution: "SELECT shipping_city, COUNT(*) AS total_orders, COUNT(*) FILTER (WHERE status = 'delivered') AS delivered_orders, AVG(total_amount) FILTER (WHERE status = 'delivered') AS avg_delivered_amount FROM orders GROUP BY shipping_city ORDER BY total_orders DESC;",
    verificationQuery: 'SELECT COUNT(DISTINCT shipping_city) as count FROM orders;',
  },

  {
    id: 'shop-a1',
    title: 'Рейтинг продаж товаров',
    description: 'ROW_NUMBER для ранжирования продаж',
    difficulty: 'advanced',
    dbType: 'sqlite',
    category: 'shop',
    schema: SHOP_SCHEMA,
    taskText: 'Присвойте каждому товару ранг по суммарной выручке (unit_price * quantity). Выведите: название товара, категорию, суммарную выручку и ранг.',
    hint: 'CTE для выручки по товарам, затем ROW_NUMBER() OVER (ORDER BY revenue DESC).',
    sampleSolution: 'WITH product_revenue AS (SELECT p.name, c.name as category_name, SUM(oi.unit_price * oi.quantity) as revenue FROM order_items oi JOIN products p ON oi.product_id = p.id JOIN categories c ON p.category_id = c.id GROUP BY p.id, p.name, c.name) SELECT name, category_name, revenue, ROW_NUMBER() OVER (ORDER BY revenue DESC) as rank FROM product_revenue ORDER BY rank;',
    verificationQuery: 'SELECT COUNT(DISTINCT product_id) as count FROM order_items;',
  },

  {
    id: 'shop-a2',
    title: 'Помесячная выручка',
    description: 'CTE + GROUP BY по месяцам',
    difficulty: 'advanced',
    dbType: 'sqlite',
    category: 'shop',
    schema: SHOP_SCHEMA,
    taskText: 'Выведите помесячную выручку магазина за 2023 год. Для каждого месяца: месяц (в формате "YYYY-MM"), общую сумму заказов и количество заказов.',
    hint: 'SUBSTR(order_date, 1, 7) извлечёт "YYYY-MM". GROUP BY по этому значению. WHERE order_date LIKE "2023%".',
    sampleSolution: "SELECT SUBSTR(order_date, 1, 7) as month, SUM(total_amount) as total_revenue, COUNT(*) as order_count FROM orders WHERE order_date LIKE '2023%' GROUP BY SUBSTR(order_date, 1, 7) ORDER BY month;",
    verificationQuery: "SELECT COUNT(DISTINCT SUBSTR(order_date, 1, 7)) as count FROM orders WHERE order_date LIKE '2023%';",
  },

  {
    id: 'shop-a3',
    title: 'Аналитика по клиентам',
    description: 'Несколько CTE для отчёта LTV',
    difficulty: 'advanced',
    dbType: 'sqlite',
    category: 'shop',
    schema: SHOP_SCHEMA,
    taskText: 'Для каждого клиента выведите: имя, количество заказов, общую сумму покупок, средний чек, дату первого и последнего заказа. Только клиенты с заказами.',
    hint: 'Один CTE: GROUP BY customer_id с MIN/MAX/COUNT/SUM/AVG.',
    sampleSolution: 'SELECT c.first_name, c.last_name, c.city, COUNT(o.id) as order_count, SUM(o.total_amount) as total_spent, ROUND(AVG(o.total_amount)) as avg_check, MIN(o.order_date) as first_order, MAX(o.order_date) as last_order FROM customers c JOIN orders o ON c.id = o.customer_id GROUP BY c.id, c.first_name, c.last_name, c.city ORDER BY total_spent DESC;',
    verificationQuery: 'SELECT COUNT(DISTINCT customer_id) as count FROM orders;',
  },

  {
    id: 'shop-a4',
    title: 'Сравнение товаров в категории',
    description: 'Self-join для сравнения цен',
    difficulty: 'advanced',
    dbType: 'sqlite',
    category: 'shop',
    schema: SHOP_SCHEMA,
    taskText: 'Найдите пары товаров из одной категории, разница в цене между которыми более 10000 рублей. Выведите названия обоих товаров, категорию и разницу в цене.',
    hint: 'Self-join products по category_id с условием p1.id < p2.id и ABS(p1.price - p2.price) > 10000.',
    sampleSolution: "SELECT p1.name as product_1, p2.name as product_2, c.name as category, ABS(p1.price - p2.price) as price_diff FROM products p1 JOIN products p2 ON p1.category_id = p2.category_id AND p1.id < p2.id JOIN categories c ON p1.category_id = c.id WHERE ABS(p1.price - p2.price) > 10000 ORDER BY price_diff DESC;",
    verificationQuery: "SELECT COUNT(*) as count FROM products p1 JOIN products p2 ON p1.category_id = p2.category_id AND p1.id < p2.id WHERE ABS(p1.price - p2.price) > 10000;",
  },

  {
    id: 'shop-a5',
    title: 'Полный отчёт по категориям',
    description: 'Множественные CTE + оконные функции',
    difficulty: 'advanced',
    dbType: 'sqlite',
    category: 'shop',
    schema: SHOP_SCHEMA,
    taskText: 'Для каждой категории выведите: название, количество товаров, среднюю цену, суммарную выручку, количество отзывов и средний рейтинг. Отсортируйте по убыванию выручки.',
    hint: '3 CTE: статы товаров, статы выручки, статы отзывов. JOIN по category_id.',
    sampleSolution: 'WITH prod_stats AS (SELECT category_id, COUNT(*) as product_count, ROUND(AVG(price)) as avg_price FROM products GROUP BY category_id), revenue_stats AS (SELECT p.category_id, SUM(oi.unit_price * oi.quantity) as total_revenue FROM order_items oi JOIN products p ON oi.product_id = p.id GROUP BY p.category_id), review_stats AS (SELECT p.category_id, COUNT(r.id) as review_count, ROUND(AVG(r.rating), 1) as avg_rating FROM reviews r JOIN products p ON r.product_id = p.id GROUP BY p.category_id) SELECT c.name as category, ps.product_count, ps.avg_price, COALESCE(rs.total_revenue, 0) as total_revenue, COALESCE(rv.review_count, 0) as review_count, COALESCE(rv.avg_rating, 0) as avg_rating FROM categories c LEFT JOIN prod_stats ps ON c.id = ps.category_id LEFT JOIN revenue_stats rs ON c.id = rs.category_id LEFT JOIN review_stats rv ON c.id = rv.category_id ORDER BY total_revenue DESC;',
    verificationQuery: 'SELECT COUNT(*) as count FROM categories;',
  },

  {
    id: 'shop-a6',
    title: 'Динамика заказов (LAG)',
    description: 'Оконная функция LAG для сравнения',
    difficulty: 'advanced',
    dbType: 'sqlite',
    category: 'shop',
    schema: SHOP_SCHEMA,
    taskText: 'Для каждого клиента выведите все заказы с предыдущей суммой заказа. Выведите: имя клиента, дату заказа, сумму и предыдущую сумму (prev_amount). Используйте LAG.',
    hint: 'LAG(total_amount) OVER (PARTITION BY customer_id ORDER BY order_date) даст предыдущую сумму.',
    sampleSolution: "SELECT c.first_name, c.last_name, o.order_date, o.total_amount, LAG(o.total_amount) OVER (PARTITION BY o.customer_id ORDER BY o.order_date) as prev_amount FROM orders o JOIN customers c ON o.customer_id = c.id ORDER BY c.last_name, o.order_date;",
    verificationQuery: 'SELECT COUNT(*) as count FROM orders o JOIN customers c ON o.customer_id = c.id;',
  },


  // ==================== COMPANY TASKS (PostgreSQL/ClickHouse) ====================
  {
    id: 'pg-18',
    title: 'PostgreSQL: LATERAL JOIN',
    description: 'Подзапрос в FROM, зависящий от внешней таблицы',
    difficulty: 'advanced',
    dbType: 'postgresql',
    category: 'company',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Для каждого отдела найдите сотрудника с самой высокой зарплатой. Используйте LATERAL JOIN: подзапрос ссылается на столбец departments.id из внешнего запроса. Выведите name отдела, first_name, last_name и salary. Отсортируйте по name отдела.',
    hint: 'CROSS JOIN LATERAL (SELECT ... WHERE department_id = d.id ORDER BY salary DESC LIMIT 1) позволяет подзапросу использовать d.id из внешней таблицы.',
    sampleSolution: "SELECT d.name, top_emp.first_name, top_emp.last_name, top_emp.salary FROM departments d CROSS JOIN LATERAL (SELECT e.first_name, e.last_name, e.salary FROM employees e WHERE e.department_id = d.id ORDER BY e.salary DESC LIMIT 1) top_emp ORDER BY d.name;",
    verificationQuery: "SELECT COUNT(*) as count FROM departments WHERE (SELECT COUNT(*) FROM employees WHERE department_id = departments.id) > 0;",
  },

  {
    id: 'pg-20',
    title: 'PostgreSQL: оконные функции — RANGE',
    description: 'Разница зарплаты от средней по отделу',
    difficulty: 'advanced',
    dbType: 'postgresql',
    category: 'company',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Для каждого сотрудника вычислите разницу между его зарплатой и средней зарплатой по отделу. Используйте оконную функцию AVG(salary) OVER (PARTITION BY department_id). Выведите first_name, last_name, department, salary и salary_diff (округлите до 2 знаков). Отсортируйте по отделу и разнице.',
    hint: 'AVG(salary) OVER (PARTITION BY department_id) вычисляет среднюю зарплату по отделу для каждой строки. Вычтите её из текущей зарплаты.',
    sampleSolution: "SELECT e.first_name, e.last_name, d.name AS department, e.salary, ROUND(e.salary - AVG(e.salary) OVER (PARTITION BY e.department_id), 2) AS salary_diff FROM employees e JOIN departments d ON e.department_id = d.id ORDER BY d.name, salary_diff;",
    verificationQuery: 'SELECT COUNT(*) as count FROM employees e JOIN departments d ON e.department_id = d.id;',
  },

  {
    id: 'pg-31',
    title: 'PostgreSQL: HAVING с подзапросом',
    description: 'Фильтрация групп по результату подзапроса',
    difficulty: 'advanced',
    dbType: 'postgresql',
    category: 'company',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Найдите отделы, где средняя зарплата сотрудников выше общей средней зарплаты по всей компании. Используйте скалярный подзапрос внутри HAVING. Выведите name отдела и avg_salary (округлите до 2 знаков). Отсортируйте по avg_salary DESC.',
    hint: 'HAVING AVG(e.salary) > (SELECT AVG(salary) FROM employees) — подзапрос вычисляет общую среднюю, а HAVING фильтрует отделы, чья средняя выше.',
    sampleSolution: "SELECT d.name, ROUND(AVG(e.salary), 2) AS avg_salary FROM employees e JOIN departments d ON e.department_id = d.id GROUP BY d.name HAVING AVG(e.salary) > (SELECT AVG(salary) FROM employees) ORDER BY avg_salary DESC;",
    verificationQuery: "SELECT COUNT(*) as count FROM (SELECT d.name FROM employees e JOIN departments d ON e.department_id = d.id GROUP BY d.name HAVING AVG(e.salary) > (SELECT AVG(salary) FROM employees));",
  },

  {
    id: 'pg-6',
    title: 'PostgreSQL: RETURNING',
    description: 'Использование RETURNING для получения данных после INSERT',
    difficulty: 'advanced',
    dbType: 'postgresql',
    category: 'company',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Напишите INSERT нового сотрудника: first_name = \'Тест\', last_name = \'Тестов\', email = \'test@company.ru\', department_id = 1, salary = 100000, hire_date = \'2024-01-01\', is_active = TRUE. Используйте RETURNING *, чтобы вернуть все столбцы добавленной записи.',
    hint: 'INSERT INTO ... VALUES (...) RETURNING * вернёт вставленную строку целиком.',
    sampleSolution: "INSERT INTO employees (first_name, last_name, email, department_id, salary, hire_date, is_active) VALUES ('Тест', 'Тестов', 'test@company.ru', 1, 100000, '2024-01-01', TRUE) RETURNING *;",
    verificationQuery: "SELECT COUNT(*) as count FROM employees WHERE email = 'test@company.ru';",
  },

  {
    id: 'pg-adv-1',
    title: 'PostgreSQL: DISTINCT ON — уникальные строки',
    description: 'Использование DISTINCT ON для выбора первой строки в группе',
    difficulty: 'advanced',
    dbType: 'postgresql',
    category: 'company',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Для каждого отдела (departments) выведите один сотрудника с самой высокой зарплатой. Используйте DISTINCT ON (department_id). Результат: department_id, first_name, last_name, salary. Отсортируйте по department_id, salary DESC.',
    hint: 'DISTINCT ON (col) возвращает первую строку для каждого уникального значения col. ORDER BY должен начинаться с того же столбца.',
    sampleSolution: "SELECT DISTINCT ON (department_id) department_id, first_name, last_name, salary FROM employees WHERE is_active = 1 ORDER BY department_id, salary DESC;",
    verificationQuery: 'SELECT COUNT(DISTINCT department_id) as count FROM employees WHERE is_active = 1;',
  },

  {
    id: 'pg-adv-2',
    title: 'PostgreSQL: UPSERT с ON CONFLICT',
    description: 'Вставка или обновление с помощью ON CONFLICT',
    difficulty: 'advanced',
    dbType: 'postgresql',
    category: 'company',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Напишите INSERT INTO для таблицы employees с ON CONFLICT DO UPDATE SET. Попытайтесь вставить сотрудника с id=1 (Иван Петров) но с зарплатой 200000. При конфликте обновите зарплату и hire_date.',
    hint: 'Синтаксис: INSERT INTO ... VALUES (...) ON CONFLICT (id) DO UPDATE SET salary = EXCLUDED.salary, hire_date = EXCLUDED.hire_date',
    sampleSolution: "INSERT INTO employees (id, first_name, last_name, email, department_id, salary, hire_date, is_active) VALUES (1, 'Иван', 'Петров', 'ivan_new@company.ru', 1, 200000, '2024-01-01', 1) ON CONFLICT (id) DO UPDATE SET salary = EXCLUDED.salary, hire_date = EXCLUDED.hire_date;",
    verificationQuery: "SELECT COUNT(*) as count FROM employees WHERE salary >= 200000;",
  },

  {
    id: 'pg-adv-4',
    title: 'PostgreSQL: GENERATE_SERIES + CROSS JOIN LATERAL',
    description: 'Генерация рядов и латеральное соединение',
    difficulty: 'advanced',
    dbType: 'postgresql',
    category: 'company',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Используя CROSS JOIN LATERAL, выведите для каждого отдела (departments) его название и зарплату топ-3 сотрудников этого отдела (first_name, last_name, salary). Подзапрос должен быть LIMIT 3 ORDER BY salary DESC.',
    hint: 'CROSS JOIN LATERAL позволяет подзапросу ссылаться на столбцы предыдущей таблицы. Структура: FROM departments CROSS JOIN LATERAL (SELECT ... FROM employees WHERE ... LIMIT 3) sub',
    sampleSolution: 'SELECT d.name AS department, sub.first_name, sub.last_name, sub.salary FROM departments d CROSS JOIN LATERAL (SELECT first_name, last_name, salary FROM employees e WHERE e.department_id = d.id AND e.is_active = 1 ORDER BY e.salary DESC LIMIT 3) sub ORDER BY d.name, sub.salary DESC;',
    verificationQuery: 'SELECT COUNT(DISTINCT department_id) as count FROM employees WHERE is_active = 1;',
  },


  // ==================== SQL CONSTRAINTS & DATA TYPES ====================
  {
    id: 'advanced-constraints-1',
    title: 'Ограничения: PRIMARY KEY и NOT NULL',
    description: 'Создание таблицы с первичным ключом и обязательными полями',
    difficulty: 'advanced',
    dbType: 'sqlite',
    schema: '',
    taskText: 'Создайте таблицу students с полями: id (INTEGER PRIMARY KEY), name (TEXT NOT NULL), email (TEXT NOT NULL). Добавьте одного студента. Выведите всех студентов.',
    hint: 'PRIMARY KEY автоматически делает столбец уникальным и NOT NULL. NOT NULL запрещает вставку NULL значений.',
    sampleSolution: "CREATE TABLE students (id INTEGER PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL); INSERT INTO students (name, email) VALUES ('Иванов', 'ivan@test.ru'); SELECT * FROM students;",
    verificationQuery: 'SELECT COUNT(*) as count FROM students;',
  },

  {
    id: 'advanced-constraints-2',
    title: 'Ограничение UNIQUE',
    description: 'Запрет дубликатов в столбце',
    difficulty: 'advanced',
    dbType: 'sqlite',
    schema: '',
    taskText: 'Создайте таблицу products с полями: id (INTEGER PRIMARY KEY), name (TEXT UNIQUE), price (REAL). Попробуйте вставить два товара с одинаковым именем. Выведите все товары.',
    hint: 'UNIQUE запрещает повторяющиеся значения. При попытке вставить дубликат возникнет ошибка.',
    sampleSolution: "CREATE TABLE products (id INTEGER PRIMARY KEY, name TEXT UNIQUE, price REAL); INSERT INTO products (name, price) VALUES ('Ноутбук', 50000), ('Мышь', 1500); SELECT * FROM products;",
    verificationQuery: 'SELECT COUNT(*) as count FROM products;',
  },

  {
    id: 'advanced-constraints-3',
    title: 'Ограничение CHECK',
    description: 'Проверка допустимых значений при вставке',
    difficulty: 'advanced',
    dbType: 'sqlite',
    schema: '',
    taskText: 'Создайте таблицу orders с полями: id (INTEGER PRIMARY KEY), quantity (INTEGER CHECK (quantity > 0)), price (REAL CHECK (price >= 0)). Вставьте заказ с quantity=5, price=1000. Выведите все заказы.',
    hint: 'CHECK (условие) проверяет данные при INSERT и UPDATE. Если условие ложное — вставка отклоняется.',
    sampleSolution: "CREATE TABLE orders (id INTEGER PRIMARY KEY, quantity INTEGER CHECK (quantity > 0), price REAL CHECK (price >= 0)); INSERT INTO orders (quantity, price) VALUES (5, 1000); SELECT * FROM orders;",
    verificationQuery: 'SELECT COUNT(*) as count FROM orders;',
  },

  {
    id: 'advanced-constraints-4',
    title: 'FOREIGN KEY — внешние ключи',
    description: 'Связь между таблицами с проверкой целостности',
    difficulty: 'advanced',
    dbType: 'sqlite',
    schema: '',
    taskText: 'Создайте таблицу departments (id INTEGER PRIMARY KEY, name TEXT). Создайте таблицу employees (id INTEGER PRIMARY KEY, name TEXT, dept_id INTEGER REFERENCES departments(id)). Вставьте отдел и сотрудника. Попробуйте вставить сотрудника с несуществующим dept_id.',
    hint: 'FOREIGN KEY (REFERENCES) обеспечивает ссылочную целостность: нельзя сослаться на несуществующую запись.',
    sampleSolution: "CREATE TABLE departments (id INTEGER PRIMARY KEY, name TEXT); CREATE TABLE employees (id INTEGER PRIMARY KEY, name TEXT, dept_id INTEGER REFERENCES departments(id)); INSERT INTO departments VALUES (1, 'IT'); INSERT INTO employees VALUES (1, 'Иванов', 1); SELECT e.name, d.name as dept FROM employees e JOIN departments d ON e.dept_id = d.id;",
    verificationQuery: 'SELECT COUNT(*) as count FROM employees;',
  },

  {
    id: 'advanced-datatypes-1',
    title: 'Типы данных: INTEGER vs REAL vs TEXT',
    description: 'Понимание различий типов данных в SQLite',
    difficulty: 'advanced',
    dbType: 'sqlite',
    schema: '',
    taskText: 'Создайте таблицу demo_types с полями: int_col INTEGER, real_col REAL, text_col TEXT. Вставьте значения: 42, 3.14, "Hello". Выведите все. Обратите внимание: SQLite динамически типизирован.',
    hint: 'INTEGER — целые числа, REAL — дробные, TEXT — строки. SQLite позволяет хранить любой тип в любом столбце, но лучше соблюдать declared тип.',
    sampleSolution: 'CREATE TABLE demo_types (int_col INTEGER, real_col REAL, text_col TEXT); INSERT INTO demo_types VALUES (42, 3.14, \'Hello\'); SELECT * FROM demo_types;',
    verificationQuery: 'SELECT COUNT(*) as count FROM demo_types;',
  },

  {
    id: 'advanced-datatypes-2',
    title: 'Типы данных: BOOLEAN и DATE в SQLite',
    description: 'Как SQLite хранит логические значения и даты',
    difficulty: 'advanced',
    dbType: 'sqlite',
    schema: '',
    taskText: 'Создайте таблицу demo_dates с полями: is_active INTEGER (0 или 1), created_at TEXT (дата в формате YYYY-MM-DD). Вставьте запись. Выведите, отфильтровав только активные записи.',
    hint: 'SQLite не имеет native BOOLEAN — используйте INTEGER 0/1. Даты хранятся как TEXT в формате ISO или как Julian Day Number.',
    sampleSolution: "CREATE TABLE demo_dates (is_active INTEGER, created_at TEXT); INSERT INTO demo_dates VALUES (1, '2024-01-15'), (0, '2024-02-20'); SELECT * FROM demo_dates WHERE is_active = 1;",
    verificationQuery: 'SELECT COUNT(*) as count FROM demo_dates WHERE is_active = 1;',
  },

  {
    id: 'advanced-explain-1',
    title: 'Чтение плана выполнения (EXPLAIN)',
    description: 'Как понять, как СУБД выполняет запрос',
    difficulty: 'advanced',
    dbType: 'sqlite',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Выполните EXPLAIN QUERY PLAN для запроса SELECT * FROM employees WHERE department_id = 1. Изучите вывод: SCAN TABLE означает полный просмотр, SEARCH — использование индекса. Какой тип используется?',
    hint: 'EXPLAIN QUERY PLAN показывает стратегию выполнения. SCAN TABLE = медленный полный просмотр всех строк. SEARCH USING INDEX = быстрый поиск по индексу.',
    sampleSolution: 'EXPLAIN QUERY PLAN SELECT * FROM employees WHERE department_id = 1;',
    verificationQuery: 'SELECT COUNT(*) as count FROM employees;',
  },

  {
    id: 'advanced-explain-2',
    title: 'Влияние индекса на план выполнения',
    description: 'Сравнение EXPLAIN до и после создания индекса',
    difficulty: 'advanced',
    dbType: 'sqlite',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Сначала выполните EXPLAIN QUERY PLAN для SELECT * FROM employees WHERE department_id = 1. Затем создайте индекс CREATE INDEX idx_dept ON employees(department_id). Снова выполните EXPLAIN — план должен измениться с SCAN на SEARCH.',
    hint: 'Без индекса: SCAN TABLE (перебор всех строк). С индексом: SEARCH USING INDEX (быстрый поиск). Разница особенно заметна на больших таблицах.',
    sampleSolution: 'EXPLAIN QUERY PLAN SELECT * FROM employees WHERE department_id = 1; CREATE INDEX idx_dept ON employees(department_id); EXPLAIN QUERY PLAN SELECT * FROM employees WHERE department_id = 1;',
    verificationQuery: "SELECT COUNT(*) as count FROM sqlite_master WHERE type='index' AND name='idx_dept';",
  },


  // ==================== ANALYTICS TASKS (ClickHouse) ====================
  {
    id: 'analytics-a1',
    title: 'countIf и sumIf — условные агрегаты',
    description: 'ClickHouse-функции countIf() и sumIf()',
    difficulty: 'advanced',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Для каждого устройства посчитайте количество кликов (countIf), количество просмотров (countIf) и суммарную длительность просмотров (sumIf).',
    hint: "countIf(event_type = 'click') считает только клики. sumIf(duration, event_type = 'page_view') суммирует длительность только для просмотров.",
    sampleSolution: "SELECT device, countIf(event_type = 'click') as clicks, countIf(event_type = 'page_view') as views, sumIf(duration, event_type = 'page_view') as total_duration FROM events GROUP BY device ORDER BY clicks DESC;",
    verificationQuery: 'SELECT COUNT(DISTINCT device) as count FROM events;',
  },

  {
    id: 'analytics-a2',
    title: 'sumIf для завершённых покупок',
    description: 'JOIN + sumIf для фильтрации по статусу',
    difficulty: 'advanced',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Для каждого пользователя выведите: общее количество покупок, сумму только завершённых покупок (sumIf) и средний чек. Используйте LEFT JOIN purchases.',
    hint: "sumIf(p.amount, p.status = 'completed') считает сумму только для завершённых покупок.",
    sampleSolution: "SELECT u.username, count(p.purchase_id) as total_purchases, sumIf(p.amount, p.status = 'completed') as completed_amount, avg(p.amount) as avg_check FROM users u LEFT JOIN purchases p ON u.user_id = p.user_id GROUP BY u.user_id, u.username ORDER BY completed_amount DESC;",
    verificationQuery: 'SELECT COUNT(*) as count FROM users;',
  },

  {
    id: 'analytics-a3',
    title: 'groupArray — массивы в ClickHouse',
    description: 'ClickHouse-функция groupArray()',
    difficulty: 'advanced',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Для каждого пользователя соберите массив уникальных страниц, которые он посещал (только page_view). Используйте groupArray().',
    hint: 'groupArray(DISTINCT page) создаёт массив уникальных страниц для каждого user_id.',
    sampleSolution: "SELECT user_id, groupArray(DISTINCT page) as visited_pages, count(*) as view_count FROM events WHERE event_type = 'page_view' GROUP BY user_id ORDER BY view_count DESC;",
    verificationQuery: "SELECT COUNT(DISTINCT user_id) as count FROM events WHERE event_type = 'page_view';",
  },

  {
    id: 'analytics-a4',
    title: 'Оконная функция ROW_NUMBER',
    description: 'ROW_NUMBER() OVER для ранжирования',
    difficulty: 'advanced',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Пронумеруйте покупки каждого пользователя по дате (от новых к старым). Выведите username, product_id, amount, purchase_date и номер строки.',
    hint: 'ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY purchase_date DESC) нумерует покупки внутри каждого пользователя.',
    sampleSolution: 'SELECT u.username, p.product_id, p.amount, p.purchase_date, ROW_NUMBER() OVER (PARTITION BY p.user_id ORDER BY p.purchase_date DESC) as rn FROM purchases p JOIN users u ON p.user_id = u.user_id ORDER BY u.user_id, rn;',
    verificationQuery: 'SELECT COUNT(*) as count FROM purchases;',
  },

  {
    id: 'analytics-a5',
    title: 'CTE + ClickHouse-функции',
    description: 'WITH (CTE) + countIf для комплексного анализа',
    difficulty: 'advanced',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Используя CTE (WITH), найдите пользователей с более чем одним кликом. Выведите их имена и количество кликов. Используйте countIf().',
    hint: "Сначала создайте CTE с кликами на пользователя, затем отфильтруйте WHERE click_count > 1.",
    sampleSolution: "WITH user_clicks AS (SELECT user_id, countIf(event_type = 'click') as click_count FROM events GROUP BY user_id) SELECT u.username, uc.click_count FROM user_clicks uc JOIN users u ON uc.user_id = u.user_id WHERE uc.click_count > 1 ORDER BY uc.click_count DESC;",
    verificationQuery: "SELECT COUNT(*) as count FROM (SELECT user_id FROM events WHERE event_type = 'click' GROUP BY user_id HAVING count(*) > 1);",
  },

  {
    id: 'ch-42',
    title: 'ClickHouse: sumIf + toStartOfDay',
    description: 'Ежедневная аналитика просмотров страниц',
    difficulty: 'advanced',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: CLICKHOUSE_EVENTS_SCHEMA,
    taskText: 'Для каждого дня вычислите общую длительность page_view событий и количество кликов. Используйте toStartOfDay(event_time) для группировки по дням, sumIf(duration, event_type = \'page_view\') для суммы длительности и countIf(event_type = \'click\') для подсчёта кликов. Выведите day, total_view_duration, click_count. Отсортируйте по day.',
    hint: 'toStartOfDay(datetime) округляет до начала дня. sumIf() и countIf() — условные агрегатные функции ClickHouse.',
    sampleSolution: "SELECT toStartOfDay(event_time) AS day, sumIf(duration, event_type = 'page_view') AS total_view_duration, countIf(event_type = 'click') AS click_count FROM events GROUP BY day ORDER BY day;",
    verificationQuery: 'SELECT COUNT(*) as count FROM events;',
  },

  {
    id: 'ch-45',
    title: 'ClickHouse: условная агрегация countIf',
    description: 'Отношение кликов к просмотрам (CTR) по дням',
    difficulty: 'advanced',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: CLICKHOUSE_EVENTS_SCHEMA,
    taskText: 'Для каждого дня вычислите CTR (Click-Through Rate) — отношение количества кликов к количеству просмотров. Используйте countIf для подсчёта каждого типа. Выведите event_date, page_views, clicks и ctr (округлите до 3 знаков). Избегайте деления на ноль через NULLIF. Отсортируйте по event_date.',
    hint: 'CTR = clicks / page_views. NULLIF(page_views, 0) предотвращает деление на ноль, возвращая NULL. ROUND(..., 3) округляет до 3 знаков.',
    sampleSolution: "SELECT toDate(event_time) AS event_date, countIf(event_type = 'page_view') AS page_views, countIf(event_type = 'click') AS clicks, ROUND(countIf(event_type = 'click') / NULLIF(countIf(event_type = 'page_view'), 0), 3) AS ctr FROM events GROUP BY event_date ORDER BY event_date;",
    verificationQuery: 'SELECT COUNT(*) as count FROM events;',
  },

  {
    id: 'ch-advanced-1',
    title: 'Вложенные подзапросы',
    description: 'Подзапросы с агрегацией',
    difficulty: 'advanced',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Найдите пользователей, которые потратили больше средней суммы покупок. Выведите имя пользователя и общую сумму.',
    hint: 'Подзапрос: SELECT avg(total) FROM (SELECT user_id, sum(amount) as total FROM purchases WHERE status = \'completed\' GROUP BY user_id).',
    sampleSolution: "SELECT u.username, sum(p.amount) as total_spent FROM users u JOIN purchases p ON u.user_id = p.user_id WHERE p.status = 'completed' GROUP BY u.user_id, u.username HAVING sum(p.amount) > (SELECT avg(total) FROM (SELECT user_id, sum(amount) as total FROM purchases WHERE status = 'completed' GROUP BY user_id)) ORDER BY total_spent DESC;",
    verificationQuery: "SELECT COUNT(*) as count FROM (SELECT user_id, sum(amount) as total FROM purchases WHERE status = 'completed' GROUP BY user_id HAVING total > (SELECT avg(total) FROM (SELECT user_id, sum(amount) as total FROM purchases WHERE status = 'completed' GROUP BY user_id)));",
  },

  {
    id: 'ch-advanced-2',
    title: 'uniqExact и toYYYYMM',
    description: 'Уникальные значения и форматирование дат',
    difficulty: 'advanced',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Для каждого месяца посчитайте количество уникальных пользователей, совершивших покупки. Используйте uniqExact и toYYYYMM.',
    hint: 'uniqExact(user_id) считает уникальные значения. toYYYYMM(purchase_date) форматирует дату.',
    sampleSolution: "SELECT toYYYYMM(purchase_date) as month, uniqExact(user_id) as unique_buyers, count(*) as total_purchases, sum(amount) as revenue FROM purchases WHERE status = 'completed' GROUP BY month ORDER BY month;",
    verificationQuery: "SELECT COUNT(DISTINCT toYYYYMM(purchase_date)) as months FROM purchases WHERE status = 'completed';",
  },

  {
    id: 'ch-advanced-3',
    title: 'if и условные выражения',
    description: 'Функция if в SELECT',
    difficulty: 'advanced',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Для каждого устройства посчитайте количество кликов и просмотров, а также конверсию (клики / просмотры * 100). Используйте if.',
    hint: 'if(event_type = \'click\', 1, 0) вернёт 1 для кликов и 0 для остальных.',
    sampleSolution: "SELECT device, sum(if(event_type = 'click', 1, 0)) as clicks, sum(if(event_type = 'page_view', 1, 0)) as views, round(sum(if(event_type = 'click', 1, 0)) * 100.0 / sum(if(event_type = 'page_view', 1, 0)), 2) as ctr FROM events GROUP BY device ORDER BY ctr DESC;",
    verificationQuery: 'SELECT COUNT(DISTINCT device) as devices FROM events;',
  },

  {
    id: 'ch-analytics-adv-1',
    title: 'ClickHouse: Воронка конверсии по страницам',
    description: 'Анализ воронки событий: от просмотра курсов до покупки',
    difficulty: 'advanced',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: SHOP_SCHEMA,
    taskText: 'Создайте воронку конверсии для таблицы orders. Посчитайте количество заказов для каждого статуса (new, processing, shipped, delivered, cancelled) в порядке жизненного цикла. Используйте countIf для каждого статуса в одном запросе.',
    hint: 'countIf(cond) считает строки, удовлетворяющие условию. Используйте один SELECT с несколькими countIf для каждого статуса.',
    sampleSolution: "SELECT countIf(status = 'new') AS new_orders, countIf(status = 'processing') AS processing_orders, countIf(status = 'shipped') AS shipped_orders, countIf(status = 'delivered') AS delivered_orders, countIf(status = 'cancelled') AS cancelled_orders FROM orders;",
    verificationQuery: "SELECT count(*) as count FROM orders WHERE status = 'delivered';",
  },

  {
    id: 'ch-analytics-adv-2',
    title: 'ClickHouse: Выручка с применением multiIf',
    description: 'Классификация заказов по сумме с помощью multiIf',
    difficulty: 'advanced',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: SHOP_SCHEMA,
    taskText: 'Для каждого заказа из таблицы orders создайте категорию на основе total_amount: "Мелкий" (< 5000), "Средний" (5000-10000), "Крупный" (10001-50000), "Премиум" (> 50000). Выведите id заказа, total_amount и категорию. Используйте multiIf.',
    hint: 'multiIf(cond1, val1, cond2, val2, ..., elseVal) работает как цепочка CASE WHEN. Порядок условий важен — от самого специфичного к общему.',
    sampleSolution: "SELECT id, total_amount, multiIf(total_amount < 5000, 'Мелкий', total_amount <= 10000, 'Средний', total_amount <= 50000, 'Крупный', 'Премиум') AS order_category FROM orders ORDER BY total_amount DESC;",
    verificationQuery: "SELECT COUNT(*) as count FROM orders WHERE total_amount > 50000;",
  },

  {
    id: 'ch-analytics-adv-3',
    title: 'ClickHouse: Топ-N с bar-визуализацией',
    description: 'Текстовая визуализация данных с помощью bar()',
    difficulty: 'advanced',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: SHOP_SCHEMA,
    taskText: 'Выведите топ-5 товаров по цене из таблицы products. Для каждого товара покажите name, price и визуальную шкалу с помощью bar(price, 70000, 20). Отсортируйте по цене DESC, ограничьте 5.',
    hint: 'bar(value, max_value, width) создаёт текстовую шкалу из символов █. max_value — это значение, соответствующее полной шкале.',
    sampleSolution: 'SELECT name, price, bar(price, 70000, 20) AS price_bar FROM products ORDER BY price DESC LIMIT 5;',
    verificationQuery: 'SELECT COUNT(*) as count FROM products WHERE price > 10000;',
  },

  {
    id: 'ch-analytics-adv-4',
    title: 'ClickHouse: Агрегация по неделям',
    description: 'Группировка данных по неделям',
    difficulty: 'advanced',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: SHOP_SCHEMA,
    taskText: 'Из таблицы orders посчитайте количество заказов и сумму total_amount для каждого месяца. Используйте toStartOfMonth(order_date) для группировки. Выведите месяц, кол-во заказов и суммарную выручку. Отсортируйте по месяцу.',
    hint: 'toStartOfMonth(date) округляет дату до начала месяца. Используйте SUM и COUNT вместе с GROUP BY.',
    sampleSolution: 'SELECT toStartOfMonth(order_date) AS month, COUNT(*) AS order_count, SUM(total_amount) AS revenue FROM orders GROUP BY month ORDER BY month;',
    verificationQuery: 'SELECT COUNT(DISTINCT SUBSTR(order_date, 1, 7)) as count FROM orders;',
  },

  {
    id: 'pg-15',
    title: 'ARRAY_AGG и ORDER BY внутри агрегации',
    description: 'Collect values into arrays with ordering',
    difficulty: 'advanced',
    dbType: 'postgresql',
    category: 'analytics',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Для каждого отдела соберите имена сотрудников в массив (ARRAY_AGG). Внутри ARRAY_AGG отсортируйте имена по алфавиту. Выведите name отдела и team_members.',
    hint: 'ARRAY_AGG collects values into a PostgreSQL array.',
    sampleSolution: "SELECT d.name, ARRAY_AGG(e.first_name ORDER BY e.first_name) as team_members FROM departments d JOIN employees e ON d.id = e.department_id GROUP BY d.name;",
    verificationQuery: 'SELECT COUNT(*) as count FROM departments;',
  },

  {
    id: 'pg-16',
    title: 'RETURNING — возврат данных при INSERT',
    description: 'Return inserted data with RETURNING clause',
    difficulty: 'advanced',
    dbType: 'postgresql',
    category: 'analytics',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Вставьте нового сотрудника: first_name = \'Тест\', last_name = \'Тестов\', email = \'test@company.ru\', department_id = 1, salary = 100000. Используйте RETURNING *, чтобы вернуть все столбцы вставленной записи.',
    hint: 'RETURNING returns data from modified rows after INSERT/UPDATE/DELETE.',
    sampleSolution: "INSERT INTO employees (first_name, last_name, email, department_id, salary) VALUES ('Тест', 'Тестов', 'test@company.ru', 1, 100000) RETURNING *;",
    verificationQuery: "SELECT COUNT(*) as count FROM employees WHERE email = 'test@company.ru';",
  },

  {
    id: 'pg-26',
    title: 'PostgreSQL: GENERATE_SERIES',
    description: 'Генерация числового ряда с GENERATE_SERIES',
    difficulty: 'advanced',
    dbType: 'postgresql',
    category: 'analytics',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Для каждого года с 2019 по 2022 включительно выведите количество нанятых сотрудников. Используйте GENERATE_SERIES(2019, 2022) как таблицу и LEFT JOIN с сотрудниками, извлекая год из hire_date через EXTRACT. Выведите hire_year и hired_count. Отсортируйте по hire_year.',
    hint: 'GENERATE_SERIES(start, end) создаёт виртуальную таблицу с рядом чисел. Используйте LEFT JOIN, чтобы сохранить все годы, даже если в некоторые никто не нанимался.',
    sampleSolution: "SELECT gs.year AS hire_year, COUNT(e.id) AS hired_count FROM GENERATE_SERIES(2019, 2022) AS gs(year) LEFT JOIN employees e ON EXTRACT(YEAR FROM e.hire_date) = gs.year GROUP BY gs.year ORDER BY gs.year;",
    verificationQuery: "SELECT COUNT(DISTINCT STRFTIME('%Y', hire_date)) AS count FROM employees;",
  },

  {
    id: 'pg-33',
    title: 'PostgreSQL: рекурсивный CTE (WITH RECURSIVE)',
    description: 'Иерархический запрос с рекурсивным CTE',
    difficulty: 'advanced',
    dbType: 'postgresql',
    category: 'analytics',
    schema: SHOP_SCHEMA,
    taskText: 'Используя рекурсивный CTE (WITH RECURSIVE), получите иерархию всех категорий товаров. Начните с корневых категорий (parent_id IS NULL), затем рекурсивно присоединяйте подкатегории (parent_id = id родителя). Выведите id, name, parent_id и level (уровень вложенности). Отсортируйте по level, затем по id.',
    hint: 'WITH RECURSIVE cte AS (базовый запрос UNION ALL рекурсивный запрос) — базовая часть выбирает корневые элементы, рекурсивная — их потомков.',
    sampleSolution: "WITH RECURSIVE category_tree AS (SELECT id, name, parent_id, 0 AS level FROM categories WHERE parent_id IS NULL UNION ALL SELECT c.id, c.name, c.parent_id, ct.level + 1 FROM categories c JOIN category_tree ct ON c.parent_id = ct.id) SELECT id, name, parent_id, level FROM category_tree ORDER BY level, id;",
    verificationQuery: 'SELECT COUNT(*) as count FROM categories;',
  },


  // ==================== EXAM TASKS ====================
  {
    id: 'ch-exam-7',
    title: 'Экзамен ClickHouse: countIf + avgIf для отзывов',
    description: 'Анализ отзывов по категориям товаров',
    difficulty: 'advanced',
    dbType: 'clickhouse',
    category: 'exam',
    examGroup: 'ch-exam-advanced',
    schema: SHOP_SCHEMA,
    taskText: 'Для каждой категории товаров вычислите: количество хороших отзывов (рейтинг >= 4) через countIf, средний рейтинг через avgIf. Объедините reviews с products по product_id, затем с categories. Выведите category, good_reviews и avg_rating (округлите до 2). Отсортируйте по avg_rating DESC.',
    hint: 'countIf(condition) считает строки по условию. avgIf(expr, condition) считает среднее по условию. Условия могут ссылаться на разные столбцы.',
    sampleSolution: "SELECT c.name AS category, countIf(r.rating >= 4) AS good_reviews, ROUND(avgIf(r.rating, r.rating > 0), 2) AS avg_rating FROM categories c JOIN products p ON c.id = p.category_id JOIN reviews r ON p.id = r.product_id GROUP BY c.name ORDER BY avg_rating DESC;",
    verificationQuery: 'SELECT COUNT(*) as count FROM categories WHERE (SELECT COUNT(*) FROM products p JOIN reviews r ON p.id = r.product_id WHERE p.category_id = categories.id) > 0;',
  },

  {
    id: 'ch-exam-8',
    title: 'Экзамен ClickHouse: toStartOfDay + countIf',
    description: 'Ежедневный анализ заказов',
    difficulty: 'advanced',
    dbType: 'clickhouse',
    category: 'exam',
    examGroup: 'ch-exam-advanced',
    schema: SHOP_SCHEMA,
    taskText: 'Для каждого дня проанализируйте заказы: количество доставленных (countIf(status = \'delivered\')), отменённых (countIf(status = \'cancelled\')) и новых (countIf(status = \'new\')). Используйте toStartOfDay(toDateTime(order_date)) для группировки. Выведите order_day, delivered, cancelled и new_orders. Отсортируйте по order_day.',
    hint: 'toStartOfDay(datetime) округляет до начала дня. countIf(condition) считает строки, удовлетворяющие условию, внутри группы.',
    sampleSolution: "SELECT toStartOfDay(toDateTime(order_date)) AS order_day, countIf(status = 'delivered') AS delivered, countIf(status = 'cancelled') AS cancelled, countIf(status = 'new') AS new_orders FROM orders GROUP BY order_day ORDER BY order_day;",
    verificationQuery: 'SELECT COUNT(*) as count FROM orders;',
  },

  {
    id: 'ch-exam-9',
    title: 'Экзамен ClickHouse: uniqExact + groupUniqArray',
    description: 'Уникальные клиенты по городам доставки',
    difficulty: 'advanced',
    dbType: 'clickhouse',
    category: 'exam',
    examGroup: 'ch-exam-advanced',
    schema: SHOP_SCHEMA,
    taskText: 'Для каждого города доставки выведите: количество уникальных клиентов (uniqExact(customer_id)), массив уникальных id клиентов (groupUniqArray(customer_id)) и общее количество заказов. Используйте таблицу orders. Отсортируйте по unique_customers DESC.',
    hint: 'uniqExact(expr) считает точное количество уникальных значений (используя хеш-таблицу). groupUniqArray(expr) собирает уникальные значения в массив.',
    sampleSolution: 'SELECT shipping_city, uniqExact(customer_id) AS unique_customers, groupUniqArray(customer_id) AS customer_list, COUNT(*) AS total_orders FROM orders GROUP BY shipping_city ORDER BY unique_customers DESC;',
    verificationQuery: 'SELECT COUNT(DISTINCT shipping_city) as count FROM orders;',
  },

  {
    id: 'exam-a1',
    title: 'Экзамен: Оконные функции',
    description: 'Проверочная работа — ROW_NUMBER, RANK, LEAD',
    difficulty: 'advanced',
    dbType: 'sqlite',
    category: 'exam',
    examGroup: 'exam-advanced',
    schema: SHOP_SCHEMA,
    taskText: 'Присвойте каждому заказу ранг по сумме (total_amount) внутри каждого города доставки. Выведите: shipping_city, order_date, total_amount, rank. Топ-3 по каждому городу.',
    hint: 'ROW_NUMBER() OVER (PARTITION BY shipping_city ORDER BY total_amount DESC) и отфильтруйте rank <= 3.',
    sampleSolution: 'WITH ranked AS (SELECT shipping_city, order_date, total_amount, ROW_NUMBER() OVER (PARTITION BY shipping_city ORDER BY total_amount DESC) as rank FROM orders WHERE total_amount IS NOT NULL) SELECT * FROM ranked WHERE rank <= 3 ORDER BY shipping_city, rank;',
    verificationQuery: 'SELECT COUNT(*) as count FROM (SELECT shipping_city, ROW_NUMBER() OVER (PARTITION BY shipping_city ORDER BY total_amount DESC) as rn FROM orders WHERE total_amount IS NOT NULL) WHERE rn <= 3;',
  },

  {
    id: 'exam-a2',
    title: 'Экзамен: Множественные CTE',
    description: 'Проверочная работа — CTE + JOIN + агрегация',
    difficulty: 'advanced',
    dbType: 'sqlite',
    category: 'exam',
    examGroup: 'exam-advanced',
    schema: SHOP_SCHEMA,
    taskText: 'Создайте отчёт: для каждого клиента — общая сумма покупок, количество товаров (штук), уникальных заказов. Только VIP-клиенты (is_vip = 1).',
    hint: 'CTE: customer_id, SUM(oi.quantity * oi.unit_price), COUNT(DISTINCT oi.order_id). JOIN с customers WHERE is_vip = 1.',
    sampleSolution: "WITH customer_stats AS (SELECT o.customer_id, SUM(o.total_amount) as total_spent, COUNT(o.id) as order_count FROM orders o GROUP BY o.customer_id) SELECT c.first_name, c.last_name, cs.total_spent, cs.order_count FROM customers c JOIN customer_stats cs ON c.id = cs.customer_id WHERE c.is_vip = 1 ORDER BY cs.total_spent DESC;",
    verificationQuery: "SELECT COUNT(*) as count FROM customers c JOIN (SELECT customer_id FROM orders GROUP BY customer_id) o ON c.id = o.customer_id WHERE c.is_vip = 1;",
  },

  {
    id: 'exam-a3',
    title: 'Экзамен: Рекурсивный CTE на практике',
    description: 'Проверочная работа — рекурсия с бизнес-логикой',
    difficulty: 'advanced',
    dbType: 'sqlite',
    category: 'exam',
    examGroup: 'exam-advanced',
    schema: SHOP_SCHEMA,
    taskText: 'Используя рекурсивный CTE, вычислите накопительную сумму заказов для каждого клиента по порядку дат: каждая строка должна содержать дату, сумму заказа и нарастающий итог (running_total). Для клиента id=1.',
    hint: 'Базовый случай: первый заказ клиента. Рекурсия: добавляем total_amount к running_total. ORDER BY order_date.',
    sampleSolution: "WITH RECURSIVE order_seq AS (SELECT o.id, o.order_date, o.total_amount, o.total_amount as running_total, ROW_NUMBER() OVER (ORDER BY o.order_date) as rn FROM orders o WHERE o.customer_id = 1 ORDER BY o.order_date), running AS (SELECT id, order_date, total_amount, running_total, rn FROM order_seq WHERE rn = 1 UNION ALL SELECT os.id, os.order_date, os.total_amount, r.running_total + os.total_amount, os.rn FROM order_seq os JOIN running r ON os.rn = r.rn + 1) SELECT order_date, total_amount, running_total FROM running ORDER BY order_date;",
    verificationQuery: 'SELECT 6 as expected_count;',
  },

  {
    id: 'exam-a4',
    title: 'Экзамен: Полный аналитический отчёт',
    description: 'Проверочная работа — сложный запрос на все знания',
    difficulty: 'advanced',
    dbType: 'sqlite',
    category: 'exam',
    examGroup: 'exam-advanced',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Создайте отчёт по отделам: название, количество активных/неактивных, средняя зарплата активных, бюджет отдела, отношение бюджета к сумме зарплат (в %). Только отделы с 3+ сотрудниками.',
    hint: 'CTE для подсчёта active/inactive, затем JOIN с departments. HAVING COUNT(*) >= 3. ROUND для процентов.',
    sampleSolution: "WITH dept_emp AS (SELECT department_id, SUM(CASE WHEN is_active = 1 THEN 1 ELSE 0 END) as active_count, SUM(CASE WHEN is_active = 0 THEN 1 ELSE 0 END) as inactive_count, AVG(CASE WHEN is_active = 1 THEN salary END) as active_avg_salary, SUM(salary) as total_salary FROM employees GROUP BY department_id HAVING COUNT(*) >= 3) SELECT d.name, de.active_count, de.inactive_count, ROUND(de.active_avg_salary) as active_avg_salary, d.budget, ROUND(CAST(d.budget AS REAL) / de.total_salary * 100, 1) as budget_ratio_pct FROM departments d JOIN dept_emp de ON d.id = de.department_id ORDER BY budget_ratio_pct DESC;",
    verificationQuery: "SELECT COUNT(*) as count FROM (SELECT department_id FROM employees GROUP BY department_id HAVING COUNT(*) >= 3);",
  },

  {
    id: 'exam-a5',
    title: 'Экзамен: Комплексная бизнес-задача',
    description: 'Проверочная работа — реальный сценарий',
    difficulty: 'advanced',
    dbType: 'sqlite',
    category: 'exam',
    examGroup: 'exam-advanced',
    schema: SHOP_SCHEMA,
    taskText: 'Найдите "растущих" клиентов: тех, чей последний заказ по сумме больше предыдущего. Выведите: first_name, last_name, сумму предпоследнего и последнего заказа, разницу.',
    hint: 'CTE с LAG(total_amount) OVER (PARTITION BY customer_id ORDER BY order_date). WHERE last_amount > prev_amount.',
    sampleSolution: "WITH order_with_prev AS (SELECT o.customer_id, o.order_date, o.total_amount, LAG(o.total_amount) OVER (PARTITION BY o.customer_id ORDER BY o.order_date) as prev_amount, ROW_NUMBER() OVER (PARTITION BY o.customer_id ORDER BY o.order_date DESC) as rn FROM orders o) SELECT c.first_name, c.last_name, op.prev_amount as prev_order, op.total_amount as last_order, op.total_amount - op.prev_amount as diff FROM order_with_prev op JOIN customers c ON op.customer_id = c.id WHERE op.rn = 1 AND op.prev_amount IS NOT NULL AND op.total_amount > op.prev_amount ORDER BY diff DESC;",
    verificationQuery: "SELECT COUNT(*) as count FROM (SELECT o.customer_id, LAG(o.total_amount) OVER (PARTITION BY o.customer_id ORDER BY o.order_date) as prev_amount, ROW_NUMBER() OVER (PARTITION BY o.customer_id ORDER BY o.order_date DESC) as rn FROM orders o) WHERE rn = 1 AND prev_amount IS NOT NULL AND total_amount > prev_amount;",
  },

  {
    id: 'pg-exam-7',
    title: 'Экзамен PostgreSQL: DISTINCT ON',
    description: 'Последний отзыв для каждого товара',
    difficulty: 'advanced',
    dbType: 'postgresql',
    category: 'exam',
    examGroup: 'pg-exam-advanced',
    schema: SHOP_SCHEMA,
    taskText: 'Получите самый последний отзыв для каждого товара. Используйте DISTINCT ON (product_id) с ORDER BY product_id, review_date DESC. Выведите product_id, customer_id, rating, comment и review_date.',
    hint: 'DISTINCT ON (expr) возвращает первую строку для каждого уникального значения выражения. Порядок определяется ORDER BY — выражение DISTINCT ON должно быть первым в ORDER BY.',
    sampleSolution: 'SELECT DISTINCT ON (product_id) product_id, customer_id, rating, comment, review_date FROM reviews ORDER BY product_id, review_date DESC;',
    verificationQuery: 'SELECT COUNT(DISTINCT product_id) as count FROM reviews;',
  },

  {
    id: 'pg-exam-8',
    title: 'Экзамен PostgreSQL: RETURNING',
    description: 'Вставка с возвратом результата',
    difficulty: 'advanced',
    dbType: 'postgresql',
    category: 'exam',
    examGroup: 'pg-exam-advanced',
    schema: SHOP_SCHEMA,
    taskText: 'Вставьте новую категорию: name = \'Игрушки\', description = \'Детские игрушки и игры\'. Используйте RETURNING *, чтобы вернуть вставленную строку целиком.',
    hint: 'RETURNING возвращает данные изменённой строки (INSERT, UPDATE, DELETE). RETURNING * возвращает все столбцы. Можно указать конкретные: RETURNING id, name.',
    sampleSolution: "INSERT INTO categories (name, description) VALUES ('Игрушки', 'Детские игрушки и игры') RETURNING *;",
    verificationQuery: 'SELECT COUNT(*) as count FROM categories;',
  },

  {
    id: 'pg-exam-9',
    title: 'Экзамен PostgreSQL: LATERAL JOIN',
    description: 'Товар-лидер в каждой категории',
    difficulty: 'advanced',
    dbType: 'postgresql',
    category: 'exam',
    examGroup: 'pg-exam-advanced',
    schema: SHOP_SCHEMA,
    taskText: 'Для каждой категории найдите товар с наибольшим общим количеством заказов. Используйте CROSS JOIN LATERAL: подзапрос должен ссылаться на categories.id. В подзапросе объедините products с order_items, сгруппируйте по product_id, просуммируйте quantity и возьмите LIMIT 1. Выведите category, product_name и total_ordered.',
    hint: 'LATERAL позволяет подзапросу в FROM ссылаться на столбцы предыдущих таблиц в FROM. CROSS JOIN LATERAL — каждый внешний ряд комбинируется с результатом подзапроса.',
    sampleSolution: "SELECT c.name AS category, top.product_name, top.total_ordered FROM categories c CROSS JOIN LATERAL (SELECT p.name AS product_name, COALESCE(SUM(oi.quantity), 0) AS total_ordered FROM products p LEFT JOIN order_items oi ON p.id = oi.product_id WHERE p.category_id = c.id GROUP BY p.id, p.name ORDER BY total_ordered DESC LIMIT 1) top ORDER BY c.name;",
    verificationQuery: 'SELECT COUNT(*) as count FROM categories WHERE (SELECT COUNT(*) FROM products WHERE category_id = categories.id) > 0;',
  },

];
