/**
 * Beginner Task Definitions
 * Auto-generated from training-tasks.ts
 */

import type { TrainingTask } from './types';
import { ANALYTICS_SCHEMA, CLICKHOUSE_EVENTS_SCHEMA, EMPLOYEES_SCHEMA, SHOP_SCHEMA } from './schemas';

export const BEGINNER_TASKS: TrainingTask[] = [

  // ==================== BEGINNER TASKS ====================
  {
    id: 'beginner-1',
    title: 'Базовый SELECT',
    description: 'Выбрать все столбцы из таблицы',
    difficulty: 'beginner',
    dbType: 'sqlite',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Выведите все данные из таблицы departments (все столбцы, все строки).',
    hint: 'Звёздочка (*) после SELECT означает "все столбцы". Это удобно для быстрого просмотра таблицы, но в реальных проектах лучше перечислять нужные столбцы явно.',
    progressiveHints: [
      {
        level: 1,
        text: 'Вам нужно выбрать все данные из таблицы departments',
        xpPenalty: 0,
      },
      {
        level: 2,
        text: 'Используйте оператор SELECT для выбора данных',
        xpPenalty: 0,
      },
      {
        level: 3,
        text: 'Звёздочка (*) после SELECT означает "все столбцы". Это удобно для быстрого просмотра таблицы, но в реальных проектах лучше перечислять нужные столбцы явно.',
        xpPenalty: 0,
      },
    ],
    sampleSolution: 'SELECT * FROM departments;',
    verificationQuery: 'SELECT COUNT(*) as count FROM departments;',
  },

  {
    id: 'beginner-2',
    title: 'Выбор столбцов',
    description: 'Выбрать конкретные столбцы из таблицы',
    difficulty: 'beginner',
    dbType: 'sqlite',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Выведите имена (first_name) и фамилии (last_name) всех сотрудников из таблицы employees.',
    hint: 'Перечислите нужные столбцы через запятую после SELECT.',
    progressiveHints: [
      {
        level: 1,
        text: 'Вам нужно выбрать конкретные столбцы из таблицы employees',
        xpPenalty: 0,
      },
      {
        level: 2,
        text: 'Используйте SELECT с перечислением столбцов через запятую',
        xpPenalty: 0,
      },
      {
        level: 3,
        text: 'Перечислите нужные столбцы через запятую после SELECT.',
        xpPenalty: 0,
      },
    ],
    sampleSolution: 'SELECT first_name, last_name FROM employees;',
    verificationQuery: 'SELECT COUNT(*) as count FROM employees;',
  },

  {
    id: 'beginner-3',
    title: 'Фильтрация WHERE',
    description: 'Отфильтровать строки с помощью WHERE',
    difficulty: 'beginner',
    dbType: 'sqlite',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Найдите всех сотрудников с зарплатой больше 130000. Выведите их first_name, last_name и salary.',
    hint: 'WHERE фильтрует строки ДО вывода результата — в результат попадут только те, где условие истинно. Операторы сравнения: =, !=, <, >, <=, >=.',
    progressiveHints: [
      {
        level: 1,
        text: 'Вам нужно отфильтровать сотрудников по условию зарплаты',
        xpPenalty: 0,
      },
      {
        level: 2,
        text: 'Используйте WHERE с оператором > для фильтрации по зарплате',
        xpPenalty: 0,
      },
      {
        level: 3,
        text: 'WHERE фильтрует строки ДО вывода результата — в результат попадут только те, где условие истинно. Операторы сравнения: =, !=, <, >, <=, >=.',
        xpPenalty: 0,
      },
    ],
    sampleSolution: 'SELECT first_name, last_name, salary FROM employees WHERE salary > 130000;',
    verificationQuery: 'SELECT COUNT(*) as count FROM employees WHERE salary > 130000;',
  },

  {
    id: 'beginner-4',
    title: 'Сортировка ORDER BY',
    description: 'Отсортировать результаты по столбцу',
    difficulty: 'beginner',
    dbType: 'sqlite',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Выведите список сотрудников (first_name, last_name, salary), отсортированный по зарплате по убыванию.',
    hint: 'Используйте ORDER BY с DESC для сортировки по убыванию.',
    progressiveHints: [
      {
        level: 1,
        text: 'Вам нужно отсортировать результаты запроса по определённому столбцу',
        xpPenalty: 0,
      },
      {
        level: 2,
        text: 'Используйте ORDER BY для сортировки и DESC для убывания',
        xpPenalty: 0,
      },
      {
        level: 3,
        text: 'Используйте ORDER BY с DESC для сортировки по убыванию.',
        xpPenalty: 0,
      },
    ],
    sampleSolution: 'SELECT first_name, last_name, salary FROM employees ORDER BY salary DESC;',
    verificationQuery: 'SELECT MAX(salary) as max_salary FROM employees;',
  },

  {
    id: 'beginner-5',
    title: 'Ограничение результатов LIMIT',
    description: 'Ограничить количество выводимых строк',
    difficulty: 'beginner',
    dbType: 'sqlite',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Выведите 5 самых высокооплачиваемых сотрудников (first_name, last_name, salary).',
    hint: 'Комбинируйте ORDER BY для сортировки и LIMIT для ограничения.',
    progressiveHints: [
      {
        level: 1,
        text: 'Вам нужно найти топ сотрудников по зарплате и ограничить количество строк',
        xpPenalty: 0,
      },
      {
        level: 2,
        text: 'Отсортируйте по зарплате по убыванию и используйте LIMIT 5',
        xpPenalty: 0,
      },
      {
        level: 3,
        text: 'Комбинируйте ORDER BY для сортировки и LIMIT для ограничения.',
        xpPenalty: 0,
      },
    ],
    sampleSolution: 'SELECT first_name, last_name, salary FROM employees ORDER BY salary DESC LIMIT 5;',
    verificationQuery: 'SELECT salary FROM employees ORDER BY salary DESC LIMIT 1;',
  },

  {
    id: 'beginner-6',
    title: 'Уникальные значения DISTINCT',
    description: 'Получить уникальные значения столбца',
    difficulty: 'beginner',
    dbType: 'sqlite',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Получите список всех уникальных городов (location) из таблицы departments.',
    hint: 'Используйте DISTINCT перед именем столбца.',
    progressiveHints: [
      {
        level: 1,
        text: 'Вам нужно получить только уникальные значения из столбца',
        xpPenalty: 0,
      },
      {
        level: 2,
        text: 'Используйте ключевое слово DISTINCT для удаления дубликатов',
        xpPenalty: 0,
      },
      {
        level: 3,
        text: 'Используйте DISTINCT перед именем столбца.',
        xpPenalty: 0,
      },
    ],
    sampleSolution: 'SELECT DISTINCT location FROM departments;',
    verificationQuery: 'SELECT COUNT(DISTINCT location) as count FROM departments;',
  },

  {
    id: 'beginner-7',
    title: 'Агрегатные функции COUNT и SUM',
    description: 'Использовать агрегатные функции для вычислений',
    difficulty: 'beginner',
    dbType: 'sqlite',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Посчитайте общее количество сотрудников и сумму всех зарплат в компании.',
    hint: 'Используйте COUNT(*) для подсчёта строк и SUM(column) для суммы.',
    progressiveHints: [
      {
        level: 1,
        text: 'Вам нужно вычислить итоговые значения для всей таблицы сотрудников',
        xpPenalty: 0,
      },
      {
        level: 2,
        text: 'Используйте агрегатные функции для подсчёта и суммирования',
        xpPenalty: 0,
      },
      {
        level: 3,
        text: 'Используйте COUNT(*) для подсчёта строк и SUM(column) для суммы.',
        xpPenalty: 0,
      },
    ],
    sampleSolution: 'SELECT COUNT(*) as total_employees, SUM(salary) as total_salary FROM employees;',
    verificationQuery: 'SELECT COUNT(*) as total_employees FROM employees;',
  },

  {
    id: 'beginner-8',
    title: 'Среднее значение AVG',
    description: 'Вычислить среднее значение столбца',
    difficulty: 'beginner',
    dbType: 'sqlite',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Вычислите среднюю зарплату сотрудников для каждого отдела. Выведите department_id и среднюю зарплату.',
    hint: 'GROUP BY "схлопывает" строки с одинаковым значением столбца в одну группу. Агрегатные функции (AVG, COUNT, SUM) вычисляют результат внутри каждой группы. Если есть GROUP BY, то в SELECT можно использовать только столбцы из GROUP BY и агрегатные функции.',
    progressiveHints: [
      {
        level: 1,
        text: 'Вам нужно сгруппировать сотрудников по отделам и вычислить среднее для каждой группы',
        xpPenalty: 0,
      },
      {
        level: 2,
        text: 'Используйте GROUP BY по department_id и AVG(salary) для расчёта',
        xpPenalty: 0,
      },
      {
        level: 3,
        text: 'GROUP BY "схлопывает" строки с одинаковым значением столбца в одну группу. Агрегатные функции (AVG, COUNT, SUM) вычисляют результат внутри каждой группы. Если есть GROUP BY, то в SELECT можно использовать только столбцы из GROUP BY и агрегатные функции.',
        xpPenalty: 0,
      },
    ],
    sampleSolution: 'SELECT department_id, AVG(salary) as avg_salary FROM employees GROUP BY department_id;',
    verificationQuery: 'SELECT COUNT(DISTINCT department_id) as dept_count FROM employees WHERE department_id IS NOT NULL;',
  },


  // ==================== SHOP TASKS ====================
  {
    id: 'ch-34',
    title: 'ClickHouse: toYYYYMM и группировка по месяцам',
    description: 'Помесячная статистика заказов',
    difficulty: 'beginner',
    dbType: 'clickhouse',
    category: 'shop',
    schema: SHOP_SCHEMA,
    taskText: 'Сгруппируйте заказы по месяцам, используя функцию toYYYYMM(order_date). Для каждого месяца выведите month и order_count. Отсортируйте по month.',
    hint: 'toYYYYMM(date) преобразует дату в число в формате YYYYMM, удобное для группировки по месяцам.',
    sampleSolution: 'SELECT toYYYYMM(order_date) AS month, COUNT(*) AS order_count FROM orders GROUP BY month ORDER BY month;',
    verificationQuery: 'SELECT COUNT(*) as count FROM orders;',
  },

  {
    id: 'pg-23',
    title: 'PostgreSQL: CONCAT_WS',
    description: 'Объединение строк с разделителем через CONCAT_WS',
    difficulty: 'beginner',
    dbType: 'postgresql',
    category: 'shop',
    schema: SHOP_SCHEMA,
    taskText: 'Для каждого клиента выведите полное имя (first_name и last_name через пробел) и email. Используйте CONCAT_WS(\' \', first_name, last_name) для объединения с разделителем. Выведите full_name и email. Отсортируйте по full_name.',
    hint: 'CONCAT_WS(separator, str1, str2, ...) объединяет строки через разделитель, автоматически пропуская NULL значения.',
    sampleSolution: "SELECT CONCAT_WS(' ', first_name, last_name) AS full_name, email FROM customers ORDER BY full_name;",
    verificationQuery: 'SELECT COUNT(*) as count FROM customers;',
  },

  {
    id: 'shop-b1',
    title: 'Каталог категорий',
    description: 'Просмотр таблицы категорий магазина',
    difficulty: 'beginner',
    dbType: 'sqlite',
    category: 'shop',
    schema: SHOP_SCHEMA,
    taskText: 'Выведите все категории товаров (name, description) из таблицы categories.',
    hint: 'Используйте SELECT с нужными столбцами FROM categories.',
    sampleSolution: 'SELECT name, description FROM categories;',
    verificationQuery: 'SELECT COUNT(*) as count FROM categories;',
  },

  {
    id: 'shop-b2',
    title: 'Товары и цены',
    description: 'Выборка товаров с ценами',
    difficulty: 'beginner',
    dbType: 'sqlite',
    category: 'shop',
    schema: SHOP_SCHEMA,
    taskText: 'Выведите названия товаров (name), цены (price) и остаток на складе (stock_quantity) из таблицы products. Отсортируйте по убыванию цены.',
    hint: 'SELECT с ORDER BY price DESC для сортировки по убыванию.',
    sampleSolution: 'SELECT name, price, stock_quantity FROM products ORDER BY price DESC;',
    verificationQuery: 'SELECT COUNT(*) as count FROM products;',
  },

  {
    id: 'shop-b3',
    title: 'Дорогие товары',
    description: 'Фильтрация товаров по цене',
    difficulty: 'beginner',
    dbType: 'sqlite',
    category: 'shop',
    schema: SHOP_SCHEMA,
    taskText: 'Найдите все товары дороже 10000 рублей. Выведите name, price и category_id.',
    hint: 'Используйте WHERE price > 10000.',
    sampleSolution: 'SELECT name, price, category_id FROM products WHERE price > 10000 ORDER BY price DESC;',
    verificationQuery: 'SELECT COUNT(*) as count FROM products WHERE price > 10000;',
  },

  {
    id: 'shop-b4',
    title: 'Топ-5 самых дорогих',
    description: 'LIMIT с сортировкой',
    difficulty: 'beginner',
    dbType: 'sqlite',
    category: 'shop',
    schema: SHOP_SCHEMA,
    taskText: 'Выведите 5 самых дорогих товаров: name, price. Отсортируйте по убыванию цены.',
    hint: 'ORDER BY price DESC LIMIT 5.',
    sampleSolution: 'SELECT name, price FROM products ORDER BY price DESC LIMIT 5;',
    verificationQuery: 'SELECT price FROM products ORDER BY price DESC LIMIT 1;',
  },

  {
    id: 'shop-b5',
    title: 'Заказы по статусам',
    description: 'GROUP BY для подсчёта заказов',
    difficulty: 'beginner',
    dbType: 'sqlite',
    category: 'shop',
    schema: SHOP_SCHEMA,
    taskText: 'Посчитайте количество заказов для каждого статуса (status). Выведите status и количество заказов.',
    hint: 'GROUP BY status с COUNT(*).',
    sampleSolution: 'SELECT status, COUNT(*) as order_count FROM orders GROUP BY status ORDER BY order_count DESC;',
    verificationQuery: 'SELECT COUNT(DISTINCT status) as count FROM orders;',
  },

  {
    id: 'shop-b6',
    title: 'Средняя цена по категориям',
    description: 'AVG + GROUP BY по категориям',
    difficulty: 'beginner',
    dbType: 'sqlite',
    category: 'shop',
    schema: SHOP_SCHEMA,
    taskText: 'Вычислите среднюю цену и количество товаров для каждой категории. Выведите category_id, среднюю цену и количество.',
    hint: 'AVG(price) и COUNT(*) с GROUP BY category_id.',
    sampleSolution: 'SELECT category_id, ROUND(AVG(price)) as avg_price, COUNT(*) as product_count FROM products GROUP BY category_id ORDER BY avg_price DESC;',
    verificationQuery: 'SELECT COUNT(DISTINCT category_id) as count FROM products;',
  },

  {
    id: 'shop-b7',
    title: 'Уникальные города клиентов',
    description: 'DISTINCT для городов',
    difficulty: 'beginner',
    dbType: 'sqlite',
    category: 'shop',
    schema: SHOP_SCHEMA,
    taskText: 'Выведите список уникальных городов клиентов (city) из таблицы customers. Отсортируйте по алфавиту.',
    hint: 'SELECT DISTINCT city FROM customers ORDER BY city.',
    sampleSolution: 'SELECT DISTINCT city FROM customers ORDER BY city;',
    verificationQuery: 'SELECT COUNT(DISTINCT city) as count FROM customers;',
  },


  // ==================== COMPANY TASKS (PostgreSQL/ClickHouse) ====================
  {
    id: 'ch-40',
    title: 'ClickHouse: bar() для визуализации',
    description: 'Визуальное сравнение бюджетов отделов',
    difficulty: 'beginner',
    dbType: 'clickhouse',
    category: 'company',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Выведите бюджет каждого отдела с визуальной полоской. Используйте bar(budget / 500000, 0, 10, 20) — параметр 20 задаёт ширину полоски в символах. Выведите name, budget и budget_bar. Отсортируйте по budget DESC.',
    hint: 'bar(value, min, max, width) рисует текстовую полоску из символов ▏..▉ пропорционально значению. Полезно для визуализации в консоли.',
    sampleSolution: "SELECT name, budget, bar(budget / 500000, 0, 10, 20) AS budget_bar FROM departments ORDER BY budget DESC;",
    verificationQuery: 'SELECT COUNT(*) as count FROM departments;',
  },

  {
    id: 'pg-22',
    title: 'PostgreSQL: NULLIF',
    description: 'Предотвращение деления на ноль с NULLIF',
    difficulty: 'beginner',
    dbType: 'postgresql',
    category: 'company',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Для каждого отдела вычислите бюджет на одного сотрудника (budget / количество сотрудников). Используйте NULLIF(COUNT(e.id), 0), чтобы избежать деления на ноль, если в отделе нет сотрудников. Выведите name отдела, budget, emp_count и budget_per_employee. Отсортируйте по budget_per_employee DESC.',
    hint: 'NULLIF(col, 0) возвращает NULL, если col = 0. Деление на NULL даёт NULL вместо ошибки деления на ноль.',
    sampleSolution: "SELECT d.name, d.budget, COUNT(e.id) AS emp_count, ROUND(d.budget / NULLIF(COUNT(e.id), 0), 2) AS budget_per_employee FROM departments d LEFT JOIN employees e ON d.id = e.department_id GROUP BY d.id, d.name, d.budget ORDER BY budget_per_employee DESC;",
    verificationQuery: 'SELECT COUNT(*) as count FROM departments;',
  },


  // ==================== ANALYTICS TASKS (ClickHouse) ====================
  {
    id: 'analytics-b1',
    title: 'Выборка событий с LIMIT',
    description: 'Базовый SELECT из таблицы событий',
    difficulty: 'beginner',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Выведите все события из таблицы events, ограничив результат 10 строками. Используйте ClickHouse-синтаксис.',
    hint: 'Используйте SELECT * FROM events LIMIT 10.',
    sampleSolution: 'SELECT * FROM events LIMIT 10;',
    verificationQuery: 'SELECT COUNT(*) as count FROM events;',
  },

  {
    id: 'analytics-b2',
    title: 'Фильтрация по устройству',
    description: 'WHERE с фильтром по device',
    difficulty: 'beginner',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Найдите все события с устройства \'mobile\'. Выведите event_id, user_id, event_type и event_time. Отсортируйте по event_time.',
    hint: 'Используйте WHERE device = \'mobile\' и ORDER BY event_time.',
    sampleSolution: "SELECT event_id, user_id, event_type, event_time FROM events WHERE device = 'mobile' ORDER BY event_time;",
    verificationQuery: "SELECT COUNT(*) as count FROM events WHERE device = 'mobile';",
  },

  {
    id: 'analytics-b3',
    title: 'Группировка по типу события',
    description: 'GROUP BY с count() для подсчёта событий',
    difficulty: 'beginner',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Посчитайте количество событий каждого типа (event_type). Выведите event_type и количество. Используйте ClickHouse-функцию count().',
    hint: 'SELECT event_type, count(*) as event_count FROM events GROUP BY event_type ORDER BY event_count DESC.',
    sampleSolution: 'SELECT event_type, count(*) as event_count FROM events GROUP BY event_type ORDER BY event_count DESC;',
    verificationQuery: 'SELECT COUNT(DISTINCT event_type) as count FROM events;',
  },

  {
    id: 'analytics-b4',
    title: 'Топ стран по событиям',
    description: 'ORDER BY + LIMIT для топ-результата',
    difficulty: 'beginner',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Найдите топ-3 страны по количеству событий. Выведите country и count. Используйте GROUP BY, ORDER BY DESC и LIMIT.',
    hint: 'Сгруппируйте по country, отсортируйте по убыванию и ограничьте 3 строками.',
    sampleSolution: 'SELECT country, count(*) as event_count FROM events GROUP BY country ORDER BY event_count DESC LIMIT 3;',
    verificationQuery: 'SELECT COUNT(DISTINCT country) as count FROM events;',
  },

  {
    id: 'analytics-b5',
    title: 'uniq — уникальные пользователи',
    description: 'ClickHouse-функция uniq() для подсчёта уникальных значений',
    difficulty: 'beginner',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Посчитайте количество уникальных пользователей (user_id) для каждого устройства (device). Используйте ClickHouse-функцию uniq().',
    hint: 'uniq(user_id) считает количество уникальных значений user_id в каждой группе.',
    sampleSolution: 'SELECT device, uniq(user_id) as unique_users, count(*) as total_events FROM events GROUP BY device ORDER BY unique_users DESC;',
    verificationQuery: 'SELECT COUNT(DISTINCT device) as count FROM events;',
  },

  {
    id: 'ch-32',
    title: 'ClickHouse: neighbour() для рядов рядом',
    description: 'Поиск событий с длительностью, близкой к предыдущему событию',
    difficulty: 'beginner',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: CLICKHOUSE_EVENTS_SCHEMA,
    taskText: 'Для каждого события (кроме первого) найдите предыдущую длительность с помощью функции neighbour(duration, -1). Выведите id, event_type, duration и prev_duration. Отфильтруйте только события, у которых duration > 0, prev_duration > 0 и ABS(duration - prev_duration) < 10. Отсортируйте по id.',
    hint: 'neighbour(col, offset) позволяет получить значение из соседней строки: offset = -1 — предыдущая строка, offset = 1 — следующая.',
    sampleSolution: "SELECT id, event_type, duration, neighbour(duration, -1) AS prev_duration FROM events WHERE duration > 0 AND neighbour(duration, -1) > 0 AND abs(duration - neighbour(duration, -1)) < 10 ORDER BY id;",
    verificationQuery: 'SELECT COUNT(*) as count FROM events WHERE duration > 0;',
  },

  {
    id: 'ch-38',
    title: 'ClickHouse: formatDateTime для красивых дат',
    description: 'Форматирование даты и времени события',
    difficulty: 'beginner',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: CLICKHOUSE_EVENTS_SCHEMA,
    taskText: 'Выведите события с форматированной датой: id, event_type и formatted_time в формате \'DD.MM.YYYY HH:MM\'. Используйте formatDateTime(event_time, \'%d.%m.%Y %H:%i\'). Отсортируйте по event_time.',
    hint: 'formatDateTime(date, format) форматирует DateTime по шаблону. %d — день, %m — месяц, %Y — год, %H — часы, %i — минуты.',
    sampleSolution: "SELECT id, event_type, formatDateTime(event_time, '%d.%m.%Y %H:%i') AS formatted_time FROM events ORDER BY event_time;",
    verificationQuery: 'SELECT COUNT(*) as count FROM events;',
  },

  {
    id: 'ch-beginner-1',
    title: 'Базовый SELECT',
    description: 'Выбрать данные из таблицы',
    difficulty: 'beginner',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Выведите все события из таблицы events (первые 10).',
    hint: 'Используйте SELECT * FROM events LIMIT 10.',
    sampleSolution: 'SELECT * FROM events LIMIT 10;',
    verificationQuery: 'SELECT COUNT(*) as count FROM events;',
  },

  {
    id: 'ch-beginner-2',
    title: 'toDate и toDateTime',
    description: 'Работа с функциями дат',
    difficulty: 'beginner',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Выведите user_id, event_type и дату события (только дата, без времени) для всех событий. Используйте toDate().',
    hint: 'toDate(event_time) преобразует DateTime в дату.',
    sampleSolution: 'SELECT user_id, event_type, toDate(event_time) as event_date FROM events LIMIT 20;',
    verificationQuery: 'SELECT COUNT(*) as count FROM events;',
  },

  {
    id: 'ch-beginner-3',
    title: 'Фильтрация WHERE',
    description: 'Фильтрация с условиями',
    difficulty: 'beginner',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Найдите все события с device = "mobile". Выведите event_id, user_id, event_type.',
    hint: 'Используйте WHERE device = \'mobile\'.',
    sampleSolution: "SELECT event_id, user_id, event_type FROM events WHERE device = 'mobile';",
    verificationQuery: "SELECT COUNT(*) as count FROM events WHERE device = 'mobile';",
  },

  {
    id: 'pg-14',
    title: 'BOOLEAN тип и TRUE/FALSE',
    description: 'PostgreSQL boolean type usage',
    difficulty: 'beginner',
    dbType: 'postgresql',
    category: 'analytics',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Найдите всех активных сотрудников с помощью IS TRUE. Выведите first_name и last_name. Отсортируйте по last_name.',
    hint: 'PostgreSQL supports native BOOLEAN type with TRUE/FALSE values.',
    sampleSolution: 'SELECT first_name, last_name FROM employees WHERE is_active IS TRUE ORDER BY last_name;',
    verificationQuery: 'SELECT COUNT(*) as count FROM employees WHERE is_active = 1;',
  },


  // ==================== EXAM TASKS ====================
  {
    id: 'ch-exam-1',
    title: 'Экзамен ClickHouse: toStartOfMonth',
    description: 'Количество сотрудников по месяцу найма',
    difficulty: 'beginner',
    dbType: 'clickhouse',
    category: 'exam',
    examGroup: 'ch-exam-beginner',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Сгруппируйте сотрудников по месяцу найма с помощью toStartOfMonth(toDate(hire_date)). Выведите hire_month и emp_count. Отсортируйте по hire_month.',
    hint: 'toStartOfMonth(date) приводит дату к первому дню месяца. Удобно для помесячной группировки.',
    sampleSolution: 'SELECT toStartOfMonth(toDate(hire_date)) AS hire_month, COUNT(*) AS emp_count FROM employees GROUP BY hire_month ORDER BY hire_month;',
    verificationQuery: 'SELECT COUNT(*) as count FROM employees;',
  },

  {
    id: 'ch-exam-2',
    title: 'Экзамен ClickHouse: if() для категоризации',
    description: 'Категоризация зарплат с помощью if()',
    difficulty: 'beginner',
    dbType: 'clickhouse',
    category: 'exam',
    examGroup: 'ch-exam-beginner',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Для каждого сотрудника определите категорию зарплаты с помощью вложенных if(): «низкая» (< 110000), «средняя» (110000–140000), «высокая» (> 140000). Выведите first_name, last_name, salary и salary_category. Отсортируйте по salary DESC.',
    hint: 'if(condition, then, else) — условное выражение. Для множественных условий вкладывайте: if(c1, v1, if(c2, v2, else)). Или используйте multiIf.',
    sampleSolution: "SELECT first_name, last_name, salary, if(salary < 110000, 'низкая', if(salary < 140000, 'средняя', 'высокая')) AS salary_category FROM employees ORDER BY salary DESC;",
    verificationQuery: 'SELECT COUNT(*) as count FROM employees;',
  },

  {
    id: 'ch-exam-3',
    title: 'Экзамен ClickHouse: formatDateTime',
    description: 'Форматирование даты найма',
    difficulty: 'beginner',
    dbType: 'clickhouse',
    category: 'exam',
    examGroup: 'ch-exam-beginner',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Выведите сотрудников: first_name, last_name и formatted_date — hire_date в формате \'YYYY-MM-DD\'. Используйте formatDateTime(toDateTime(hire_date), \'%Y-%m-%d\'). Отсортируйте по hire_date.',
    hint: 'formatDateTime(datetime, format) форматирует DateTime. %Y — 4-значный год, %m — месяц (01-12), %d — день (01-31).',
    sampleSolution: "SELECT first_name, last_name, formatDateTime(toDateTime(hire_date), '%Y-%m-%d') AS formatted_date FROM employees ORDER BY hire_date;",
    verificationQuery: 'SELECT COUNT(*) as count FROM employees;',
  },

  {
    id: 'exam-b1',
    title: 'Экзамен: Фильтрация данных',
    description: 'Проверочная работа — WHERE, операторы сравнения',
    difficulty: 'beginner',
    dbType: 'sqlite',
    category: 'exam',
    examGroup: 'exam-beginner',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Найдите всех сотрудников, чья зарплата от 100000 до 130000 включительно. Выведите first_name, last_name, salary. Отсортируйте по зарплате.',
    hint: 'Используйте WHERE salary BETWEEN 100000 AND 130000.',
    sampleSolution: 'SELECT first_name, last_name, salary FROM employees WHERE salary BETWEEN 100000 AND 130000 ORDER BY salary;',
    verificationQuery: "SELECT COUNT(*) as count FROM employees WHERE salary BETWEEN 100000 AND 130000;",
  },

  {
    id: 'exam-b2',
    title: 'Экзамен: Сортировка и ограничение',
    description: 'Проверочная работа — ORDER BY, LIMIT, OFFSET',
    difficulty: 'beginner',
    dbType: 'sqlite',
    category: 'exam',
    examGroup: 'exam-beginner',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Выведите 3-х самых низкооплачиваемых сотрудников (first_name, last_name, salary) из отдела "HR" (department_id = 4).',
    hint: 'WHERE department_id = 4, ORDER BY salary ASC, LIMIT 3.',
    sampleSolution: 'SELECT first_name, last_name, salary FROM employees WHERE department_id = 4 ORDER BY salary ASC LIMIT 3;',
    verificationQuery: 'SELECT 3 as expected_count;',
  },

  {
    id: 'exam-b3',
    title: 'Экзамен: Поиск по шаблону',
    description: 'Проверочная работа — LIKE, паттерны',
    difficulty: 'beginner',
    dbType: 'sqlite',
    category: 'exam',
    examGroup: 'exam-beginner',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Найдите всех сотрудников, чья фамилия заканчивается на "ова". Выведите first_name, last_name. Отсортируйте по фамилии.',
    hint: "Используйте WHERE last_name LIKE '%ова'.",
    sampleSolution: "SELECT first_name, last_name FROM employees WHERE last_name LIKE '%ова' ORDER BY last_name;",
    verificationQuery: "SELECT COUNT(*) as count FROM employees WHERE last_name LIKE '%ова';",
  },

  {
    id: 'exam-b4',
    title: 'Экзамен: Агрегация с фильтром',
    description: 'Проверочная работа — COUNT, SUM с WHERE',
    difficulty: 'beginner',
    dbType: 'sqlite',
    category: 'exam',
    examGroup: 'exam-beginner',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Посчитайте количество активных сотрудников (is_active = 1) и среднюю зарплату среди них в одном запросе.',
    hint: 'WHERE is_active = 1, затем COUNT(*) и AVG(salary).',
    sampleSolution: 'SELECT COUNT(*) as active_count, ROUND(AVG(salary)) as avg_salary FROM employees WHERE is_active = 1;',
    verificationQuery: 'SELECT 22 as expected_count;',
  },

  {
    id: 'exam-b5',
    title: 'Экзамен: Группировка',
    description: 'Проверочная работа — GROUP BY с несколькими агрегатами',
    difficulty: 'beginner',
    dbType: 'sqlite',
    category: 'exam',
    examGroup: 'exam-beginner',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Для каждого города departments выведите: количество отделов и суммарный бюджет. Выведите location, count, total_budget.',
    hint: 'GROUP BY location с COUNT(*) и SUM(budget).',
    sampleSolution: 'SELECT location, COUNT(*) as dept_count, SUM(budget) as total_budget FROM departments GROUP BY location ORDER BY total_budget DESC;',
    verificationQuery: 'SELECT COUNT(DISTINCT location) as count FROM departments;',
  },

  {
    id: 'pg-exam-1',
    title: 'Экзамен PostgreSQL: TRUE/FALSE условия',
    description: 'Поиск сотрудников с зарплатой выше порога',
    difficulty: 'beginner',
    dbType: 'postgresql',
    category: 'exam',
    examGroup: 'pg-exam-beginner',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Выведите first_name, last_name и salary сотрудников, у которых зарплата больше 120000. Добавьте столбец high_salary со значением TRUE или FALSE (salary > 120000). Отсортируйте по salary DESC.',
    hint: 'В PostgreSQL выражение (salary > 120000) возвращает TRUE или FALSE. Можно использовать прямо в SELECT как вычисляемый столбец.',
    sampleSolution: 'SELECT first_name, last_name, salary, (salary > 120000) AS high_salary FROM employees WHERE salary > 120000 ORDER BY salary DESC;',
    verificationQuery: 'SELECT COUNT(*) as count FROM employees WHERE salary > 120000;',
  },

  {
    id: 'pg-exam-2',
    title: 'Экзамен PostgreSQL: ILIKE для поиска',
    description: 'Поиск сотрудников с буквой «а» в имени',
    difficulty: 'beginner',
    dbType: 'postgresql',
    category: 'exam',
    examGroup: 'pg-exam-beginner',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Найдите всех сотрудников, у которых в first_name есть буква «а» (русская, строчная). Используйте ILIKE для регистронезависимого поиска. Выведите first_name и last_name. Отсортируйте по first_name.',
    hint: 'ILIKE выполняет регистронезависимый поиск с шаблонами: % — любая последовательность символов, _ — один символ.',
    sampleSolution: "SELECT first_name, last_name FROM employees WHERE first_name ILIKE '%а%' ORDER BY first_name;",
    verificationQuery: "SELECT COUNT(*) as count FROM employees WHERE first_name LIKE '%а%' OR first_name LIKE '%А%';",
  },

  {
    id: 'pg-exam-3',
    title: 'Экзамен PostgreSQL: COALESCE для замены NULL',
    description: 'Замена NULL значений на текст по умолчанию',
    difficulty: 'beginner',
    dbType: 'postgresql',
    category: 'exam',
    examGroup: 'pg-exam-beginner',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Выведите проекты: name, start_date, end_date и status. Замените NULL в end_date на текст \'В процессе\' с помощью COALESCE. Отсортируйте по name.',
    hint: 'COALESCE(val1, val2, ...) возвращает первый не-NULL аргумент. Полезно для замены NULL на значения по умолчанию.',
    sampleSolution: "SELECT name, start_date, COALESCE(end_date, 'В процессе') AS end_date, status FROM projects ORDER BY name;",
    verificationQuery: 'SELECT COUNT(*) as count FROM projects;',
  },

  // ==================== CLICKHOUSE REAL-WORLD ANALYTICS ====================
  {
    id: 'ch-analytics-real-1',
    title: 'ClickHouse: Ежедневные активные пользователи (DAU)',
    description: 'Подсчёт уникальных пользователей по дням',
    difficulty: 'beginner',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Посчитайте количество уникальных пользователей (user_id) для каждого дня. Используйте toDate(event_time) для группировки по дням и uniq() для подсчёта уникальных. Выведите day и dau. Отсортируйте по day.',
    hint: 'uniq(user_id) — быстрая аппроксимация количества уникальных значений в ClickHouse. toDate(event_time) извлекает дату из DateTime.',
    sampleSolution: 'SELECT toDate(event_time) AS day, uniq(user_id) AS dau FROM events GROUP BY day ORDER BY day;',
    verificationQuery: 'SELECT COUNT(*) as count FROM events;',
  },

  {
    id: 'ch-analytics-real-2',
    title: 'ClickHouse: Распределение по устройствам',
    description: 'Доля событий по типам устройств',
    difficulty: 'beginner',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Посчитайте количество событий и долю (%) для каждого устройства (device). Используйте count() для подсчёта и count() * 100.0 / (SELECT count() FROM events) для доли. Выведите device, events_count и events_pct.',
    hint: 'Для доли можно использовать оконную функцию: count() * 100.0 / sum(count()) OVER () — это даст процент от общего числа.',
    sampleSolution: 'SELECT device, count(*) AS events_count, round(count(*) * 100.0 / sum(count()) OVER (), 1) AS events_pct FROM events GROUP BY device ORDER BY events_count DESC;',
    verificationQuery: 'SELECT COUNT(DISTINCT device) as count FROM events;',
  },

  {
    id: 'ch-analytics-real-3',
    title: 'ClickHouse: Конверсия по типам событий',
    description: 'Воронка: просмотры → клики → покупки',
    difficulty: 'beginner',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Посчитайте количество событий для каждого типа (event_type) с помощью countIf(). Выведите page_views (event_type = "page_view"), clicks (event_type = "click") и purchases (event_type = "purchase").',
    hint: 'countIf(event_type = "page_view") считает только просмотры. Используйте несколько countIf в одном запросе для воронки.',
    sampleSolution: "SELECT countIf(event_type = 'page_view') AS page_views, countIf(event_type = 'click') AS clicks, countIf(event_type = 'purchase') AS purchases FROM events;",
    verificationQuery: 'SELECT COUNT(*) as count FROM events;',
  },

];
