/**
 * ClickHouse Task Definitions
 * Auto-generated from training-tasks.ts
 */

import type { TrainingTask } from './types';
import { ANALYTICS_SCHEMA, CLICKHOUSE_EVENTS_SCHEMA, EMPLOYEES_SCHEMA, SHOP_SCHEMA } from './schemas';

export const CLICKHOUSE_TASKS: TrainingTask[] = [

  // ==================== SHOP TASKS ====================
  {
    id: 'ch-34',
    title: 'ClickHouse: toYYYYMM и группировка по месяцам',
    description: 'Помесячная статистика заказов',
    difficulty: 'beginner',
    dbType: 'clickhouse',
    category: 'shop',
    schema: SHOP_SCHEMA,
    taskText: 'Сгруппируйте заказы по месяцам, используя функцию toYYYYMM(order_date). Для каждого месяца выведите month и order_count. Отсортируйте по month.',
    hint: 'toYYYYMM(date) преобразует дату в число в формате YYYYMM, удобное для группировки по месяцам.',
    sampleSolution: 'SELECT toYYYYMM(order_date) AS month, COUNT(*) AS order_count FROM orders GROUP BY month ORDER BY month;',
    verificationQuery: 'SELECT COUNT(*) as count FROM orders;',
  },

  {
    id: 'ch-35',
    title: 'ClickHouse: groupArray + arrayJoin',
    description: 'Сбор товаров в массивы по категориям и раскрытие массивов',
    difficulty: 'intermediate',
    dbType: 'clickhouse',
    category: 'shop',
    schema: SHOP_SCHEMA,
    taskText: 'Для каждой категории соберите названия товаров в массив products с помощью groupArray(). Выведите name категории и products. Отсортируйте по name. Дополнительно покажите, что arrayJoin() раскрывает массив обратно в строки: SELECT arrayJoin(groupArray(DISTINCT shipping_city)) AS city FROM orders;',
    hint: 'groupArray(expr) собирает все значения в группе в массив. arrayJoin(arr) раскрывает массив в отдельные строки — обратная операция.',
    sampleSolution: "SELECT c.name, groupArray(p.name) AS products FROM products p JOIN categories c ON p.category_id = c.id GROUP BY c.name ORDER BY c.name;",
    verificationQuery: 'SELECT COUNT(*) as count FROM categories WHERE (SELECT COUNT(*) FROM products WHERE category_id = categories.id) > 0;',
  },

  {
    id: 'ch-36',
    title: 'ClickHouse: avgIf для фильтрованной аналитики',
    description: 'Средняя цена только активных товаров',
    difficulty: 'intermediate',
    dbType: 'clickhouse',
    category: 'shop',
    schema: SHOP_SCHEMA,
    taskText: 'Для каждой категории вычислите среднюю цену только активных товаров (is_active = 1). Используйте avgIf(price, is_active = 1). Выведите name категории и avg_active_price (округлите до 2 знаков). Отсортируйте по avg_active_price DESC.',
    hint: 'avgIf(expr, condition) вычисляет среднее только по строкам, удовлетворяющим условию. Аналоги: sumIf, countIf, minIf, maxIf.',
    sampleSolution: "SELECT c.name, ROUND(avgIf(p.price, p.is_active = 1), 2) AS avg_active_price FROM products p JOIN categories c ON p.category_id = c.id GROUP BY c.name ORDER BY avg_active_price DESC;",
    verificationQuery: 'SELECT COUNT(*) as count FROM categories;',
  },

  {
    id: 'ch-41',
    title: 'ClickHouse: having + countIf',
    description: 'Категории с более чем 3 товарами',
    difficulty: 'intermediate',
    dbType: 'clickhouse',
    category: 'shop',
    schema: SHOP_SCHEMA,
    taskText: 'Найдите категории, в которых более 3 товаров. Используйте GROUP BY category_id, HAVING COUNT(*) > 3. Для каждой подходящей категории выведите name, product_count и expensive_count (товары с ценой > 5000 через countIf). Отсортируйте по product_count DESC.',
    hint: 'HAVING фильтрует группы после GROUP BY. countIf(condition) считает строки, удовлетворяющие условию внутри группы.',
    sampleSolution: "SELECT c.name, COUNT(*) AS product_count, countIf(p.price > 5000) AS expensive_count FROM products p JOIN categories c ON p.category_id = c.id GROUP BY c.name, c.id HAVING COUNT(*) > 3 ORDER BY product_count DESC;",
    verificationQuery: 'SELECT COUNT(*) as count FROM categories WHERE (SELECT COUNT(*) FROM products WHERE category_id = categories.id) > 3;',
  },

  {
    id: 'ch-43',
    title: 'ClickHouse: groupUniqArray для уникальных списков',
    description: 'Уникальные города доставки по клиентам',
    difficulty: 'intermediate',
    dbType: 'clickhouse',
    category: 'shop',
    schema: SHOP_SCHEMA,
    taskText: 'Для каждого города доставки соберите уникальные идентификаторы клиентов в массив. Используйте groupUniqArray(customer_id). Выведите shipping_city, unique_customers (массив) и total_orders. Отсортируйте по shipping_city.',
    hint: 'groupUniqArray(expr) собирает только уникальные значения в массив (в отличие от groupArray, который может содержать дубликаты).',
    sampleSolution: 'SELECT shipping_city, groupUniqArray(customer_id) AS unique_customers, COUNT(*) AS total_orders FROM orders GROUP BY shipping_city ORDER BY shipping_city;',
    verificationQuery: 'SELECT COUNT(DISTINCT shipping_city) as count FROM orders;',
  },


  // ==================== COMPANY TASKS (PostgreSQL/ClickHouse) ====================
  {
    id: 'ch-37',
    title: 'ClickHouse: multiIf для категоризации',
    description: 'Категоризация зарплат по диапазонам',
    difficulty: 'intermediate',
    dbType: 'clickhouse',
    category: 'company',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Для каждого сотрудника определите диапазон зарплаты: «низкая» (< 100000), «средняя» (100000–120000), «высокая» (120000–150000), «очень высокая» (> 150000). Используйте multiIf(). Выведите first_name, last_name, salary и salary_range. Отсортируйте по salary DESC.',
    hint: 'multiIf(cond1, val1, cond2, val2, ..., elseVal) — цепочка условий, аналогичная CASE WHEN в SQL. Условия проверяются по порядку.',
    sampleSolution: "SELECT first_name, last_name, salary, multiIf(salary < 100000, 'низкая', salary < 120000, 'средняя', salary < 150000, 'высокая', 'очень высокая') AS salary_range FROM employees ORDER BY salary DESC;",
    verificationQuery: 'SELECT COUNT(*) as count FROM employees;',
  },

  {
    id: 'ch-40',
    title: 'ClickHouse: bar() для визуализации',
    description: 'Визуальное сравнение бюджетов отделов',
    difficulty: 'beginner',
    dbType: 'clickhouse',
    category: 'company',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Выведите бюджет каждого отдела с визуальной полоской. Используйте bar(budget / 500000, 0, 10, 20) — параметр 20 задаёт ширину полоски в символах. Выведите name, budget и budget_bar. Отсортируйте по budget DESC.',
    hint: 'bar(value, min, max, width) рисует текстовую полоску из символов ▏..▉ пропорционально значению. Полезно для визуализации в консоли.',
    sampleSolution: "SELECT name, budget, bar(budget / 500000, 0, 10, 20) AS budget_bar FROM departments ORDER BY budget DESC;",
    verificationQuery: 'SELECT COUNT(*) as count FROM departments;',
  },

  {
    id: 'ch-44',
    title: 'ClickHouse: toYear + toMonth для анализа',
    description: 'Сотрудники по году и месяцу найма',
    difficulty: 'intermediate',
    dbType: 'clickhouse',
    category: 'company',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Сгруппируйте сотрудников по году и месяцу найма. Используйте toYear(toDate(hire_date)) и toMonth(toDate(hire_date)). Выведите hire_year, hire_month, emp_count и avg_salary (округлите до 2 знаков). Отсортируйте по hire_year, hire_month.',
    hint: 'toYear(date) извлекает год, toMonth(date) — месяц. toDate() преобразует строку в тип Date.',
    sampleSolution: "SELECT toYear(toDate(hire_date)) AS hire_year, toMonth(toDate(hire_date)) AS hire_month, COUNT(*) AS emp_count, ROUND(AVG(salary), 2) AS avg_salary FROM employees GROUP BY hire_year, hire_month ORDER BY hire_year, hire_month;",
    verificationQuery: 'SELECT COUNT(*) as count FROM employees;',
  },


  // ==================== ANALYTICS TASKS (ClickHouse) ====================
  {
    id: 'analytics-a1',
    title: 'countIf и sumIf — условные агрегаты',
    description: 'ClickHouse-функции countIf() и sumIf()',
    difficulty: 'advanced',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Для каждого устройства посчитайте количество кликов (countIf), количество просмотров (countIf) и суммарную длительность просмотров (sumIf).',
    hint: "countIf(event_type = 'click') считает только клики. sumIf(duration, event_type = 'page_view') суммирует длительность только для просмотров.",
    sampleSolution: "SELECT device, countIf(event_type = 'click') as clicks, countIf(event_type = 'page_view') as views, sumIf(duration, event_type = 'page_view') as total_duration FROM events GROUP BY device ORDER BY clicks DESC;",
    verificationQuery: 'SELECT COUNT(DISTINCT device) as count FROM events;',
  },

  {
    id: 'analytics-a2',
    title: 'sumIf для завершённых покупок',
    description: 'JOIN + sumIf для фильтрации по статусу',
    difficulty: 'advanced',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Для каждого пользователя выведите: общее количество покупок, сумму только завершённых покупок (sumIf) и средний чек. Используйте LEFT JOIN purchases.',
    hint: "sumIf(p.amount, p.status = 'completed') считает сумму только для завершённых покупок.",
    sampleSolution: "SELECT u.username, count(p.purchase_id) as total_purchases, sumIf(p.amount, p.status = 'completed') as completed_amount, avg(p.amount) as avg_check FROM users u LEFT JOIN purchases p ON u.user_id = p.user_id GROUP BY u.user_id, u.username ORDER BY completed_amount DESC;",
    verificationQuery: 'SELECT COUNT(*) as count FROM users;',
  },

  {
    id: 'analytics-a3',
    title: 'groupArray — массивы в ClickHouse',
    description: 'ClickHouse-функция groupArray()',
    difficulty: 'advanced',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Для каждого пользователя соберите массив уникальных страниц, которые он посещал (только page_view). Используйте groupArray().',
    hint: 'groupArray(DISTINCT page) создаёт массив уникальных страниц для каждого user_id.',
    sampleSolution: "SELECT user_id, groupArray(DISTINCT page) as visited_pages, count(*) as view_count FROM events WHERE event_type = 'page_view' GROUP BY user_id ORDER BY view_count DESC;",
    verificationQuery: "SELECT COUNT(DISTINCT user_id) as count FROM events WHERE event_type = 'page_view';",
  },

  {
    id: 'analytics-a4',
    title: 'Оконная функция ROW_NUMBER',
    description: 'ROW_NUMBER() OVER для ранжирования',
    difficulty: 'advanced',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Пронумеруйте покупки каждого пользователя по дате (от новых к старым). Выведите username, product_id, amount, purchase_date и номер строки.',
    hint: 'ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY purchase_date DESC) нумерует покупки внутри каждого пользователя.',
    sampleSolution: 'SELECT u.username, p.product_id, p.amount, p.purchase_date, ROW_NUMBER() OVER (PARTITION BY p.user_id ORDER BY p.purchase_date DESC) as rn FROM purchases p JOIN users u ON p.user_id = u.user_id ORDER BY u.user_id, rn;',
    verificationQuery: 'SELECT COUNT(*) as count FROM purchases;',
  },

  {
    id: 'analytics-a5',
    title: 'CTE + ClickHouse-функции',
    description: 'WITH (CTE) + countIf для комплексного анализа',
    difficulty: 'advanced',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Используя CTE (WITH), найдите пользователей с более чем одним кликом. Выведите их имена и количество кликов. Используйте countIf().',
    hint: "Сначала создайте CTE с кликами на пользователя, затем отфильтруйте WHERE click_count > 1.",
    sampleSolution: "WITH user_clicks AS (SELECT user_id, countIf(event_type = 'click') as click_count FROM events GROUP BY user_id) SELECT u.username, uc.click_count FROM user_clicks uc JOIN users u ON uc.user_id = u.user_id WHERE uc.click_count > 1 ORDER BY uc.click_count DESC;",
    verificationQuery: "SELECT COUNT(*) as count FROM (SELECT user_id FROM events WHERE event_type = 'click' GROUP BY user_id HAVING count(*) > 1);",
  },

  {
    id: 'analytics-b1',
    title: 'Выборка событий с LIMIT',
    description: 'Базовый SELECT из таблицы событий',
    difficulty: 'beginner',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Выведите все события из таблицы events, ограничив результат 10 строками. Используйте ClickHouse-синтаксис.',
    hint: 'Используйте SELECT * FROM events LIMIT 10.',
    sampleSolution: 'SELECT * FROM events LIMIT 10;',
    verificationQuery: 'SELECT COUNT(*) as count FROM events;',
  },

  {
    id: 'analytics-b2',
    title: 'Фильтрация по устройству',
    description: 'WHERE с фильтром по device',
    difficulty: 'beginner',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Найдите все события с устройства \'mobile\'. Выведите event_id, user_id, event_type и event_time. Отсортируйте по event_time.',
    hint: 'Используйте WHERE device = \'mobile\' и ORDER BY event_time.',
    sampleSolution: "SELECT event_id, user_id, event_type, event_time FROM events WHERE device = 'mobile' ORDER BY event_time;",
    verificationQuery: "SELECT COUNT(*) as count FROM events WHERE device = 'mobile';",
  },

  {
    id: 'analytics-b3',
    title: 'Группировка по типу события',
    description: 'GROUP BY с count() для подсчёта событий',
    difficulty: 'beginner',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Посчитайте количество событий каждого типа (event_type). Выведите event_type и количество. Используйте ClickHouse-функцию count().',
    hint: 'SELECT event_type, count(*) as event_count FROM events GROUP BY event_type ORDER BY event_count DESC.',
    sampleSolution: 'SELECT event_type, count(*) as event_count FROM events GROUP BY event_type ORDER BY event_count DESC;',
    verificationQuery: 'SELECT COUNT(DISTINCT event_type) as count FROM events;',
  },

  {
    id: 'analytics-b4',
    title: 'Топ стран по событиям',
    description: 'ORDER BY + LIMIT для топ-результата',
    difficulty: 'beginner',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Найдите топ-3 страны по количеству событий. Выведите country и count. Используйте GROUP BY, ORDER BY DESC и LIMIT.',
    hint: 'Сгруппируйте по country, отсортируйте по убыванию и ограничьте 3 строками.',
    sampleSolution: 'SELECT country, count(*) as event_count FROM events GROUP BY country ORDER BY event_count DESC LIMIT 3;',
    verificationQuery: 'SELECT COUNT(DISTINCT country) as count FROM events;',
  },

  {
    id: 'analytics-b5',
    title: 'uniq — уникальные пользователи',
    description: 'ClickHouse-функция uniq() для подсчёта уникальных значений',
    difficulty: 'beginner',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Посчитайте количество уникальных пользователей (user_id) для каждого устройства (device). Используйте ClickHouse-функцию uniq().',
    hint: 'uniq(user_id) считает количество уникальных значений user_id в каждой группе.',
    sampleSolution: 'SELECT device, uniq(user_id) as unique_users, count(*) as total_events FROM events GROUP BY device ORDER BY unique_users DESC;',
    verificationQuery: 'SELECT COUNT(DISTINCT device) as count FROM events;',
  },

  {
    id: 'analytics-i1',
    title: 'JOIN пользователей и событий',
    description: 'LEFT JOIN users с events',
    difficulty: 'intermediate',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Выведите имя пользователя (username) и количество его событий. Используйте LEFT JOIN таблиц users и events.',
    hint: 'LEFT JOIN гарантирует, что все пользователи будут в результате, даже без событий.',
    sampleSolution: 'SELECT u.username, count(e.event_id) as event_count FROM users u LEFT JOIN events e ON u.user_id = e.user_id GROUP BY u.user_id, u.username ORDER BY event_count DESC;',
    verificationQuery: 'SELECT COUNT(*) as count FROM users;',
  },

  {
    id: 'analytics-i2',
    title: 'HAVING — фильтрация групп',
    description: 'GROUP BY + HAVING для фильтрации агрегатов',
    difficulty: 'intermediate',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Найдите страны, в которых больше 5 событий. Используйте GROUP BY country + HAVING с условием.',
    hint: 'HAVING count(*) > 5 фильтрует группы после агрегации.',
    sampleSolution: 'SELECT country, count(*) as event_count FROM events GROUP BY country HAVING count(*) > 5 ORDER BY event_count DESC;',
    verificationQuery: "SELECT COUNT(*) as count FROM (SELECT country FROM events GROUP BY country HAVING count(*) > 5);",
  },

  {
    id: 'analytics-i3',
    title: 'toStartOfDay — группировка по дням',
    description: 'ClickHouse-функция toStartOfDay()',
    difficulty: 'intermediate',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Посчитайте количество событий по дням (таблица events). Используйте ClickHouse-функцию toStartOfDay() для группировки.',
    hint: 'toStartOfDay(event_time) округляет DateTime до начала дня.',
    sampleSolution: 'SELECT toStartOfDay(event_time) as day, count(*) as event_count FROM events GROUP BY day ORDER BY day;',
    verificationQuery: "SELECT COUNT(DISTINCT date(event_time)) as days FROM events;",
  },

  {
    id: 'analytics-i4',
    title: 'toStartOfMonth — аналитика покупок',
    description: 'Группировка покупок по месяцам',
    difficulty: 'intermediate',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Выведите месяц покупки, количество покупок и общую сумму по месяцам. Используйте toStartOfMonth() для группировки.',
    hint: 'toStartOfMonth(purchase_date) возвращает первый день месяца для каждой покупки.',
    sampleSolution: 'SELECT toStartOfMonth(purchase_date) as month, count(*) as purchase_count, sum(amount) as total_amount FROM purchases GROUP BY month ORDER BY month;',
    verificationQuery: 'SELECT COUNT(DISTINCT purchase_date) as days FROM purchases;',
  },

  {
    id: 'analytics-i5',
    title: 'multiIf — множественное условие',
    description: 'ClickHouse-функция multiIf() для классификации',
    difficulty: 'intermediate',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Классифицируйте пользователей по возрасту: "молодой" (<25), "средний" (25-34), "старший" (>=35). Выведите username, age и категорию. Используйте multiIf().',
    hint: "multiIf(age < 25, 'молодой', age <= 34, 'средний', 'старший') — работает как CASE WHEN с несколькими условиями.",
    sampleSolution: "SELECT username, age, multiIf(age < 25, 'молодой', age <= 34, 'средний', 'старший') as age_category FROM users ORDER BY age;",
    verificationQuery: 'SELECT COUNT(*) as count FROM users;',
  },

  {
    id: 'ch-1',
    title: 'sumIf — условная сумма',
    description: 'Conditional sum with sumIf',
    difficulty: 'intermediate',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: CLICKHOUSE_EVENTS_SCHEMA,
    taskText: 'Вычислите общую продолжительность (duration) только событий типа page_view. Используйте sumIf(). Выведите результат как total_page_view_duration.',
    hint: 'sumIf(expr, condition) sums only rows matching the condition.',
    sampleSolution: "SELECT sumIf(duration, event_type = 'page_view') as total_page_view_duration FROM events;",
    verificationQuery: 'SELECT 1 as count;',
  },

  {
    id: 'ch-2',
    title: 'countIf — условный подсчёт',
    description: 'Conditional count with countIf',
    difficulty: 'intermediate',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: CLICKHOUSE_EVENTS_SCHEMA,
    taskText: 'Подсчитайте количество премиум-пользователей из Москвы. Используйте countIf(). Выведите результат как premium_moscow.',
    hint: 'countIf(condition) counts rows matching the condition.',
    sampleSolution: "SELECT countIf(is_premium = 1 AND city = 'Москва') as premium_moscow FROM users;",
    verificationQuery: 'SELECT 1 as count;',
  },

  {
    id: 'ch-3',
    title: 'toStartOfMonth — группировка по месяцам',
    description: 'Group by month with toStartOfMonth',
    difficulty: 'intermediate',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: CLICKHOUSE_EVENTS_SCHEMA,
    taskText: 'Сгруппируйте покупки по месяцам. Для каждого месяца выведите количество покупок (cnt) и общую сумму (total). Используйте toStartOfMonth().',
    hint: 'toStartOfMonth(date) truncates date to the first day of the month.',
    sampleSolution: 'SELECT toStartOfMonth(purchase_date) as month, count() as cnt, SUM(amount) as total FROM purchases GROUP BY month ORDER BY month;',
    verificationQuery: 'SELECT 1 as count;',
  },

  {
    id: 'ch-32',
    title: 'ClickHouse: neighbour() для рядов рядом',
    description: 'Поиск событий с длительностью, близкой к предыдущему событию',
    difficulty: 'beginner',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: CLICKHOUSE_EVENTS_SCHEMA,
    taskText: 'Для каждого события (кроме первого) найдите предыдущую длительность с помощью функции neighbour(duration, -1). Выведите id, event_type, duration и prev_duration. Отфильтруйте только события, у которых duration > 0, prev_duration > 0 и ABS(duration - prev_duration) < 10. Отсортируйте по id.',
    hint: 'neighbour(col, offset) позволяет получить значение из соседней строки: offset = -1 — предыдущая строка, offset = 1 — следующая.',
    sampleSolution: "SELECT id, event_type, duration, neighbour(duration, -1) AS prev_duration FROM events WHERE duration > 0 AND neighbour(duration, -1) > 0 AND abs(duration - neighbour(duration, -1)) < 10 ORDER BY id;",
    verificationQuery: 'SELECT COUNT(*) as count FROM events WHERE duration > 0;',
  },

  {
    id: 'ch-33',
    title: 'ClickHouse: dateDiff с INTERVAL',
    description: 'Количество дней между первым и последним событием для каждого пользователя',
    difficulty: 'intermediate',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: CLICKHOUSE_EVENTS_SCHEMA,
    taskText: 'Для каждого пользователя вычислите количество дней между первым и последним событием. Используйте dateDiff(\'day\', MIN(event_time), MAX(event_time)). Выведите user_id, first_event, last_event и days_span. Отсортируйте по user_id.',
    hint: 'dateDiff(unit, start, end) вычисляет разницу между двумя датами. Поддерживаемые единицы: \'day\', \'hour\', \'minute\', \'second\' и др.',
    sampleSolution: "SELECT user_id, MIN(event_time) AS first_event, MAX(event_time) AS last_event, dateDiff('day', MIN(event_time), MAX(event_time)) AS days_span FROM events GROUP BY user_id ORDER BY user_id;",
    verificationQuery: 'SELECT COUNT(*) as count FROM events;',
  },

  {
    id: 'ch-38',
    title: 'ClickHouse: formatDateTime для красивых дат',
    description: 'Форматирование даты и времени события',
    difficulty: 'beginner',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: CLICKHOUSE_EVENTS_SCHEMA,
    taskText: 'Выведите события с форматированной датой: id, event_type и formatted_time в формате \'DD.MM.YYYY HH:MM\'. Используйте formatDateTime(event_time, \'%d.%m.%Y %H:%i\'). Отсортируйте по event_time.',
    hint: 'formatDateTime(date, format) форматирует DateTime по шаблону. %d — день, %m — месяц, %Y — год, %H — часы, %i — минуты.',
    sampleSolution: "SELECT id, event_type, formatDateTime(event_time, '%d.%m.%Y %H:%i') AS formatted_time FROM events ORDER BY event_time;",
    verificationQuery: 'SELECT COUNT(*) as count FROM events;',
  },

  {
    id: 'ch-39',
    title: 'ClickHouse: uniqExact vs COUNT DISTINCT',
    description: 'Подсчёт уникальных пользователей за день',
    difficulty: 'intermediate',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: CLICKHOUSE_EVENTS_SCHEMA,
    taskText: 'Для каждого дня подсчитайте количество уникальных пользователей двумя способами: uniqExact(user_id) и COUNT(DISTINCT user_id). Выведите event_date, unique_exact и unique_countd. uniqExact точнее, но медленнее. Отсортируйте по event_date.',
    hint: 'uniqExact() считает уникальные значения точно (используя хеш-таблицу). COUNT(DISTINCT) в ClickHouse может быть приблизительным. Для маленьких данных результат одинаков.',
    sampleSolution: 'SELECT toDate(event_time) AS event_date, uniqExact(user_id) AS unique_exact, count(DISTINCT user_id) AS unique_countd FROM events GROUP BY event_date ORDER BY event_date;',
    verificationQuery: 'SELECT COUNT(*) as count FROM events;',
  },

  {
    id: 'ch-4',
    title: 'groupArray — массивы из групп',
    description: 'Create arrays from groups with groupArray',
    difficulty: 'intermediate',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: CLICKHOUSE_EVENTS_SCHEMA,
    taskText: 'Для каждого пользователя соберите уникальные посещённые страницы (page) в массив. Используйте groupArray(DISTINCT page). Выведите user_id и visited_pages.',
    hint: 'groupArray(expr) creates an array from all values in the group.',
    sampleSolution: 'SELECT user_id, groupArray(DISTINCT page) as visited_pages FROM events GROUP BY user_id ORDER BY user_id;',
    verificationQuery: 'SELECT 1 as count;',
  },

  {
    id: 'ch-42',
    title: 'ClickHouse: sumIf + toStartOfDay',
    description: 'Ежедневная аналитика просмотров страниц',
    difficulty: 'advanced',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: CLICKHOUSE_EVENTS_SCHEMA,
    taskText: 'Для каждого дня вычислите общую длительность page_view событий и количество кликов. Используйте toStartOfDay(event_time) для группировки по дням, sumIf(duration, event_type = \'page_view\') для суммы длительности и countIf(event_type = \'click\') для подсчёта кликов. Выведите day, total_view_duration, click_count. Отсортируйте по day.',
    hint: 'toStartOfDay(datetime) округляет до начала дня. sumIf() и countIf() — условные агрегатные функции ClickHouse.',
    sampleSolution: "SELECT toStartOfDay(event_time) AS day, sumIf(duration, event_type = 'page_view') AS total_view_duration, countIf(event_type = 'click') AS click_count FROM events GROUP BY day ORDER BY day;",
    verificationQuery: 'SELECT COUNT(*) as count FROM events;',
  },

  {
    id: 'ch-45',
    title: 'ClickHouse: условная агрегация countIf',
    description: 'Отношение кликов к просмотрам (CTR) по дням',
    difficulty: 'advanced',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: CLICKHOUSE_EVENTS_SCHEMA,
    taskText: 'Для каждого дня вычислите CTR (Click-Through Rate) — отношение количества кликов к количеству просмотров. Используйте countIf для подсчёта каждого типа. Выведите event_date, page_views, clicks и ctr (округлите до 3 знаков). Избегайте деления на ноль через NULLIF. Отсортируйте по event_date.',
    hint: 'CTR = clicks / page_views. NULLIF(page_views, 0) предотвращает деление на ноль, возвращая NULL. ROUND(..., 3) округляет до 3 знаков.',
    sampleSolution: "SELECT toDate(event_time) AS event_date, countIf(event_type = 'page_view') AS page_views, countIf(event_type = 'click') AS clicks, ROUND(countIf(event_type = 'click') / NULLIF(countIf(event_type = 'page_view'), 0), 3) AS ctr FROM events GROUP BY event_date ORDER BY event_date;",
    verificationQuery: 'SELECT COUNT(*) as count FROM events;',
  },

  {
    id: 'ch-46',
    title: 'ClickHouse: has() для поиска в массиве',
    description: 'Пользователи, посещавшие определённую страницу',
    difficulty: 'intermediate',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: CLICKHOUSE_EVENTS_SCHEMA,
    taskText: 'Найдите пользователей, которые посещали страницу \'/home\'. Используйте подзапрос: сначала соберите посещённые страницы каждого пользователя в массив через groupArray(DISTINCT page), затем отфильтруйте с помощью has(visited_pages, \'/home\'). Выведите user_id и visited_pages. Отсортируйте по user_id.',
    hint: 'has(array, value) возвращает 1, если массив содержит значение, и 0 иначе. Работает с массивами, созданными groupArray.',
    sampleSolution: "SELECT user_id, groupArray(DISTINCT page) AS visited_pages FROM events GROUP BY user_id HAVING has(groupArray(DISTINCT page), '/home') ORDER BY user_id;",
    verificationQuery: 'SELECT COUNT(*) as count FROM events;',
  },

  {
    id: 'ch-5',
    title: 'multiIf — множественное условие',
    description: 'Multiple conditions with multiIf',
    difficulty: 'intermediate',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: CLICKHOUSE_EVENTS_SCHEMA,
    taskText: 'Классифицируйте пользователей по возрастным группам: «молодой» (до 25), «средний» (25-34), «опытный» (35-44), «старший» (45+). Используйте multiIf(). Выведите username, age и age_group.',
    hint: 'multiIf(cond1, val1, cond2, val2, ..., elseVal) evaluates conditions sequentially.',
    sampleSolution: "SELECT username, age, multiIf(age < 25, 'молодой', age < 35, 'средний', age < 45, 'опытный', 'старший') as age_group FROM users ORDER BY age;",
    verificationQuery: 'SELECT COUNT(*) as count FROM users;',
  },

  {
    id: 'ch-6',
    title: 'formatDateTime — форматирование дат',
    description: 'Date formatting with formatDateTime',
    difficulty: 'intermediate',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: CLICKHOUSE_EVENTS_SCHEMA,
    taskText: 'Сгруппируйте события по часам. Используйте formatDateTime(event_time, \'%Y-%m-%d %H:00\') для группировки. Выведите event_time, hour_bucket и количество событий (events_count).',
    hint: 'formatDateTime(date, format) formats dates using strftime-style patterns.',
    sampleSolution: "SELECT event_time, formatDateTime(event_time, '%Y-%m-%d %H:00') as hour_bucket, COUNT() as events_count FROM events GROUP BY event_time, hour_bucket ORDER BY event_time;",
    verificationQuery: 'SELECT 1 as count;',
  },

  {
    id: 'ch-advanced-1',
    title: 'Вложенные подзапросы',
    description: 'Подзапросы с агрегацией',
    difficulty: 'advanced',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Найдите пользователей, которые потратили больше средней суммы покупок. Выведите имя пользователя и общую сумму.',
    hint: 'Подзапрос: SELECT avg(total) FROM (SELECT user_id, sum(amount) as total FROM purchases WHERE status = \'completed\' GROUP BY user_id).',
    sampleSolution: "SELECT u.username, sum(p.amount) as total_spent FROM users u JOIN purchases p ON u.user_id = p.user_id WHERE p.status = 'completed' GROUP BY u.user_id, u.username HAVING sum(p.amount) > (SELECT avg(total) FROM (SELECT user_id, sum(amount) as total FROM purchases WHERE status = 'completed' GROUP BY user_id)) ORDER BY total_spent DESC;",
    verificationQuery: "SELECT COUNT(*) as count FROM (SELECT user_id, sum(amount) as total FROM purchases WHERE status = 'completed' GROUP BY user_id HAVING total > (SELECT avg(total) FROM (SELECT user_id, sum(amount) as total FROM purchases WHERE status = 'completed' GROUP BY user_id)));",
  },

  {
    id: 'ch-advanced-2',
    title: 'uniqExact и toYYYYMM',
    description: 'Уникальные значения и форматирование дат',
    difficulty: 'advanced',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Для каждого месяца посчитайте количество уникальных пользователей, совершивших покупки. Используйте uniqExact и toYYYYMM.',
    hint: 'uniqExact(user_id) считает уникальные значения. toYYYYMM(purchase_date) форматирует дату.',
    sampleSolution: "SELECT toYYYYMM(purchase_date) as month, uniqExact(user_id) as unique_buyers, count(*) as total_purchases, sum(amount) as revenue FROM purchases WHERE status = 'completed' GROUP BY month ORDER BY month;",
    verificationQuery: "SELECT COUNT(DISTINCT toYYYYMM(purchase_date)) as months FROM purchases WHERE status = 'completed';",
  },

  {
    id: 'ch-advanced-3',
    title: 'if и условные выражения',
    description: 'Функция if в SELECT',
    difficulty: 'advanced',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Для каждого устройства посчитайте количество кликов и просмотров, а также конверсию (клики / просмотры * 100). Используйте if.',
    hint: 'if(event_type = \'click\', 1, 0) вернёт 1 для кликов и 0 для остальных.',
    sampleSolution: "SELECT device, sum(if(event_type = 'click', 1, 0)) as clicks, sum(if(event_type = 'page_view', 1, 0)) as views, round(sum(if(event_type = 'click', 1, 0)) * 100.0 / sum(if(event_type = 'page_view', 1, 0)), 2) as ctr FROM events GROUP BY device ORDER BY ctr DESC;",
    verificationQuery: 'SELECT COUNT(DISTINCT device) as devices FROM events;',
  },

  {
    id: 'ch-analytics-adv-1',
    title: 'ClickHouse: Воронка конверсии по страницам',
    description: 'Анализ воронки событий: от просмотра курсов до покупки',
    difficulty: 'advanced',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: SHOP_SCHEMA,
    taskText: 'Создайте воронку конверсии для таблицы orders. Посчитайте количество заказов для каждого статуса (new, processing, shipped, delivered, cancelled) в порядке жизненного цикла. Используйте countIf для каждого статуса в одном запросе.',
    hint: 'countIf(cond) считает строки, удовлетворяющие условию. Используйте один SELECT с несколькими countIf для каждого статуса.',
    sampleSolution: "SELECT countIf(status = 'new') AS new_orders, countIf(status = 'processing') AS processing_orders, countIf(status = 'shipped') AS shipped_orders, countIf(status = 'delivered') AS delivered_orders, countIf(status = 'cancelled') AS cancelled_orders FROM orders;",
    verificationQuery: "SELECT count(*) as count FROM orders WHERE status = 'delivered';",
  },

  {
    id: 'ch-analytics-adv-2',
    title: 'ClickHouse: Выручка с применением multiIf',
    description: 'Классификация заказов по сумме с помощью multiIf',
    difficulty: 'advanced',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: SHOP_SCHEMA,
    taskText: 'Для каждого заказа из таблицы orders создайте категорию на основе total_amount: "Мелкий" (< 5000), "Средний" (5000-10000), "Крупный" (10001-50000), "Премиум" (> 50000). Выведите id заказа, total_amount и категорию. Используйте multiIf.',
    hint: 'multiIf(cond1, val1, cond2, val2, ..., elseVal) работает как цепочка CASE WHEN. Порядок условий важен — от самого специфичного к общему.',
    sampleSolution: "SELECT id, total_amount, multiIf(total_amount < 5000, 'Мелкий', total_amount <= 10000, 'Средний', total_amount <= 50000, 'Крупный', 'Премиум') AS order_category FROM orders ORDER BY total_amount DESC;",
    verificationQuery: "SELECT COUNT(*) as count FROM orders WHERE total_amount > 50000;",
  },

  {
    id: 'ch-analytics-adv-3',
    title: 'ClickHouse: Топ-N с bar-визуализацией',
    description: 'Текстовая визуализация данных с помощью bar()',
    difficulty: 'advanced',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: SHOP_SCHEMA,
    taskText: 'Выведите топ-5 товаров по цене из таблицы products. Для каждого товара покажите name, price и визуальную шкалу с помощью bar(price, 70000, 20). Отсортируйте по цене DESC, ограничьте 5.',
    hint: 'bar(value, max_value, width) создаёт текстовую шкалу из символов █. max_value — это значение, соответствующее полной шкале.',
    sampleSolution: 'SELECT name, price, bar(price, 70000, 20) AS price_bar FROM products ORDER BY price DESC LIMIT 5;',
    verificationQuery: 'SELECT COUNT(*) as count FROM products WHERE price > 10000;',
  },

  {
    id: 'ch-analytics-adv-4',
    title: 'ClickHouse: Агрегация по неделям',
    description: 'Группировка данных по неделям',
    difficulty: 'advanced',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: SHOP_SCHEMA,
    taskText: 'Из таблицы orders посчитайте количество заказов и сумму total_amount для каждого месяца. Используйте toStartOfMonth(order_date) для группировки. Выведите месяц, кол-во заказов и суммарную выручку. Отсортируйте по месяцу.',
    hint: 'toStartOfMonth(date) округляет дату до начала месяца. Используйте SUM и COUNT вместе с GROUP BY.',
    sampleSolution: 'SELECT toStartOfMonth(order_date) AS month, COUNT(*) AS order_count, SUM(total_amount) AS revenue FROM orders GROUP BY month ORDER BY month;',
    verificationQuery: 'SELECT COUNT(DISTINCT SUBSTR(order_date, 1, 7)) as count FROM orders;',
  },

  {
    id: 'ch-beginner-1',
    title: 'Базовый SELECT',
    description: 'Выбрать данные из таблицы',
    difficulty: 'beginner',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Выведите все события из таблицы events (первые 10).',
    hint: 'Используйте SELECT * FROM events LIMIT 10.',
    sampleSolution: 'SELECT * FROM events LIMIT 10;',
    verificationQuery: 'SELECT COUNT(*) as count FROM events;',
  },

  {
    id: 'ch-beginner-2',
    title: 'toDate и toDateTime',
    description: 'Работа с функциями дат',
    difficulty: 'beginner',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Выведите user_id, event_type и дату события (только дата, без времени) для всех событий. Используйте toDate().',
    hint: 'toDate(event_time) преобразует DateTime в дату.',
    sampleSolution: 'SELECT user_id, event_type, toDate(event_time) as event_date FROM events LIMIT 20;',
    verificationQuery: 'SELECT COUNT(*) as count FROM events;',
  },

  {
    id: 'ch-beginner-3',
    title: 'Фильтрация WHERE',
    description: 'Фильтрация с условиями',
    difficulty: 'beginner',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Найдите все события с device = "mobile". Выведите event_id, user_id, event_type.',
    hint: 'Используйте WHERE device = \'mobile\'.',
    sampleSolution: "SELECT event_id, user_id, event_type FROM events WHERE device = 'mobile';",
    verificationQuery: "SELECT COUNT(*) as count FROM events WHERE device = 'mobile';",
  },

  {
    id: 'ch-intermediate-1',
    title: 'sumIf и countIf',
    description: 'Условные агрегации',
    difficulty: 'intermediate',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Для каждого пользователя (users) выведите имя, общее количество покупок и общую сумму только завершённых покупок (purchases, status = \'completed\').',
    hint: 'Используйте sumIf(amount, status = \'completed\') и countIf(status = \'completed\').',
    sampleSolution: "SELECT u.username, countIf(p.status = 'completed') as completed_count, sumIf(p.amount, p.status = 'completed') as total_spent FROM users u LEFT JOIN purchases p ON u.user_id = p.user_id GROUP BY u.user_id, u.username ORDER BY total_spent DESC;",
    verificationQuery: 'SELECT COUNT(*) as count FROM users;',
  },

  {
    id: 'ch-intermediate-2',
    title: 'toStartOfMonth',
    description: 'Группировка по месяцам',
    difficulty: 'intermediate',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Посчитайте количество покупок и общую сумму по месяцам (таблица purchases). Используйте toStartOfMonth.',
    hint: 'toStartOfMonth(purchase_date) вернёт начало месяца для группировки.',
    sampleSolution: 'SELECT toStartOfMonth(purchase_date) as month, count(*) as purchase_count, sum(amount) as total_amount FROM purchases GROUP BY month ORDER BY month;',
    verificationQuery: 'SELECT COUNT(DISTINCT toStartOfMonth(purchase_date)) as months FROM purchases;',
  },

  {
    id: 'ch-intermediate-3',
    title: 'avgIf',
    description: 'Условное среднее',
    difficulty: 'intermediate',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Найдите среднюю длительность (duration) только для событий page_view, сгруппированных по device.',
    hint: 'avgIf(duration, event_type = \'page_view\')',
    sampleSolution: "SELECT device, avgIf(duration, event_type = 'page_view') as avg_duration FROM events WHERE event_type = 'page_view' GROUP BY device ORDER BY avg_duration DESC;",
    verificationQuery: "SELECT COUNT(DISTINCT device) as devices FROM events WHERE event_type = 'page_view';",
  },

  {
    id: 'ch-intermediate-4',
    title: 'multiIf',
    description: 'Множественное условие',
    difficulty: 'intermediate',
    dbType: 'clickhouse',
    category: 'analytics',
    schema: ANALYTICS_SCHEMA,
    taskText: 'Классифицируйте пользователей по возрасту: "молодой" (<25), "средний" (25-34), "старший" (>=35). Выведите имя, возраст и категорию.',
    hint: 'multiIf(age < 25, \'молодой\', age <= 34, \'средний\', \'старший\')',
    sampleSolution: "SELECT username, age, multiIf(age < 25, 'молодой', age <= 34, 'средний', 'старший') as age_category FROM users ORDER BY age;",
    verificationQuery: 'SELECT COUNT(*) as count FROM users;',
  },


  // ==================== EXAM TASKS ====================
  {
    id: 'ch-exam-1',
    title: 'Экзамен ClickHouse: toStartOfMonth',
    description: 'Количество сотрудников по месяцу найма',
    difficulty: 'beginner',
    dbType: 'clickhouse',
    category: 'exam',
    examGroup: 'ch-exam-beginner',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Сгруппируйте сотрудников по месяцу найма с помощью toStartOfMonth(toDate(hire_date)). Выведите hire_month и emp_count. Отсортируйте по hire_month.',
    hint: 'toStartOfMonth(date) приводит дату к первому дню месяца. Удобно для помесячной группировки.',
    sampleSolution: 'SELECT toStartOfMonth(toDate(hire_date)) AS hire_month, COUNT(*) AS emp_count FROM employees GROUP BY hire_month ORDER BY hire_month;',
    verificationQuery: 'SELECT COUNT(*) as count FROM employees;',
  },

  {
    id: 'ch-exam-2',
    title: 'Экзамен ClickHouse: if() для категоризации',
    description: 'Категоризация зарплат с помощью if()',
    difficulty: 'beginner',
    dbType: 'clickhouse',
    category: 'exam',
    examGroup: 'ch-exam-beginner',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Для каждого сотрудника определите категорию зарплаты с помощью вложенных if(): «низкая» (< 110000), «средняя» (110000–140000), «высокая» (> 140000). Выведите first_name, last_name, salary и salary_category. Отсортируйте по salary DESC.',
    hint: 'if(condition, then, else) — условное выражение. Для множественных условий вкладывайте: if(c1, v1, if(c2, v2, else)). Или используйте multiIf.',
    sampleSolution: "SELECT first_name, last_name, salary, if(salary < 110000, 'низкая', if(salary < 140000, 'средняя', 'высокая')) AS salary_category FROM employees ORDER BY salary DESC;",
    verificationQuery: 'SELECT COUNT(*) as count FROM employees;',
  },

  {
    id: 'ch-exam-3',
    title: 'Экзамен ClickHouse: formatDateTime',
    description: 'Форматирование даты найма',
    difficulty: 'beginner',
    dbType: 'clickhouse',
    category: 'exam',
    examGroup: 'ch-exam-beginner',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Выведите сотрудников: first_name, last_name и formatted_date — hire_date в формате \'YYYY-MM-DD\'. Используйте formatDateTime(toDateTime(hire_date), \'%Y-%m-%d\'). Отсортируйте по hire_date.',
    hint: 'formatDateTime(datetime, format) форматирует DateTime. %Y — 4-значный год, %m — месяц (01-12), %d — день (01-31).',
    sampleSolution: "SELECT first_name, last_name, formatDateTime(toDateTime(hire_date), '%Y-%m-%d') AS formatted_date FROM employees ORDER BY hire_date;",
    verificationQuery: 'SELECT COUNT(*) as count FROM employees;',
  },

  {
    id: 'ch-exam-4',
    title: 'Экзамен ClickHouse: sumIf для проектных часов',
    description: 'Часы ведущих разработчиков по проектам',
    difficulty: 'intermediate',
    dbType: 'clickhouse',
    category: 'exam',
    examGroup: 'ch-exam-intermediate',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Для каждого проекта вычислите: часы ведущих разработчиков (sumIf(hours_worked, role = \'Ведущий разработчик\')) и общие часы. Используйте таблицу assignments. Выведите project_id, lead_hours и total_hours. Отсортируйте по project_id.',
    hint: 'sumIf(expr, condition) суммирует expr только для строк, где condition = true. Это компактнее, чем CASE WHEN внутри SUM.',
    sampleSolution: "SELECT project_id, sumIf(hours_worked, role = 'Ведущий разработчик') AS lead_hours, SUM(hours_worked) AS total_hours FROM assignments GROUP BY project_id ORDER BY project_id;",
    verificationQuery: 'SELECT COUNT(*) as count FROM assignments;',
  },

  {
    id: 'ch-exam-5',
    title: 'Экзамен ClickHouse: groupArray',
    description: 'Список сотрудников по отделам',
    difficulty: 'intermediate',
    dbType: 'clickhouse',
    category: 'exam',
    examGroup: 'ch-exam-intermediate',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Для каждого отдела соберите имена сотрудников в массив. Используйте groupArray(first_name || \' \' || last_name). Выведите department и employees (массив). Отсортируйте по department.',
    hint: 'groupArray(expr) создаёт массив из значений expr в каждой группе. Порядок элементов не гарантируется. Для уникальных значений используйте groupUniqArray.',
    sampleSolution: "SELECT d.name AS department, groupArray(e.first_name || ' ' || e.last_name) AS employees FROM departments d JOIN employees e ON d.id = e.department_id GROUP BY d.name ORDER BY d.name;",
    verificationQuery: 'SELECT COUNT(*) as count FROM departments;',
  },

  {
    id: 'ch-exam-6',
    title: 'Экзамен ClickHouse: multiIf для зарплатных групп',
    description: 'Зарплатные группы с помощью multiIf',
    difficulty: 'intermediate',
    dbType: 'clickhouse',
    category: 'exam',
    examGroup: 'ch-exam-intermediate',
    schema: EMPLOYEES_SCHEMA,
    taskText: 'Разбейте сотрудников на зарплатные группы с помощью multiIf: A (< 100K), B (100K–120K), C (120K–140K), D (140K–160K), E (160K+). Выведите first_name, last_name, salary и bracket. Отсортируйте по salary.',
    hint: 'multiIf(cond1, val1, cond2, val2, ..., elseVal) — цепочка условий. Удобнее вложенных if(). Условия проверяются последовательно.',
    sampleSolution: "SELECT first_name, last_name, salary, multiIf(salary < 100000, 'A', salary < 120000, 'B', salary < 140000, 'C', salary < 160000, 'D', 'E') AS bracket FROM employees ORDER BY salary;",
    verificationQuery: 'SELECT COUNT(*) as count FROM employees;',
  },

  {
    id: 'ch-exam-7',
    title: 'Экзамен ClickHouse: countIf + avgIf для отзывов',
    description: 'Анализ отзывов по категориям товаров',
    difficulty: 'advanced',
    dbType: 'clickhouse',
    category: 'exam',
    examGroup: 'ch-exam-advanced',
    schema: SHOP_SCHEMA,
    taskText: 'Для каждой категории товаров вычислите: количество хороших отзывов (рейтинг >= 4) через countIf, средний рейтинг через avgIf. Объедините reviews с products по product_id, затем с categories. Выведите category, good_reviews и avg_rating (округлите до 2). Отсортируйте по avg_rating DESC.',
    hint: 'countIf(condition) считает строки по условию. avgIf(expr, condition) считает среднее по условию. Условия могут ссылаться на разные столбцы.',
    sampleSolution: "SELECT c.name AS category, countIf(r.rating >= 4) AS good_reviews, ROUND(avgIf(r.rating, r.rating > 0), 2) AS avg_rating FROM categories c JOIN products p ON c.id = p.category_id JOIN reviews r ON p.id = r.product_id GROUP BY c.name ORDER BY avg_rating DESC;",
    verificationQuery: 'SELECT COUNT(*) as count FROM categories WHERE (SELECT COUNT(*) FROM products p JOIN reviews r ON p.id = r.product_id WHERE p.category_id = categories.id) > 0;',
  },

  {
    id: 'ch-exam-8',
    title: 'Экзамен ClickHouse: toStartOfDay + countIf',
    description: 'Ежедневный анализ заказов',
    difficulty: 'advanced',
    dbType: 'clickhouse',
    category: 'exam',
    examGroup: 'ch-exam-advanced',
    schema: SHOP_SCHEMA,
    taskText: 'Для каждого дня проанализируйте заказы: количество доставленных (countIf(status = \'delivered\')), отменённых (countIf(status = \'cancelled\')) и новых (countIf(status = \'new\')). Используйте toStartOfDay(toDateTime(order_date)) для группировки. Выведите order_day, delivered, cancelled и new_orders. Отсортируйте по order_day.',
    hint: 'toStartOfDay(datetime) округляет до начала дня. countIf(condition) считает строки, удовлетворяющие условию, внутри группы.',
    sampleSolution: "SELECT toStartOfDay(toDateTime(order_date)) AS order_day, countIf(status = 'delivered') AS delivered, countIf(status = 'cancelled') AS cancelled, countIf(status = 'new') AS new_orders FROM orders GROUP BY order_day ORDER BY order_day;",
    verificationQuery: 'SELECT COUNT(*) as count FROM orders;',
  },

  {
    id: 'ch-exam-9',
    title: 'Экзамен ClickHouse: uniqExact + groupUniqArray',
    description: 'Уникальные клиенты по городам доставки',
    difficulty: 'advanced',
    dbType: 'clickhouse',
    category: 'exam',
    examGroup: 'ch-exam-advanced',
    schema: SHOP_SCHEMA,
    taskText: 'Для каждого города доставки выведите: количество уникальных клиентов (uniqExact(customer_id)), массив уникальных id клиентов (groupUniqArray(customer_id)) и общее количество заказов. Используйте таблицу orders. Отсортируйте по unique_customers DESC.',
    hint: 'uniqExact(expr) считает точное количество уникальных значений (используя хеш-таблицу). groupUniqArray(expr) собирает уникальные значения в массив.',
    sampleSolution: 'SELECT shipping_city, uniqExact(customer_id) AS unique_customers, groupUniqArray(customer_id) AS customer_list, COUNT(*) AS total_orders FROM orders GROUP BY shipping_city ORDER BY unique_customers DESC;',
    verificationQuery: 'SELECT COUNT(DISTINCT shipping_city) as count FROM orders;',
  },

];
