/**
 * MongoDB Task Definitions
 * Training tasks for MongoDB query language (find, aggregate).
 */

import type { TrainingTask } from './types';

// MongoDB schema as JSON data for in-memory execution
const MONGODB_USERS_SCHEMA = JSON.stringify({
  users: [
    {
      _id: 1,
      name: 'Ivan Petrov',
      age: 30,
      city: 'Moscow',
      email: 'ivan@company.ru',
      role: 'developer',
      salary: 150000,
      skills: ['JavaScript', 'React', 'Node.js'],
    },
    {
      _id: 2,
      name: 'Maria Sidorova',
      age: 25,
      city: 'Saint Petersburg',
      email: 'maria@company.ru',
      role: 'developer',
      salary: 140000,
      skills: ['Python', 'Django', 'PostgreSQL'],
    },
    {
      _id: 3,
      name: 'Alexey Kozlov',
      age: 35,
      city: 'Moscow',
      email: 'alexey@company.ru',
      role: 'architect',
      salary: 160000,
      skills: ['Java', 'Spring', 'Microservices'],
    },
    {
      _id: 4,
      name: 'Elena Novikova',
      age: 28,
      city: 'Kazan',
      email: 'elena@company.ru',
      role: 'designer',
      salary: 120000,
      skills: ['Figma', 'UI/UX', 'Photoshop'],
    },
    {
      _id: 5,
      name: 'Dmitry Volkov',
      age: 32,
      city: 'Moscow',
      email: 'dmitry@company.ru',
      role: 'developer',
      salary: 130000,
      skills: ['JavaScript', 'Vue.js', 'TypeScript'],
    },
    {
      _id: 6,
      name: 'Olga Morozova',
      age: 27,
      city: 'Novosibirsk',
      email: 'olga@company.ru',
      role: 'manager',
      salary: 140000,
      skills: ['Agile', 'Scrum', 'Jira'],
    },
    {
      _id: 7,
      name: 'Sergey Lebedev',
      age: 29,
      city: 'Yekaterinburg',
      email: 'sergey@company.ru',
      role: 'developer',
      salary: 125000,
      skills: ['Python', 'FastAPI', 'MongoDB'],
    },
    {
      _id: 8,
      name: 'Anna Sokolova',
      age: 24,
      city: 'Moscow',
      email: 'anna@company.ru',
      role: 'junior',
      salary: 90000,
      skills: ['HTML', 'CSS', 'JavaScript'],
    },
    {
      _id: 9,
      name: 'Nikolay Kuznetsov',
      age: 40,
      city: 'Saint Petersburg',
      email: 'nikolay@company.ru',
      role: 'lead',
      salary: 180000,
      skills: ['Go', 'Kubernetes', 'Docker'],
    },
    {
      _id: 10,
      name: 'Victoria Popova',
      age: 31,
      city: 'Kazan',
      email: 'victoria@company.ru',
      role: 'developer',
      salary: 135000,
      skills: ['Java', 'Spring', 'React'],
    },
  ],
  products: [
    {
      _id: 1,
      name: 'ProBook Laptop',
      category: 'electronics',
      price: 89990,
      stock: 15,
      tags: ['computer', 'laptop', 'work'],
    },
    {
      _id: 2,
      name: 'Wireless Mouse',
      category: 'electronics',
      price: 2990,
      stock: 100,
      tags: ['accessory', 'wireless'],
    },
    {
      _id: 3,
      name: 'Mechanical Keyboard',
      category: 'electronics',
      price: 7990,
      stock: 50,
      tags: ['accessory', 'mechanical'],
    },
    { _id: 4, name: '27" Monitor', category: 'electronics', price: 35990, stock: 20, tags: ['display', 'monitor'] },
    { _id: 5, name: 'Pro Headphones', category: 'electronics', price: 12990, stock: 30, tags: ['audio', 'headphones'] },
    { _id: 6, name: 'Laptop Backpack', category: 'accessories', price: 3990, stock: 40, tags: ['bag', 'laptop'] },
    { _id: 7, name: 'USB-C Hub', category: 'accessories', price: 4990, stock: 60, tags: ['adapter', 'usb'] },
    { _id: 8, name: 'HD Webcam', category: 'electronics', price: 5990, stock: 25, tags: ['camera', 'video'] },
  ],
  orders: [
    { _id: 1, userId: 1, productId: 1, quantity: 1, total: 89990, status: 'delivered', date: '2024-01-15' },
    { _id: 2, userId: 2, productId: 2, quantity: 2, total: 5980, status: 'delivered', date: '2024-01-20' },
    { _id: 3, userId: 3, productId: 3, quantity: 1, total: 7990, status: 'shipped', date: '2024-02-01' },
    { _id: 4, userId: 1, productId: 5, quantity: 1, total: 12990, status: 'delivered', date: '2024-02-10' },
    { _id: 5, userId: 5, productId: 4, quantity: 1, total: 35990, status: 'pending', date: '2024-02-15' },
    { _id: 6, userId: 4, productId: 6, quantity: 2, total: 7980, status: 'delivered', date: '2024-02-20' },
    { _id: 7, userId: 6, productId: 7, quantity: 1, total: 4990, status: 'cancelled', date: '2024-03-01' },
    { _id: 8, userId: 3, productId: 1, quantity: 1, total: 89990, status: 'delivered', date: '2024-03-05' },
    { _id: 9, userId: 7, productId: 8, quantity: 1, total: 5990, status: 'delivered', date: '2024-03-10' },
    { _id: 10, userId: 9, productId: 4, quantity: 2, total: 71980, status: 'shipped', date: '2024-03-15' },
  ],
});

export const MONGODB_SCHEMA = MONGODB_USERS_SCHEMA;

export const MONGODB_TASKS: TrainingTask[] = [
  // ==================== MONGODB BASIC ====================
  {
    id: 'mongo-1',
    title: 'Basic find — all documents',
    description: 'Get all documents from collection',
    difficulty: 'beginner',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText: 'Get all users from the users collection. Use db.users.find({}).',
    hint: 'db.users.find({}) returns all documents from the collection.',
    sampleSolution: JSON.stringify({ find: 'users', query: {} }),
    verificationQuery: JSON.stringify({ count: 'users' }),
  },
  {
    id: 'mongo-2',
    title: 'find with filter',
    description: 'Filter documents by condition',
    difficulty: 'beginner',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText: 'Find all developers (role: "developer") from Moscow. Display name and email.',
    hint: 'Use { role: "developer", city: "Moscow" } as filter and projection to select fields.',
    sampleSolution: JSON.stringify({
      find: 'users',
      query: { role: 'developer', city: 'Moscow' },
      projection: { name: 1, email: 1 },
    }),
    verificationQuery: JSON.stringify({ count: 'users', filter: { role: 'developer', city: 'Moscow' } }),
  },
  {
    id: 'mongo-3',
    title: 'find with comparison operators',
    description: 'Using $gt, $lt, $gte, $lte',
    difficulty: 'beginner',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText: 'Find users older than 30 with salary above 140000.',
    hint: 'Use { age: { $gt: 30 }, salary: { $gt: 140000 } }.',
    sampleSolution: JSON.stringify({ find: 'users', query: { age: { $gt: 30 }, salary: { $gt: 140000 } } }),
    verificationQuery: JSON.stringify({ count: 'users', filter: { age: { $gt: 30 }, salary: { $gt: 140000 } } }),
  },
  {
    id: 'mongo-4',
    title: 'find with $in',
    description: 'Search by multiple values',
    difficulty: 'beginner',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText: 'Find users from Moscow or Saint Petersburg.',
    hint: 'Use { city: { $in: ["Moscow", "Saint Petersburg"] } }.',
    sampleSolution: JSON.stringify({ find: 'users', query: { city: { $in: ['Moscow', 'Saint Petersburg'] } } }),
    verificationQuery: JSON.stringify({ count: 'users', filter: { city: { $in: ['Moscow', 'Saint Petersburg'] } } }),
  },
  {
    id: 'mongo-5',
    title: 'find with $regex',
    description: 'Search with regular expression',
    difficulty: 'intermediate',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText: 'Find users whose last name contains "ov" or "ev".',
    hint: 'Use { name: { $regex: "(ov|ev)$" } }.',
    sampleSolution: JSON.stringify({ find: 'users', query: { name: { $regex: '(ov|ev)$' } } }),
    verificationQuery: JSON.stringify({ count: 'users', filter: { name: { $regex: '(ov|ev)$' } } }),
  },
  {
    id: 'mongo-6',
    title: 'find with sort and limit',
    description: 'Sorting and limiting results',
    difficulty: 'beginner',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText: 'Get the top 3 users by salary (descending). Display name and salary.',
    hint: 'Use sort: { salary: -1 } and limit: 3.',
    sampleSolution: JSON.stringify({
      find: 'users',
      query: {},
      sort: { salary: -1 },
      limit: 3,
      projection: { name: 1, salary: 1 },
    }),
    verificationQuery: JSON.stringify({ count: 'users', sort: { salary: -1 }, limit: 3 }),
  },
  {
    id: 'mongo-7',
    title: 'find with arrays — array search',
    description: 'Search documents by array value',
    difficulty: 'intermediate',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText: 'Find all users who have "JavaScript" in their skills.',
    hint: 'MongoDB automatically searches arrays: { skills: "JavaScript" }.',
    sampleSolution: JSON.stringify({ find: 'users', query: { skills: 'JavaScript' } }),
    verificationQuery: JSON.stringify({ count: 'users', filter: { skills: 'JavaScript' } }),
  },
  {
    id: 'mongo-8',
    title: 'find with $exists',
    description: 'Check field existence',
    difficulty: 'beginner',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText: 'Find all orders with status "delivered".',
    hint: 'Use { status: "delivered" } — if the field exists, the document will be returned.',
    sampleSolution: JSON.stringify({ find: 'orders', query: { status: 'delivered' } }),
    verificationQuery: JSON.stringify({ count: 'orders', filter: { status: 'delivered' } }),
  },

  // ==================== MONGODB AGGREGATE ====================
  {
    id: 'mongo-9',
    title: 'aggregate — $match + $group',
    description: 'Grouping with pre-filtering',
    difficulty: 'intermediate',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText: 'Count the number of users in each city. Use aggregate with $match (role: "developer") and $group.',
    hint: 'Pipeline: [{ $match: { role: "developer" } }, { $group: { _id: "$city", count: { $sum: 1 } } }].',
    sampleSolution: JSON.stringify({
      aggregate: 'users',
      pipeline: [{ $match: { role: 'developer' } }, { $group: { _id: '$city', count: { $sum: 1 } } }],
    }),
    verificationQuery: JSON.stringify({ count: 'users', filter: { role: 'developer' } }),
  },
  {
    id: 'mongo-10',
    title: 'aggregate — $group with $avg',
    description: 'Average value in grouping',
    difficulty: 'intermediate',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText: 'Calculate the average salary by each role. Display role and average salary.',
    hint: 'Use { $group: { _id: "$role", avgSalary: { $avg: "$salary" } } }.',
    sampleSolution: JSON.stringify({
      aggregate: 'users',
      pipeline: [{ $group: { _id: '$role', avgSalary: { $avg: '$salary' } } }],
    }),
    verificationQuery: JSON.stringify({ count: 'users' }),
  },
  {
    id: 'mongo-11',
    title: 'aggregate — $group with $sum',
    description: 'Sum in grouping',
    difficulty: 'intermediate',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText: 'Calculate the total order amount by each status. Display status and total amount.',
    hint: 'Use { $group: { _id: "$status", totalAmount: { $sum: "$total" } } }.',
    sampleSolution: JSON.stringify({
      aggregate: 'orders',
      pipeline: [{ $group: { _id: '$status', totalAmount: { $sum: '$total' } } }],
    }),
    verificationQuery: JSON.stringify({ count: 'orders' }),
  },
  {
    id: 'mongo-12',
    title: 'aggregate — $sort after $group',
    description: 'Sorting aggregation results',
    difficulty: 'intermediate',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText: 'Find the average salary by city and sort descending.',
    hint: 'Pipeline: [{ $group: { _id: "$city", avgSalary: { $avg: "$salary" } } }, { $sort: { avgSalary: -1 } }].',
    sampleSolution: JSON.stringify({
      aggregate: 'users',
      pipeline: [{ $group: { _id: '$city', avgSalary: { $avg: '$salary' } } }, { $sort: { avgSalary: -1 } }],
    }),
    verificationQuery: JSON.stringify({ count: 'users' }),
  },
  {
    id: 'mongo-13',
    title: 'aggregate — $match + $group + $sort',
    description: 'Combined aggregation',
    difficulty: 'advanced',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText:
      'Find products in category "electronics", group by category and calculate total value (price * stock). Sort descending.',
    hint: 'First $match, then $group with $sum to calculate totalValue.',
    sampleSolution: JSON.stringify({
      aggregate: 'products',
      pipeline: [
        { $match: { category: 'electronics' } },
        { $group: { _id: '$category', totalValue: { $sum: { $multiply: ['$price', '$stock'] } }, count: { $sum: 1 } } },
        { $sort: { totalValue: -1 } },
      ],
    }),
    verificationQuery: JSON.stringify({ count: 'products', filter: { category: 'electronics' } }),
  },
  {
    id: 'mongo-14',
    title: 'aggregate — $unwind',
    description: 'Unwinding arrays',
    difficulty: 'advanced',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText: 'Unwind the skills array for users. Each skill should be in a separate document with the user name.',
    hint: 'Use { $unwind: "$skills" }, then $project to display name and skill.',
    sampleSolution: JSON.stringify({
      aggregate: 'users',
      pipeline: [{ $unwind: '$skills' }, { $project: { _id: 0, name: 1, skill: '$skills' } }],
    }),
    verificationQuery: JSON.stringify({ count: 'users' }),
  },
  {
    id: 'mongo-15',
    title: 'aggregate — $lookup (join)',
    description: 'Joining collections',
    difficulty: 'advanced',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText: 'Join orders with users using $lookup. For each order show userId, total and user name.',
    hint: 'Use { $lookup: { from: "users", localField: "userId", foreignField: "_id", as: "user" } }.',
    sampleSolution: JSON.stringify({
      aggregate: 'orders',
      pipeline: [
        { $lookup: { from: 'users', localField: 'userId', foreignField: '_id', as: 'user' } },
        { $project: { userId: 1, total: 1, userName: { $arrayElemAt: ['$user.name', 0] } } },
      ],
    }),
    verificationQuery: JSON.stringify({ count: 'orders' }),
  },
  {
    id: 'mongo-16',
    title: 'aggregate — $project with computed fields',
    description: 'Creating new fields',
    difficulty: 'intermediate',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText: 'For each product display name, price and inStock field (true if stock > 20).',
    hint: 'Use { $project: { name: 1, price: 1, inStock: { $gt: ["$stock", 20] } } }.',
    sampleSolution: JSON.stringify({
      aggregate: 'products',
      pipeline: [{ $project: { name: 1, price: 1, inStock: { $gt: ['$stock', 20] } } }],
    }),
    verificationQuery: JSON.stringify({ count: 'products' }),
  },
  {
    id: 'mongo-17',
    title: 'find with $or',
    description: 'Logical OR in query',
    difficulty: 'intermediate',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText: 'Find users who live in Moscow OR have a salary above 160000.',
    hint: 'Use { $or: [{ city: "Moscow" }, { salary: { $gt: 160000 } }] }.',
    sampleSolution: JSON.stringify({
      find: 'users',
      query: { $or: [{ city: 'Moscow' }, { salary: { $gt: 160000 } }] },
    }),
    verificationQuery: JSON.stringify({
      count: 'users',
      filter: { $or: [{ city: 'Moscow' }, { salary: { $gt: 160000 } }] },
    }),
  },
  {
    id: 'mongo-18',
    title: 'aggregate — $count',
    description: 'Counting documents',
    difficulty: 'beginner',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText: 'Count the number of delivered orders (status: "delivered").',
    hint: 'Pipeline: [{ $match: { status: "delivered" } }, { $count: "deliveredCount" }].',
    sampleSolution: JSON.stringify({
      aggregate: 'orders',
      pipeline: [{ $match: { status: 'delivered' } }, { $count: 'deliveredCount' }],
    }),
    verificationQuery: JSON.stringify({ count: 'orders', filter: { status: 'delivered' } }),
  },
];
