/**
 * MongoDB Task Definitions
 * Training tasks for MongoDB query language (find, aggregate).
 */

import type { TrainingTask } from './types';

// MongoDB schema as JSON data for in-memory execution
const MONGODB_USERS_SCHEMA = JSON.stringify({
  users: [
    {
      _id: 1,
      name: 'Иван Петров',
      age: 30,
      city: 'Москва',
      email: 'ivan@company.ru',
      role: 'developer',
      salary: 150000,
      skills: ['JavaScript', 'React', 'Node.js'],
    },
    {
      _id: 2,
      name: 'Мария Сидорова',
      age: 25,
      city: 'Санкт-Петербург',
      email: 'maria@company.ru',
      role: 'developer',
      salary: 140000,
      skills: ['Python', 'Django', 'PostgreSQL'],
    },
    {
      _id: 3,
      name: 'Алексей Козлов',
      age: 35,
      city: 'Москва',
      email: 'alexey@company.ru',
      role: 'architect',
      salary: 160000,
      skills: ['Java', 'Spring', 'Microservices'],
    },
    {
      _id: 4,
      name: 'Елена Новикова',
      age: 28,
      city: 'Казань',
      email: 'elena@company.ru',
      role: 'designer',
      salary: 120000,
      skills: ['Figma', 'UI/UX', 'Photoshop'],
    },
    {
      _id: 5,
      name: 'Дмитрий Волков',
      age: 32,
      city: 'Москва',
      email: 'dmitry@company.ru',
      role: 'developer',
      salary: 130000,
      skills: ['JavaScript', 'Vue.js', 'TypeScript'],
    },
    {
      _id: 6,
      name: 'Ольга Морозова',
      age: 27,
      city: 'Новосибирск',
      email: 'olga@company.ru',
      role: 'manager',
      salary: 140000,
      skills: ['Agile', 'Scrum', 'Jira'],
    },
    {
      _id: 7,
      name: 'Сергей Лебедев',
      age: 29,
      city: 'Екатеринбург',
      email: 'sergey@company.ru',
      role: 'developer',
      salary: 125000,
      skills: ['Python', 'FastAPI', 'MongoDB'],
    },
    {
      _id: 8,
      name: 'Анна Соколова',
      age: 24,
      city: 'Москва',
      email: 'anna@company.ru',
      role: 'junior',
      salary: 90000,
      skills: ['HTML', 'CSS', 'JavaScript'],
    },
    {
      _id: 9,
      name: 'Николай Кузнецов',
      age: 40,
      city: 'Санкт-Петербург',
      email: 'nikolay@company.ru',
      role: 'lead',
      salary: 180000,
      skills: ['Go', 'Kubernetes', 'Docker'],
    },
    {
      _id: 10,
      name: 'Виктория Попова',
      age: 31,
      city: 'Казань',
      email: 'victoria@company.ru',
      role: 'developer',
      salary: 135000,
      skills: ['Java', 'Spring', 'React'],
    },
  ],
  products: [
    {
      _id: 1,
      name: 'Ноутбук ProBook',
      category: 'electronics',
      price: 89990,
      stock: 15,
      tags: ['computer', 'laptop', 'work'],
    },
    {
      _id: 2,
      name: 'Мышь Wireless',
      category: 'electronics',
      price: 2990,
      stock: 100,
      tags: ['accessory', 'wireless'],
    },
    {
      _id: 3,
      name: 'Клавиатура Mechanical',
      category: 'electronics',
      price: 7990,
      stock: 50,
      tags: ['accessory', 'mechanical'],
    },
    { _id: 4, name: 'Монитор 27"', category: 'electronics', price: 35990, stock: 20, tags: ['display', 'monitor'] },
    { _id: 5, name: 'Наушники Pro', category: 'electronics', price: 12990, stock: 30, tags: ['audio', 'headphones'] },
    { _id: 6, name: 'Рюкзак для ноутбука', category: 'accessories', price: 3990, stock: 40, tags: ['bag', 'laptop'] },
    { _id: 7, name: 'USB-C Hub', category: 'accessories', price: 4990, stock: 60, tags: ['adapter', 'usb'] },
    { _id: 8, name: 'Веб-камера HD', category: 'electronics', price: 5990, stock: 25, tags: ['camera', 'video'] },
  ],
  orders: [
    { _id: 1, userId: 1, productId: 1, quantity: 1, total: 89990, status: 'delivered', date: '2024-01-15' },
    { _id: 2, userId: 2, productId: 2, quantity: 2, total: 5980, status: 'delivered', date: '2024-01-20' },
    { _id: 3, userId: 3, productId: 3, quantity: 1, total: 7990, status: 'shipped', date: '2024-02-01' },
    { _id: 4, userId: 1, productId: 5, quantity: 1, total: 12990, status: 'delivered', date: '2024-02-10' },
    { _id: 5, userId: 5, productId: 4, quantity: 1, total: 35990, status: 'pending', date: '2024-02-15' },
    { _id: 6, userId: 4, productId: 6, quantity: 2, total: 7980, status: 'delivered', date: '2024-02-20' },
    { _id: 7, userId: 6, productId: 7, quantity: 1, total: 4990, status: 'cancelled', date: '2024-03-01' },
    { _id: 8, userId: 3, productId: 1, quantity: 1, total: 89990, status: 'delivered', date: '2024-03-05' },
    { _id: 9, userId: 7, productId: 8, quantity: 1, total: 5990, status: 'delivered', date: '2024-03-10' },
    { _id: 10, userId: 9, productId: 4, quantity: 2, total: 71980, status: 'shipped', date: '2024-03-15' },
  ],
});

export const MONGODB_SCHEMA = MONGODB_USERS_SCHEMA;

export const MONGODB_TASKS: TrainingTask[] = [
  // ==================== MONGODB BASIC ====================
  {
    id: 'mongo-1',
    title: 'Базовый find — все документы',
    description: 'Получить все документы из коллекции',
    difficulty: 'beginner',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText: 'Получите всех пользователей из коллекции users. Используйте db.users.find({}).',
    hint: 'db.users.find({}) вернёт все документы из коллекции.',
    sampleSolution: JSON.stringify({ find: 'users', query: {} }),
    verificationQuery: JSON.stringify({ count: 'users' }),
  },
  {
    id: 'mongo-2',
    title: 'find с фильтром',
    description: 'Фильтрация документов по условию',
    difficulty: 'beginner',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText: 'Найдите всех разработчиков (role: "developer") из Москвы. Выведите имя и email.',
    hint: 'Используйте { role: "developer", city: "Москва" } как фильтр и projection для выбора полей.',
    sampleSolution: JSON.stringify({
      find: 'users',
      query: { role: 'developer', city: 'Москва' },
      projection: { name: 1, email: 1 },
    }),
    verificationQuery: JSON.stringify({ count: 'users', filter: { role: 'developer', city: 'Москва' } }),
  },
  {
    id: 'mongo-3',
    title: 'find с операторами сравнения',
    description: 'Использование $gt, $lt, $gte, $lte',
    difficulty: 'beginner',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText: 'Найдите пользователей старше 30 лет с зарплатой выше 140000.',
    hint: 'Используйте { age: { $gt: 30 }, salary: { $gt: 140000 } }.',
    sampleSolution: JSON.stringify({ find: 'users', query: { age: { $gt: 30 }, salary: { $gt: 140000 } } }),
    verificationQuery: JSON.stringify({ count: 'users', filter: { age: { $gt: 30 }, salary: { $gt: 140000 } } }),
  },
  {
    id: 'mongo-4',
    title: 'find с $in',
    description: 'Поиск по нескольким значениям',
    difficulty: 'beginner',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText: 'Найдите пользователей из Москвы или Санкт-Петербурга.',
    hint: 'Используйте { city: { $in: ["Москва", "Санкт-Петербург"] } }.',
    sampleSolution: JSON.stringify({ find: 'users', query: { city: { $in: ['Москва', 'Санкт-Петербург'] } } }),
    verificationQuery: JSON.stringify({ count: 'users', filter: { city: { $in: ['Москва', 'Санкт-Петербург'] } } }),
  },
  {
    id: 'mongo-5',
    title: 'find с $regex',
    description: 'Поиск по регулярному выражению',
    difficulty: 'intermediate',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText: 'Найдите пользователей у которых фамилия содержит "ов" или "ев".',
    hint: 'Используйте { name: { $regex: "(ов|ев)$" } }.',
    sampleSolution: JSON.stringify({ find: 'users', query: { name: { $regex: '(ов|ев)$' } } }),
    verificationQuery: JSON.stringify({ count: 'users', filter: { name: { $regex: '(ов|ев)$' } } }),
  },
  {
    id: 'mongo-6',
    title: 'find с sort и limit',
    description: 'Сортировка и ограничение результатов',
    difficulty: 'beginner',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText: 'Получите топ-3 пользователей по зарплате (по убыванию). Выведите имя и зарплату.',
    hint: 'Используйте sort: { salary: -1 } и limit: 3.',
    sampleSolution: JSON.stringify({
      find: 'users',
      query: {},
      sort: { salary: -1 },
      limit: 3,
      projection: { name: 1, salary: 1 },
    }),
    verificationQuery: JSON.stringify({ count: 'users', sort: { salary: -1 }, limit: 3 }),
  },
  {
    id: 'mongo-7',
    title: 'find с массивами — $in для массива',
    description: 'Поиск документов по значению в массиве',
    difficulty: 'intermediate',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText: 'Найдите всех пользователей у которых в навыках есть "JavaScript".',
    hint: 'MongoDB автоматически ищет в массивах: { skills: "JavaScript" }.',
    sampleSolution: JSON.stringify({ find: 'users', query: { skills: 'JavaScript' } }),
    verificationQuery: JSON.stringify({ count: 'users', filter: { skills: 'JavaScript' } }),
  },
  {
    id: 'mongo-8',
    title: 'find с $exists',
    description: 'Проверка наличия поля',
    difficulty: 'beginner',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText: 'Найдите все заказы со статусом "delivered" (существующие и доставленные).',
    hint: 'Используйте { status: "delivered" } — если поле существует, документ вернётся.',
    sampleSolution: JSON.stringify({ find: 'orders', query: { status: 'delivered' } }),
    verificationQuery: JSON.stringify({ count: 'orders', filter: { status: 'delivered' } }),
  },

  // ==================== MONGODB AGGREGATE ====================
  {
    id: 'mongo-9',
    title: 'aggregate — $match + $group',
    description: 'Группировка с предварительной фильтрацией',
    difficulty: 'intermediate',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText:
      'Подсчитайте количество пользователей в каждом городе. Используйте aggregate с $match (role: "developer") и $group.',
    hint: 'Pipeline: [{ $match: { role: "developer" } }, { $group: { _id: "$city", count: { $sum: 1 } } }].',
    sampleSolution: JSON.stringify({
      aggregate: 'users',
      pipeline: [{ $match: { role: 'developer' } }, { $group: { _id: '$city', count: { $sum: 1 } } }],
    }),
    verificationQuery: JSON.stringify({ count: 'users', filter: { role: 'developer' } }),
  },
  {
    id: 'mongo-10',
    title: 'aggregate — $group с $avg',
    description: 'Среднее значение в группировке',
    difficulty: 'intermediate',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText: 'Вычислите среднюю зарплату по каждой роли (role). Выведите роль и среднюю зарплату.',
    hint: 'Используйте { $group: { _id: "$role", avgSalary: { $avg: "$salary" } } }.',
    sampleSolution: JSON.stringify({
      aggregate: 'users',
      pipeline: [{ $group: { _id: '$role', avgSalary: { $avg: '$salary' } } }],
    }),
    verificationQuery: JSON.stringify({ count: 'users' }),
  },
  {
    id: 'mongo-11',
    title: 'aggregate — $group с $sum',
    description: 'Сумма в группировке',
    difficulty: 'intermediate',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText: 'Подсчитайте общую сумму заказов (total) по каждому статусу. Выведите статус и сумму.',
    hint: 'Используйте { $group: { _id: "$status", totalAmount: { $sum: "$total" } } }.',
    sampleSolution: JSON.stringify({
      aggregate: 'orders',
      pipeline: [{ $group: { _id: '$status', totalAmount: { $sum: '$total' } } }],
    }),
    verificationQuery: JSON.stringify({ count: 'orders' }),
  },
  {
    id: 'mongo-12',
    title: 'aggregate — $sort после $group',
    description: 'Сортировка результатов агрегации',
    difficulty: 'intermediate',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText: 'Найдите среднюю зарплату по городам и отсортируйте по убыванию.',
    hint: 'Pipeline: [{ $group: { _id: "$city", avgSalary: { $avg: "$salary" } } }, { $sort: { avgSalary: -1 } }].',
    sampleSolution: JSON.stringify({
      aggregate: 'users',
      pipeline: [{ $group: { _id: '$city', avgSalary: { $avg: '$salary' } } }, { $sort: { avgSalary: -1 } }],
    }),
    verificationQuery: JSON.stringify({ count: 'users' }),
  },
  {
    id: 'mongo-13',
    title: 'aggregate — $match + $group + $sort',
    description: 'Комбинированная агрегация',
    difficulty: 'advanced',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText:
      'Найдите товары в категории "electronics", сгруппируйте по категории и посчитайте общую стоимость всех товаров (price * stock). Отсортируйте по убыванию.',
    hint: 'Нужно сначала $match, затем $group с $sum для вычисления totalValue.',
    sampleSolution: JSON.stringify({
      aggregate: 'products',
      pipeline: [
        { $match: { category: 'electronics' } },
        { $group: { _id: '$category', totalValue: { $sum: { $multiply: ['$price', '$stock'] } }, count: { $sum: 1 } } },
        { $sort: { totalValue: -1 } },
      ],
    }),
    verificationQuery: JSON.stringify({ count: 'products', filter: { category: 'electronics' } }),
  },
  {
    id: 'mongo-14',
    title: 'aggregate — $unwind',
    description: 'Разворачивание массива',
    difficulty: 'advanced',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText:
      'Разверните массив skills у пользователей. Каждый навык должен быть в отдельном документе с именем пользователя.',
    hint: 'Используйте { $unwind: "$skills" }, затем $project для вывода имени и навыка.',
    sampleSolution: JSON.stringify({
      aggregate: 'users',
      pipeline: [{ $unwind: '$skills' }, { $project: { _id: 0, name: 1, skill: '$skills' } }],
    }),
    verificationQuery: JSON.stringify({ count: 'users' }),
  },
  {
    id: 'mongo-15',
    title: 'aggregate — $lookup (join)',
    description: 'Соединение коллекций',
    difficulty: 'advanced',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText:
      'Соедините заказы с пользователями через $lookup. Для каждого заказа покажите userId, total и имя пользователя.',
    hint: 'Используйте { $lookup: { from: "users", localField: "userId", foreignField: "_id", as: "user" } }.',
    sampleSolution: JSON.stringify({
      aggregate: 'orders',
      pipeline: [
        { $lookup: { from: 'users', localField: 'userId', foreignField: '_id', as: 'user' } },
        { $project: { userId: 1, total: 1, userName: { $arrayElemAt: ['$user.name', 0] } } },
      ],
    }),
    verificationQuery: JSON.stringify({ count: 'orders' }),
  },
  {
    id: 'mongo-16',
    title: 'aggregate — $project с вычисляемыми полями',
    description: 'Создание новых полей',
    difficulty: 'intermediate',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText: 'Для каждого товара выведите название, цену и поле inStock (true если stock > 20).',
    hint: 'Используйте { $project: { name: 1, price: 1, inStock: { $gt: ["$stock", 20] } } }.',
    sampleSolution: JSON.stringify({
      aggregate: 'products',
      pipeline: [{ $project: { name: 1, price: 1, inStock: { $gt: ['$stock', 20] } } }],
    }),
    verificationQuery: JSON.stringify({ count: 'products' }),
  },
  {
    id: 'mongo-17',
    title: 'find с $or',
    description: 'Логическое ИЛИ в запросе',
    difficulty: 'intermediate',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText: 'Найдите пользователей которые живут в Москве ИЛИ имеют зарплату выше 160000.',
    hint: 'Используйте { $or: [{ city: "Москва" }, { salary: { $gt: 160000 } }] }.',
    sampleSolution: JSON.stringify({
      find: 'users',
      query: { $or: [{ city: 'Москва' }, { salary: { $gt: 160000 } }] },
    }),
    verificationQuery: JSON.stringify({
      count: 'users',
      filter: { $or: [{ city: 'Москва' }, { salary: { $gt: 160000 } }] },
    }),
  },
  {
    id: 'mongo-18',
    title: 'aggregate — $count',
    description: 'Подсчёт документов',
    difficulty: 'beginner',
    dbType: 'mongodb',
    schema: MONGODB_SCHEMA,
    taskText: 'Подсчитайте количество доставленных заказов (status: "delivered").',
    hint: 'Pipeline: [{ $match: { status: "delivered" } }, { $count: "deliveredCount" }].',
    sampleSolution: JSON.stringify({
      aggregate: 'orders',
      pipeline: [{ $match: { status: 'delivered' } }, { $count: 'deliveredCount' }],
    }),
    verificationQuery: JSON.stringify({ count: 'orders', filter: { status: 'delivered' } }),
  },
];
